### ISSUE TITLE
Master Layouts and partials

### ISSUE THREAD

**Issue by bastienJS** [toddams/RazorLight#1]
Hello,

do master layouts with partials work?

If yes, would you please create samples how-to?

**Comment by toddams** [comment]
Hi there,
I 'm working on next release which includes Layouts, ViewImports and ViewStart features. Partials are also in backlog. Stay tuned

**Comment by toddams** [comment]
Layouts and sections are implemented in the latest release (Install-Package RazorLight -Pre)

I wrote some info in our wiki:

https://github.com/toddams/RazorLight/wiki/Layout-page
https://github.com/toddams/RazorLight/wiki/Sections
