### ISSUE TITLE
Base model always null

### ISSUE THREAD

**Issue by acopapic** [toddams/RazorLight#10]
I have a base model: 
```
public class EmailBaseDto
{
   public string Subject { get; set; }
   public string Title { get; set; }
}
```

and a layout view __LayoutEmail.cshtml where I want to use base model class:
`@model EmailBaseDto`

Then I have a derived model:
```
public class EmailForgotPasswordDto : EmailBaseDto
{
   public string CallbackUrl { get; set; }
}
```

and ForgotPassword.cshtml view which uses derived class:
`@model EmailForgotPasswordDto`

In the runtime `@Model.CallbackUrl` is as expected but `@Model.Subject` in layout view crashes because Model is null! For rendering I use this method: `engine.Parse(viewName + ".cshtml", model);`

What could be a problem here?

**Comment by toddams** [comment]
As discussed here ( #4 ) your templates do not share model with layout. If you want to pass some data to your layout - use a ViewBag. You can also find an example of it's usage at the topic I mentioned above
