### ISSUE TITLE
Compilation failing due to missing references

### ISSUE THREAD

**Issue by jordanwallwork** [toddams/RazorLight#102]
I keep running into the following error when trying to compile a razor template from a console app

    Failed to compile generated Razor template:
    - (128:45) The type or namespace name 'Mvc' does not exist in the namespace 'Microsoft.AspNetCore' (are you missing an assembly reference?)

The assembly is definitely referenced in the project, is there something I can do to ensure it gets hooked up in razorlight? I'm using v1.1.0 - unfortunately I can't upgrade currently because of a bug in aspnet core mvc 2.0.0 which cripples our core project.

**Comment by toddams** [comment]
Unfortunately, 1.* version is not supported anymore.

**Comment by jordanwallwork** [comment]
Is there anything that I can do though? I know there's stuff in 2.* to add missing namespaces, is there anything analogous in v1?
