### ISSUE TITLE
Accessing model values from the layout

### ISSUE THREAD

**Issue by ThunderDev1** [toddams/RazorLight#104]
Hi, I tried the following

Layout page

```
<div id="header">
    <span>Some content here</span>
</div>
<div id="body">
    @RenderBody()
</div>
<div>@Model.Description</div> (if this line is removed, compilation succeeds)
```

Template page

```
@model TestModel
@{
    Layout = "_Layout.cshtml";
}
<div>Hello @Model.Title</div>
```

I can't seem to access the values from the model inside my layout.

`RuntimeBinderException: Cannot perform runtime binding on a null reference`

Is there a way to do this ?

**Comment by toddams** [comment]
You should use ViewBag

**Comment by ThunderDev1** [comment]
Thanks just saw #97 which explains how it's done.
