### ISSUE TITLE
DefaultCompilerCache doesn't cache

### ISSUE THREAD

**Issue by Sumo-MBryant** [toddams/RazorLight#105]
According to the implementation of `DefaultCompilerCache`:

https://github.com/toddams/RazorLight/blob/093ec42a9b4ee70be20170b980f71ace32163ca9/src/RazorLight/Caching/DefaultCompilerCache.cs#L31-L37

On cache miss, it creates a new cache entry but doesn't appear to ever insert it into `_cache`.

**Comment by toddams** [comment]
In 2.0 version (which is supported) it's working, though - https://github.com/toddams/RazorLight/blob/dev-2.0/src/RazorLight/Caching/DefaultCachingProvider.cs
