### ISSUE TITLE
Add DisableEncoding to ITemplatePage

### ISSUE THREAD

**Issue by john-t-white** [toddams/RazorLight#106]
I am using your library to help with generating HTML and text content. What I would like to do is get the compiled template, and then set DisableEncoding based on a setting I have per template stored in some metadata.

**Comment by toddams** [comment]
That's a good point, will do

**Comment by john-t-white** [comment]
Thanks.  Any plans on when the next release might be?

**Comment by toddams** [comment]
On Sunday
