### ISSUE TITLE
Injected Dependencies with "Scoped" ServiceLifetime are not refreshed with new requests.

### ISSUE THREAD

**Issue by Disciplemike** [toddams/RazorLight#109]
@inject does not properly detect end of scoped lifestyle for dependencies.

I have a stored view that has contains "@inject IAuthorizationService AuthorizationService".
In the content of that view I call out to resolve a policy check against the IAuthorizationHandler.
The handler has a ctor that takes a DbContext as a dependency (this dbcontext is defined as a scoped service in startup).
On the "HandleRequirementAsync" method, the dbcontext is used to retrieve data from the database.

Here's the issue:
If I start the application and navigate to the page with the RazorLight.ParseString content, it will load correctly reflecting what's in the database.  If I change the stored HTML (in the database) and refresh the page, the content is updated correctly.
However, if I change the fields in the database that the "HandleRequirementAsync" method is looking at, the page generated from the RazorLightEngine is NOT correctly updated.  Upon debugging, I see the ctor is hit and creates a new context, but when the "HandleRequirementAsync" method is hit, the context is still the original one, with the old database values.
The odd part is that all other views handled by normal controllers work with this handler just fine (i.e. when I change the database properties for this policy, the pages render correctly).

I'm pretty sure this is an issue with the @inject somehow not seeing that the scope has changed, and therefore maintaining the old instance.
If I set my dbcontext to Transient in startup, the @inject behaves correctly;however, I don't want a transient dbcontext.

Am I doing something wrong, or is this an issue with @inject?

**Comment by toddams** [comment]
Must be fixed in beta1
