### ISSUE TITLE
Not compatible with .NetFramework v4.6.1

### ISSUE THREAD

**Issue by kongres** [toddams/RazorLight#11]
Hello. Thank you for the great library. It has simple features which are most important. I like this library.

I have a question. Is it possible to make it work with framework 4.6.1? For some reason I can't use next frameworks. So it would be great to make it work with .net 4.6.1.

Thanks.
Igor.

**Comment by toddams** [comment]
Hello there,
Wow, thank you so much, I appreciate your feedback :)
I will try to support as low .NET version as possible (maybe even 4.5), so stay tuned 👍

**Comment by kongres** [comment]
Thank you.
Using embed resources is very useful and important for me. And it was implemented in .Net Core very great and easy.

```
"buildOptions": {
    "embed": [
      "Test1.cshtml",
      "Test2.cshtml",
      "Test3.cshtml",
      "Test4.cshtml",
       ...
    ]
  },
```
 So if I start to use your library for my email service for generation emails it will be great!!

I will wait for your response.

Thanks.

**Comment by toddams** [comment]
Added .NET 4.5.1 (and higher) support

**Comment by kongres** [comment]
Great! Thank you!!! Will try in my project soon.

**Comment by bremussolutions** [comment]
I can't use RazorLight with .NET 4.6.1. in a class library:

> The dependency RazorLight >= 1.0.0-rc2 could not be resolved.

My _project.json_ looks like this:

`{
  "version": "1.0.0-*",

  "dependencies": {
    "HtmlAgilityPack": "1.4.9.5",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.1.0",
    "Microsoft.AspNetCore.Razor": "1.1.0",
    "NETStandard.Library": "1.6.1",
    "RazorLight": "1.0.0-rc2"
  },

  "frameworks": {
    "net461": {}
  }
}`

Is that a problem on my or your side?

**Comment by toddams** [comment]
You are targeting .net 4.6.1 but referencing NETStandard.Library. I'm not sure it's correct
