### ISSUE TITLE
If you are parsing string why do you need EngineFactory.CreatePhysical

### ISSUE THREAD

**Issue by nukec** [toddams/RazorLight#110]
How can I instantiate engine without having psychical folder on hard drive, if I want to do small test with string?

**Comment by Disciplemike** [comment]
What type of project are you doing this test within?

**Comment by toddams** [comment]
You are right, no need to have hard drive for strings. 
Already in progress for 2.0 and will be released soon

**Comment by toddams** [comment]
Fixed in beta1
