### ISSUE TITLE
Cannot render template with @model

### ISSUE THREAD

**Issue by hkosmidi** [toddams/RazorLight#111]
I am using razorLight in a non-MVC project to render html strings.
I have a custom model and I use razor like:
``` csharp

var engine = EngineFactory.CreatePhysical(Path.Combine(AppContext.BaseDirectory, "PrintTemplates"));
var data = new RoutineReportModel() { versionNumber = "1" };
string result = engine.Parse("test.cshtml", data);
```

This throw exception: Failed to parse razor page. See ParserErrors for more details

My test.cshtml file is:

``` html
@model PrintModels.RoutineReportModel

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>test</title>
</head>
<body>
<h1>test</h1>
    <p>@model.versionNumber</p>
</body>
</html>
```

If I remove <p>@model.versionNumber</p> it works correctly. What puzzles me is that when I edit the file there is no intellisense from VS2017. As if I edit a simple html page. Am I missing something?

**Comment by toddams** [comment]
Please, follow what exception message is saying and look in ParserErrors property of ab exception

**Comment by hkosmidi** [comment]
After restarting VS, intellisense works in cshtml but now I got the following:

{RazorLight.TemplateCompilationException: Failed to compile generated Razor template:
- (13:8) The name 'Model' does not exist in the current context

In the cshtml file the line is:
<p>@Model.versionNumber</p>

**Comment by toddams** [comment]
That's basic Razor

When you specify model type - @model (lower case).
When you reference a model property - @Model.someProperty
