### ISSUE TITLE
Suggestion for caching

### ISSUE THREAD

**Issue by lwansbrough** [toddams/RazorLight#113]
Given that caching is disabled for non-file-based templates, I wonder if it would be possible to enable it. I haven't looked at the code, but I'm assuming you're not caching string templates because you can't assert whether or not a string is meant to replace and older string, or if it's a new template entirely. So why not allow the user to define a template name along with the template string, that way caching can be done?

**Comment by toddams** [comment]
at 2.0 version string templates are cached as well

**Comment by jjxtra** [comment]
How are the string templates cached? Is this a parameter that can be controlled? Can we provide a token that provides a last modified date/last access date?
