### ISSUE TITLE
Cannot build project with 2.0.0-alpha3

### ISSUE THREAD

**Issue by Igoreso** [toddams/RazorLight#114]
The following line:
```
services.AddRazorLight("/Views");
```
gives build error:
```
      Error CS7069: Reference to type 'IEngineConfiguration' claims it is defined in 'RazorLight', but it could not be found (71, 13)
```
Any ideas? Same happens with alpha1 and alpha2 versions.

edit:
Workaround found in this comment:
https://github.com/toddams/RazorLight/issues/63#issuecomment-328362211

```
        services.AddSingleton<IRazorLightEngine>(f =>
        {
            return (new EngineFactory())
                .ForFileSystem($"{Environment.ContentRootPath}\\Views");
        });
```

Except instead of `Environment` I use `IHostingEnvironment env` that I added as a parameter to `ConfigureServices` like this (example):
`public void ConfigureServices(IServiceCollection services, IHostingEnvironment env, IConfiguration config)`

**Comment by toddams** [comment]
RazorLight.MVC does not reference the latest version of RazorLight.

New version is coming soon

**Comment by toddams** [comment]
Check out new beta1 version

**Comment by Torshe** [comment]
Still have this problem with beta1 version and MVC version 1.0.4 version.

**Comment by jzabroski** [comment]
Can you create an example project in a new issue? I'm not familiar with Razorlight.mvc as I started helping with Razorlight 2.0 bera2. I don't mind looking into this but without a repro, not sure where to start.

**Comment by Torshe** [comment]
Yes sir. I will make an example tomorow.
