### ISSUE TITLE
Json as a model

### ISSUE THREAD

**Issue by farshid3003** [toddams/RazorLight#117]
RazoreEngine support JObject type for model and I could dynamically render my email templates like this:

```
             var sampleModel = Newtonsoft.Json.Linq.JObject.Parse(Model_In_Json_Format_String);
            string bodyTempKey = $"{Model.Name}#v{Model.Version}";
            var body = Engine.Razor.Run(bodyTempKey,null, sampleModel);

```

but RazoreLight does not support jobject. 
Do you have any plan to fix this?

**Comment by toddams** [comment]
I don't think it's a bug, so no need to **fix** it, but as a new feature, I think, it would be nice to have :)

**Comment by farshid3003** [comment]
RazorEngine has this feature for all dynamic objects
https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/RazorDynamicObject.cs
Are you going to add this feature ?

**Comment by farshid3003** [comment]
I test Branch "dev-2.0" and this case works there as a charm. when are you going to lunch this version ?
