### ISSUE TITLE
Version 2.0.0 alpha 3 throws exception in Azure

### ISSUE THREAD

**Issue by howardlo** [toddams/RazorLight#118]
Was able to get an asp.net core 2.0 app with V2.0.0-alpha3 running through IISExpress in Visual Studio and also in standalone (command line). Then when I push the app to Azure I get this exception.

`InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'`

Any suggestions?

**Comment by howardlo** [comment]
There is a similar issue (https://github.com/dotnet/core-setup/issues/2113) and noticed that in my deployment in Azure it was missing the "refs" directory. I added the lines PreserveCompilationContext and MvcRazorCompileOnPublish as such in the .cproj file:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
  </PropertyGroup>
```

and voila! the refs directory appeared and contains the Microsoft.Win32.Registry and everything seems to be working now.

**Comment by mthird** [comment]
Thanks, @howardlo !  This resolved my issue with the beta version, too.
