### ISSUE TITLE
Support to @inject

### ISSUE THREAD

**Issue by diegobrum** [toddams/RazorLight#12]
Hi!

I'm trying to use @inject to inject via .netCore DI system some services in my View.
But "@inject" it's not a known tag in RazorLight.

Can you implement this in some future version? Do you want some help to do this?

To now I use a workaround.

Rather than
`
@inject IServiceUri ServiceUri
`

I used
`
@{var ServiceUri = new ServiceUri();}
`

But... I lost DI :'(

**Comment by toddams** [comment]
@inject is a feature of ASP.NET MVC, but I planned to add an integration
Expect this on beta5 release

**Comment by toddams** [comment]
- **Add package**

    ````Install-Package RazorLight.MVC````

- **Add RazorLight services in Startup.cs**

````CSharp
        public void ConfigureServices(IServiceCollection services)
        {
            ....
            services.AddRazorLight("/Views"); // <- This one
            ....
        }
````
- **Inject services to your templates**
````CSharp
@inject MyProject.TestViewModel myModel
````

**Comment by Aledever4i** [comment]
@KishorTiwari @lnodaba 

Hello. As i understand framework realization, you cannot use base user scenario for using @inject .

But what you should do:

First way:
Expand your services collection: services.AddRazorLight()
In controller or service constructor get IRazorLightEngine service, and use it for your tasks.

Another way:
You can use example from Tests, method Ensure_Registered_Properties_Are_Injected
