### ISSUE TITLE
Sandbox support

### ISSUE THREAD

**Issue by Genbox** [toddams/RazorLight#126]
If templates are user supplied, they can write `@System.Diagnostics.Process.Start("evil command")` to execute any arbitrary command on the server. It would be great to add sandbox support, such that users can only use functionality in a given assembly.

Looking through the code, it seems that DefaultMetadataReferenceManager resolves from assemblies that "operatingassembly" is compiled against, but since any assembly, will be compiled with .NET Core, it will have access to System.Diagnostics etc.

Users can implement their own MetadataReferenceManager and just not resolve for assemblies they don't want to support. However, upstream security configuration to limit the impact of code execution would be preferred.

**Comment by toddams** [comment]
You can find our discussion about on this topic on #38

**Comment by Genbox** [comment]
Hi @toddams,

Thanks for your response. As for the discussion:
- AppDomains: If the AppDomain has identical assemblies loaded as the parent domain, it is still possible for users to do execute commands. It is definitely possible to compile Razor to an assembly and load it using an external process, which would replicate the functionality of the AppDomain. However, it is not exactly a pretty solution.
- Regular expressions: Definitely not a solution in any case.

I think the simpler solution here is to limit what assemblies to load in the assembly resolver. Right now I load the C# type system + some needed assemblies to actually execute the Razor code.

**Comment by toddams** [comment]
Do I understand right that you can already achieve it by already built functionality of RazorLight?

**Comment by Genbox** [comment]
Pretty much, yes. I implemented my own IMetadataReferenceManager and only allow certain assemblies to be loaded. System.dll, System.Linq.dll etc. so System.Diagnostics and System.Reflection are never loaded when compiling the Razor code.

**Comment by dlukyanov** [comment]
@Genbox  is there an example how to activate "sandbox"?

**Comment by Genbox** [comment]
> [@Genbox](https://github.com/Genbox) is there an example how to activate "sandbox"?

A few changes in the Razor runtime since 2017 have broken the way you can block assemblies from loading. I ended up writing a Razor rendering system based on Razor's engine internals with sandbox support via an engine feature called `DefaultMetadataReferenceFeature`.

I essentially reversed what ASP.net was doing before they converted to using a code generator for view pre-compilation. Unfortunately, there is a single hard-coded class that doesn't have an interface, which pulls in the entire ASP.net runtime. I asked the Razor team to consider a small refactoring to alleviate it, but they decided against it, arguing it would increase their public API surface (with 1 interface...).

If you want to write something similar, take a look at `RazorProjectEngine.Create()` and `RazorProjectEngine.Process()`
