### ISSUE TITLE
Error while using IncludeAsync from layout page

### ISSUE THREAD

**Issue by kae** [toddams/RazorLight#13]
```
RazorLight.RazorLightException: Can't locate a page as PageLookup is not set
```

It looks like trouble is from PageRenderer 
```
private TemplatePage GetLayoutPage(string layoutKey)
```
where you create from page factory, but doesn't set PageLookup property of created object

**Comment by kae** [comment]
Is there an option to release fixed version of library before complete feature set planned for beta5?

**Comment by toddams** [comment]
Beta5 is almost done, and I hope tomorrow I'll upload it, thank you for patience :)

After 1.0.0 stable release I'll deliver minor patches as soon as bugs are fixed.

**Comment by toddams** [comment]
fixed
