### ISSUE TITLE
How do I add a service with the new version?

### ISSUE THREAD

**Issue by jcphlux** [toddams/RazorLight#130]
I am using the RazorLight2 package on NuGet. Before I when I used ASP Core 1 I would add a service like the code below but now I get and error on that. 
```
     services.AddSingleton<IRazorLightEngine>(f =>
            {
                return (new EngineFactory())
                    .ForEmbeddedResources(typeof(ContactMessage));
            });
```
Please let me know any details you might need to help TS the issue.

**Comment by toddams** [comment]
````EngineFactory```` is now obsolette, so you must use ````RazorLightEngineBuilder```` instead

````CSharp
    services.AddRazorLight(() => 
    {
        return new RazorLightEngineBuilder().Build();
    });
````
