### ISSUE TITLE
Layout throws null reference exceptions

### ISSUE THREAD

**Issue by azaytsev-csr** [toddams/RazorLight#132]
Trying to use a fairly simple set up (.net core 2.0, windows, RazorLight `2.0.0-beta1`)

```
var engine = new RazorLightEngineBuilder()
                    .UseMemoryCachingProvider()
                    .UseFilesystemProject(@"C:\Wherever\My\Templates\are")
                    .Build();

 var p = "@{ViewBag.Title = \"test\"; Layout = \"_l\";} @Model.Var1";
                var pp = engine.CompileRenderAsync("tk", p, new { Var1 = "var1", Var2 = "var2" }).GetAwaiter().GetResult();
```

My `_l.cshtml` is:

```
@RenderBody()

@Model.Var2
```

If i remove ```@Model.Var2``` from the layout, i don't get any NullReferenceExceptions.

**Comment by toddams** [comment]
Layout has no model in a Razor template

**Comment by azaytsev-csr** [comment]
@toddams but it works in `RazorEngine`? (am trying to port code from RazorEngine to .net core using RazorLight)

**Comment by toddams** [comment]
I have no idea if it works in RazorEngine, this is a different library :)

But I see there is a real need to share model with layout, so I will add this

**Comment by toddams** [comment]
This issue is now tracked in #123
