### ISSUE TITLE
Cannot find compilation library location for package 'Microsoft.Win32.Registry' dot net core 2.0

### ISSUE THREAD

**Issue by tjackadams** [toddams/RazorLight#137]
Just trying to integrate this package into a class library to send emails from a background job.
The issue only happens when the project has been published, it works fine in the develop environment.

The exception happens in the CompileRenderAsync method

here is my code
```

            var engine = new RazorLightEngineBuilder()
                .UseEmbeddedResourcesProject(typeof(PortalCoreModule))
                .UseMemoryCachingProvider()
                .Build();

            string emailBody = await engine.CompileRenderAsync(templateKey, viewModel, viewModelType);
```

and here is the exception that is thrown

> System.InvalidOperationException
> 
> Cannot find compilation library location for package 'Microsoft.Win32.Registry'
> 
> System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
>    at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(DependencyContext dependencyContext)
>    at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
>    at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
>    at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)
>    at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
>    at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
>    at RazorLight.Compilation.RoslynCompilationService.CompileAsync(IGeneratedRazorTemplate razorTemplate)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at RazorLight.Compilation.TemplateFactoryProvider.<CompileAsync>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at RazorLight.Compilation.TemplateFactoryProvider.<CreateFactoryAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at RazorLight.RazorLightEngine.<CompileRenderAsync>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Portal.Notifications.EmailNotificationManager.<PrepareSendAsync>d__9`1.MoveNext() in C:\Users\tom\Source\Repos\portal\src\Portal.Core\Notifications\EmailNotificationManager.cs:line 124
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Portal.Notifications.EmailNotificationManager.<SendAsync>d__8`1.MoveNext() in C:\Users\tom\Source\Repos\portal\src\Portal.Core\Notifications\EmailNotificationManager.cs:line 112
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Portal.BackupMonitoring.BackupMonitoringManager.<DailyBackupReports>d__21.MoveNext() in C:\Users\tom\Source\Repos\portal\src\Portal.Core\BackupMonitoring\BackupMonitoringManager.cs:line 1228

I had a look around for similar issues and ending up adding the following to my .csproj

`<PreserveCompilationContext>true</PreserveCompilationContext>`
`<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>`

but these settings didn't seem to change anything. Any ideas what could be causing this?

**Comment by toddams** [comment]
Did you do clean/rebuild after you changed csproj?

**Comment by tjackadams** [comment]
The project is deployed via a CI server so its a new build anyway.
But just to confirm, i have just cleaned the solution, rebuilt it and manually copied the files over to deployment and the issue is the same

**Comment by tjackadams** [comment]
Ok i think this issue can be closed now.
The class library that contained the razor views was referenced by a web project which was the main entry point.
Adding `<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>` to the web project .csproj then fixed this.
