### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Abhimanyu41** [toddams/RazorLight#139]
Hi @toddams 

I have upgraded from Asp Core 1.1 to Asp Core 2.0.
Getting error 
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
  Source=RazorLight.MVC
  StackTrace:
   at RazorLight.MVC.MvcServiceCollectionExtensions.AddRazorLight(IServiceCollection services, String root, Action`1 config)
   at GPSWeb.Startup.ConfigureServices(IServiceCollection services) 

At startup file
in services.AddRazorLight("/Views/MailTemplates"); line

**Comment by toddams** [comment]
RazorLight.MVC is no longer used, and IServiceCollection extensions moved to main assembly

Also api is changed - https://github.com/toddams/RazorLight/blob/master/src/RazorLight/Extensions/ServiceCollectionExtensions.cs

**Comment by Abhimanyu41** [comment]
thanks for the reply fast @toddams 
i am beginner to Asp Core and so in MVC
it will really helpful if you have any demo site where this is implemented

**Comment by Abhimanyu41** [comment]
Which library i should use instead of RazorLight.MVC for core 2

**Comment by toddams** [comment]
RazorLight itself, it's included, no need to have extra library

**Comment by golayp** [comment]
Hello maybe is it a good idea to update [wiki entry](https://github.com/toddams/RazorLight/wiki/ASP.NET-MVC-Core-integration) on this topic.
