### ISSUE TITLE
Can not resolve a content for the template if viewBag is null

### ISSUE THREAD

**Issue by Rizzen** [toddams/RazorLight#140]
I'm trying to render very simple template without Model:
```C#
string template = "Hello, Welcome to RazorLight repository";

string result = await engine.CompileRenderAsync("templateKey", template);
```
But i have runtime error 
```
Can not resolve a content for the template "{0}" as there is no project set.
You can only render a template by passing it's content directly via string using coresponding function overload
```
Should it works?

ADD:
If I pass empty object as third argument in CompileRenderAsync(), it works fine.

**Comment by deckertron9000** [comment]
You are using the method that requires a model as the second parameter. The runtime error is expected in this case.

**Comment by Rizzen** [comment]
Is there method to compile template without model?

**Comment by toddams** [comment]
Pass model as null?

**Comment by Rizzen** [comment]
@toddams it works only if i using it something like that
```C#
string result = await engine.CompileRenderAsync("key", template, null, null, null);
```
Otherwise i have runtime failure
