### ISSUE TITLE
Update the Nuget Package

### ISSUE THREAD

**Issue by sameera** [toddams/RazorLight#142]
The Nuget package seems to be quite out of date with classes like RazorLightEngineBuilder missing.
Appreciate if someone could update it.

**Comment by toddams** [comment]
Beta1 is the lastest version and it should contain all the changes

**Comment by sameera** [comment]
Ok, my mistake. I was using RazorLight2 package thinking it had the latest code in the v2 branch.

**Comment by toddams** [comment]
That's not my package and it confuses people
