### ISSUE TITLE
Cannot convert from 'RazorLight.Caching.TemplateCacheItem' to 'RazorLight.ITemplatePage'

### ISSUE THREAD

**Issue by huanbd** [toddams/RazorLight#143]
Hi,
I'm use code to get cache template but It has error
`var cacheResult = engine.TemplateCache.RetrieveTemplate(buildedTemplate.Id);
if (cacheResult.Success)
{
Html = await engine.RenderTemplateAsync(cacheResult.Template, demo);
}`
So how to resolve that, thanks!

**Comment by toddams** [comment]
So what is the problem?

RetriveTemplate returns TemplateCacheItem, not ITemplatePage

**Comment by huanbd** [comment]
Hi toddams,
I've followed your guide and It was resolved
Today, I'm debug code to see how it cache, but I'm see that It was not saved to cache
Can you show me how to correct ?
This is my code
`var engine = new RazorLightEngineBuilder()`
`                            .UseMemoryCachingProvider()`
`                            .Build();`

`var cacheResult = engine.TemplateCache.RetrieveTemplate(templateId);`
`// It always return false`
                    `if (cacheResult.Success)`
                    `{`
                       `resultHtml = await engine.RenderTemplateAsync(cacheResult.Template.TemplatePageFactory(), obj);`
                   ` }`
                    `else`
                   ` {`
                        `resultHtml = await engine.CompileRenderAsync(templateId, htmlTemplate, obj);`
                   ` }`
Thank you!
