### ISSUE TITLE
Precompile should prefix `dotnet-` for tool

### ISSUE THREAD

**Issue by onionhammer** [toddams/RazorLight#144]
In order to be usable as a 'dotnet' tool, the assembly should be prefixed with 'dotnet-', that way the user can precompile the razor views in their project by calling `dotnet razorlight-precompile` and precompile all their views when the user uses

`<DotNetCliToolReference Include="RazorLight" Version="2.0.0-beta1" />`

**Comment by toddams** [comment]
Precompile feature is not yet released, so what is this issue about? :)

**Comment by onionhammer** [comment]
Ah ok, didnt realize you were developing that feature on trunk
