### ISSUE TITLE
QuickStart "To render a compiled template" code should be updated

### ISSUE THREAD

**Issue by rshillington** [toddams/RazorLight#145]
I think the line:
`string result = await engine.RenderTemplateAsync(cacheResult.Template, model);`

should be
`string result = await engine.RenderTemplateAsync(cacheResult.Template.TemplatePageFactory(), model);`

**Comment by toddams** [comment]
So why don't you create a Pull Request, instead of an issue? :)

**Comment by rshillington** [comment]
Done
