### ISSUE TITLE
Could we use this library with .Net 4.6.1 in the future?

### ISSUE THREAD

**Issue by glikoz** [toddams/RazorLight#147]
Will this library compatible with .Net Framework 4.6.1 ?
It seems  Full .Net Supported version was updated a year ago.
https://github.com/toddams/RazorLight/tree/full-net-support

Thanks.

**Comment by toddams** [comment]
Yep, beta2 bring back.NET Framework support

**Comment by glikoz** [comment]
Hi,

Do you have a roadmap for it, when will beta2 be completed? Also RC? 

Ps:Thanks for good work.

**Comment by glikoz** [comment]
I can add Beta1 version to my .Net Framework 4.6.1 console application via Nuget.  But during test I'm getting weird error 
![image](https://user-images.githubusercontent.com/1757659/35592596-90efc1fa-061e-11e8-8fcb-29b79d741905.png)

Am I forcing wrong way?

**Comment by glikoz** [comment]
We were able to use current beta1 version with .net framework 4.6.1 console application, the problem that i sent is related with dependencycontext, also we patched it, i will send our solution.

**Comment by RomanDidenko** [comment]
Hi @glikoz, can you please share your solution?

**Comment by glikoz** [comment]
I will share at the weekend, best wishes.

**Comment by glikoz** [comment]
Now I'm sharing :) You can find %100 working .Net 4.6.1 console application that uses RazorLight. It's name is RazorLight.Sandbox.Net. Download my fork and run

https://github.com/glikoz/RazorLight/

**Comment by glikoz** [comment]
* I've added RazorLight Beta-1 to RazorLight.Sandbox.Net console application
* I've updated All nugetPackages
* Remove RazorLight.dll (that comes with Nuget)
* Add RazorLight.dll from Solution 

I wrote these if you have a problem after Nuget Restore use same path.

Best wishes.

**Comment by chrisbuttacavoli** [comment]
I am receiving the exact same error message when I try running RazorLight in a 4.6.1 class library. I am using NUnit to test my templates.

`var razor = new RazorLightEngineBuilder()
                    .SetOperatingAssembly(Assembly.GetAssembly(typeof(ITemplateGenerator))) // The assembly with the templates
                    .UseFilesystemProject(this._templatePath)
                    .UseMemoryCachingProvider()
                    .Build();

            var templateString = await razor.CompileRenderAsync("Test.cshtml", new { }); // Throws here`

When I run this code in my MVC project, there are no issues, doesn't seem like it can resolve the dependencies. Would really like this fixed so I can use automated tests for my application with this code.

The raw exception message:
`Result StackTrace:	
at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(DependencyContext dependencyContext)
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
   at RazorLight.Compilation.RoslynCompilationService.CompileAsync(IGeneratedRazorTemplate razorTemplate)`

**Comment by adospace** [comment]
@toddams sorry to bother, any eta for beta2: we are really interested in use RazorLight with full framework

**Comment by Tieantono** [comment]
Yes, I would like to know to, my team are really interested on using RazorLight with .NET Framework.

**Comment by zagros** [comment]
@toddams - we are getting this same error with .net 4.6.2.  Your sandbox uses Dependency Injection 2.0.0.0 but the version 2.0.3 or higher have the error which you seem to have fixed in #159 

Our project is awaiting your Beta2 release.  Can you please provide an ETA?

**Comment by dlopatin-ms** [comment]
It seems the project is dead. I tried different options for working with .net Framework - always errors :(

**Comment by toddams** [comment]
Project is pretty alive. .NET framework is dead

**Comment by jzabroski** [comment]
@toddams I think the reason people think the project is dead is because the last official non-beta release was a long time ago, and it's confusing as hell when you go to nuget.org and search for Razorlight package.

@dlopatin-Ms Your comments are simply destructive and should be flagged as inappropriate. What is your point in calling something dead? Do you want to take it over?Please open issues for working with .net standard 2.0 (not .net framework 4.8). Due to complexity, I can't spend time supporting the old .net csproj project type.

**Comment by dlopatin-ms** [comment]
> Project is pretty alive. .NET framework is dead

And it is bad, I still support a big WinForms project

**Comment by dlopatin-ms** [comment]
> I think the reason people think the project is dead is because the last official non-beta release was a long time ago, and it's confusing as hell when you go to nuget.org and search for Razorlight package.

Exactly, but I'm glad that you work on the project.

**Comment by jzabroski** [comment]
Best way to show appreciation is to provide good issues that don't require lots of time to understand. Please open a new issue rather than continue commenting on a 4 year old issue. Thank you!

**Comment by toddams** [comment]
@dlopatin-ms for .NET framework there is an alternative https://github.com/Antaris/RazorEngine

If it's urgent for you

**Comment by dlopatin-ms** [comment]
> @dlopatin-ms for .NET framework there is an alternative https://github.com/Antaris/RazorEngine
> 
> If it's urgent for you

RazorEnging really died two years ago))

We are discussing so far to bring functionality to misroservice. I basically agree with @jzabroski - there is no big reason to support old framework.

**Comment by niaher** [comment]
@jzabroski @toddams just wanted to follow up and see if NET Framework 4.7 supported at this time? I've tried using `2.0.0-rc.3` on a NET 4.7.2 project but keep getting `The type or namespace name 'Razor' does not exist in the namespace 'RazorLight'`.

I can of course use https://github.com/Antaris/RazorEngine instead, but wanted to check with you first. Thank you.
