### ISSUE TITLE
net462 TemplateCompilationException

### ISSUE THREAD

**Issue by aristovg** [toddams/RazorLight#15]
Hi, 

We're getting the TemplateCompilationException on net462. 

I noticed that CompilationReferences in RoslynCompilerService  doesn't contain the reference to Microsoft.CSharp.dll on net462 (the library isn't in list of dlls returned by System.AppDomain.CurrentDomain.GetAssemblies event if package explicitly referenced for all target frameworks). 

I've referenced the package and explicitly added the dll in MetadataResolver and its worked, but there should be a better way to do this :)

`metadataReferences.Add(MetadataReference.CreateFromFile(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "Microsoft.CSharp.dll")));` 

Thank you

**Comment by toddams** [comment]
Thank you for reporting :+1: 

I will take a look at this one asap

**Comment by toddams** [comment]
I tried to reproduce this bug on .NET 4.6.2, but my templates were successfully compiled.

I'd be very thankfull if you give me an exampe of the code that causes that exception, thank you

**Comment by aristovg** [comment]
@toddams 

We're getting a failure even on minimal example (tested on two machines with win10 + net4.6.2)
https://gist.github.com/anonymous/3c2223cb296df2773c2c88227afbec11

It crashes with RazorLight.TemplateCompilationException. CompilationErrors is the following: 
`"Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'"`

**Comment by toddams** [comment]
Confirmed, I reproduced this bug on the new project. Strange that compiler gives no exception on my SandBox project, even though Microsoft.CSharp.dll is not referenced

I'm working on a fix, thank you

**Comment by toddams** [comment]
Fixed in beta6
