### ISSUE TITLE
TemplateCompilationException: Linq not available

### ISSUE THREAD

**Issue by Fewthlix** [toddams/RazorLight#150]
Since I updated from 2.0.0-alpha3 to 2.0.0-beta1 I get the following error:

> TemplateCompilationException: Failed to compile generated Razor template:
> (146:41) 'ICollection<CreditMemoLineItem>' does not contain a definition for 'Where' and no >extension method 'Where' accepting a first argument of type 'ICollection<CreditMemoLineItem>' >could be found (are you missing a using directive or an assembly reference?)

I'm using RazorLight like that:

`var engineFactory = new RazorLightEngineBuilder().UseMemoryCachingProvider().Build();`
`var pdfContent = await engineFactory.CompileRenderAsync("CreditMemo", template, creditMemo, typeof(CreditMemo));`

Is this a bug or do I have do add some additional using statements in my html view?

**Comment by twenzel** [comment]
I guess you have to add "@using System.Linq" to your template

**Comment by Fewthlix** [comment]
Thanks, that's the solution!
