### ISSUE TITLE
PreserveCompilationContext in Release mode

### ISSUE THREAD

**Issue by benjamin-hodgson** [toddams/RazorLight#156]
I'm getting the error "Make sure PreserveCompilationContext is set to true in *.csproj file" when I build in Release mode. I've set `PreserveCompilationContext` in the csproj, in its own separate `PropertyGroup` as detailed [here](https://github.com/toddams/RazorLight/issues/127), and it works in debug mode but not in release mode.

This is when writing a console application on .NET Core 2.1.4.

Any tips on getting this working?

**Comment by toddams** [comment]
Are you sure about .NET Core 2.**1**.4 ?

**Comment by benjamin-hodgson** [comment]
Sorry, should have been more specific. Version 2.1.4 of the SDK/command line tools. I guess that’d be v2.0 of the framework itself

**Comment by benjamin-hodgson** [comment]
Has this been resolved?

**Comment by toddams** [comment]
Yes, now if it fails to get metadata references using DependencyContext - it will resolve it using Referenced assemblies.

**Comment by benjamin-hodgson** [comment]
That's great news. Thanks!
