### ISSUE TITLE
How to inline params with string

### ISSUE THREAD

**Issue by Ibrahim-Islam** [toddams/RazorLight#157]
I am trying to generate code in some other language. The following gives me an error because it considers `Type` a method rather than a property:
```
case class @Model.Type(@Model.Params)
```

**Comment by toddams** [comment]
Are you sure you have "Type" function in a model?

**Comment by Ibrahim-Islam** [comment]
No I dont. case class is Scala syntax which is what I am trying to generate but this seem to work:
```
case class @(@Model.Type)(@Raw(Model.Params))
```
becomes
```
case class Customer(id: Int, name: String)
```
