### ISSUE TITLE
TagHelpers not supported?

### ISSUE THREAD

**Issue by kudoz83** [toddams/RazorLight#16]
The following should render different Hello World variants based on the current
runtime environment.  It appears the addTagHelper directive is not being honored since it is what recognizes the environment tag.

```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<environment names="Development">
	Hello World (Dev)
</environment>
<environment names="Staging,Production">
	Hello World (Prod)
</environment>
```

project.json is using 
`"RazorLight.MVC": "1.0.0"`

**Comment by toddams** [comment]
That's true, RazorLight has borrowed some features from ASP.NET MVC (models, sections, layouts, partials), and there is also an integration package (RazorLight.MVC) that allows you to inject services into your templates via built in dependency injection, but HTML helpers and TagHelpers are not implemeted. This requires quite some time and was not at the first priority list.

There is a workaround for your case:
The IHostingEnvironment service provides the core abstraction for working with environments. Just inject into your template and check EnvironmentName property

````CSharp
@inject IHostingEnvironment env

@if(env.EnvironmentName == "Development")
{

}
````
