### ISSUE TITLE
Please update Samples and fix the bugs in it

### ISSUE THREAD

**Issue by martonx** [toddams/RazorLight#162]
Hi,

I tried to use samples, but there are more issues with it:
![image](https://user-images.githubusercontent.com/407433/37309756-2957c22e-2642-11e8-9f97-c5bc68026e22.png)
With these issues I can't try it out.
Please update samples!

Thank you very much!

**Comment by toddams** [comment]
This is not a sample project, but sandbox. You can delete it

**Comment by martonx** [comment]
Yes, one part of the issues are from sandbox, but please check the lowest error :) that is real error, and the depreciated new EngineFactory().Create(project) should be updated also.

**Comment by martonx** [comment]
Thanks about talking. Actually I have issue with use RazorLight with templates from real DB, this is why I wanted to check the samples in move.
