### ISSUE TITLE
2.0 beta.1 not compatible with .net core 2.0 ?

### ISSUE THREAD

**Issue by snielsson** [toddams/RazorLight#163]
Hi, I am trying the simplest possible .net core 2.0 console app:

```
using System;
using RazorLight;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
	        var engine = new RazorLightEngineBuilder()
		        .UseMemoryCachingProvider()
		        .Build();
	        string template = "Hello, Model.Name. Welcome to RazorLight repository";
	        string result = engine.CompileRenderAsync("templateKey", template).Result;
		Console.WriteLine(result);
	        Console.ReadLine();
        }
    }
}
```

I get this exception when calling CompileRenderAsync:

One or more errors occurred. (Can not resolve a content for the template "{0}" as there is no project set.You can only render a template by passing it's content directly via string using coresponding function overload)

I also observed this on package restore:

    Package RazorLight 2.0.0-beta1 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package RazorLight 2.0.0-beta1 supports: netstandard2.0 (.NETStandard,Version=v2.0)
    One or more packages are incompatible with .NETCoreApp,Version=v2.0.

So, is 2.0 beta1 not compatible with .net core 2.0 ?

**Comment by toddams** [comment]
You didn't pass a model, and you are using an overload that resolves template content from projects (file, embedded resource, etc)

Project is compatible with .net core 2.0
