### ISSUE TITLE
Are Layouts Fully Supported?

### ISSUE THREAD

**Issue by kudoz83** [toddams/RazorLight#17]
I'm using razorlight to emulate a "Razor Website" from .NET4

I've got some cshtml files in my wwwroot folder, and a generic controller that handles all requests for .cshtml content containing an engine targeting appropriately.  Everything seems to work reasonably well until I try to assign a layout to one of the cshtml pages.   

The control returns the requested page as such
```
var result = await ParseAsync(path, model);
Response.StatusCode = 200;
return Content(result, "text/html");
```

I'm setting Layout the same way it looks like you do in you tests... 
```
@{
	Layout = "_layout.cshtml";
}
```

The layout and cshtml page being rendered are both in the engine's root path (wwwroot). 

Any thoughts?   Let me know if this isn't clear.

**Comment by toddams** [comment]
Can you show please how you are creating an RazorLightEngine?

**Comment by kudoz83** [comment]
I'm using the services collection for DI

`services.AddRazorLight(HostingEnvironment.WebRootPath);`

and the controller constructor
```
public RazorResourceController(IHostingEnvironment hostEnv, IRazorLightEngine engine)
		{
			this.HostEnvironment = hostEnv;
			this.Engine = engine;
		}
```

For completeness, here is the rest of the controller logic
```
// This route handles requests for any resource requested ending in ".cshtml"
		// Ideally the static file processor is handling other resources.
		[Route(@"{*path:regex(^.*\.cshtml$)}")]
		[ApiExplorerSettings(IgnoreApi = true)]
		public async Task<IActionResult> Get(string path)
		{
			try
			{
				object model = null;
				Response.StatusCode = 200;
				
				if (Is404Result(path))
				{
					if (IsAjaxRequest())
					{
						// ajax requets don't need branded 
						// friendly 404 page not found content.
						return NotFound();
					}
					
					Response.StatusCode = 404;
					model = new Models.ErrorNotFoundViewModel {Path = path};
					path = Path404;
				}
				
				var result = await ParseAsync(path, model);
				return Content(result, "text/html");
			}
			catch (Exception ex)
			{
				if (IsAjaxRequest())
				{
					// ajax requests don't need branded
					// friendly 500 error content.
					return new StatusCodeResult(500);
				}

				Response.StatusCode = 500;
				var model = new Models.ErrorUnhandledExceptionViewModel { Path = path };

				if (HostEnvironment.IsDevelopment())
					model.Exception = ex;
				
				var result = await ParseAsync(Path500, model);
				return Content(result, "text/html");
			}
		}

		private bool IsAjaxRequest()
		{
			if (Request.Headers != null)
				return Request.Headers["X-Requested-With"] == "XMLHttpRequest";
			else
				return false;
		}

		private bool Is404Result(string path)
		{
			// cshtml files starting with underscore should not be served.
			// we'll use this convention to prevent serving Layouts.
			if (path.StartsWith("_"))
				return true;

			// This controller only processes existing CSHTML resources inside the WWWROOT folder.
			// we want to make sure the requested resource exists on disk.
			var file = string.Format(@"{0}\{1}", this.HostEnvironment.WebRootPath, path.Replace("/", "\\"));
			return !System.IO.File.Exists(file);
		}

		private Task<string> ParseAsync(string path, object model = null)
		{
			model = model ?? new { };
			return Task.Run(() => Engine.Parse(path, model));
		}
	}
```

**Comment by toddams** [comment]
> Everything seems to work reasonably well until I try to assign a layout to one of the cshtml pages.

What happens when you try to set a layout? You are getting an exception? If yes, can you please show an exception message (If it's a TemplateCompilationException - CompilationErrors errors)

**Comment by kudoz83** [comment]
I think I've figured out the issue...

`
@inject IHostingEnvironment Environment
`
Environment is null inside the layout... even if the inject statement also exists on the page calling the layout.    I apologize for not being able to diagnose the issue more succinctly earlier, my 500 error page was swallowing additional details erroneously. 

The inject statements seem to work fine within the page calling the layout.

**Comment by toddams** [comment]
Thank you for reporting, I'll add @inject support to layouts asap
