### ISSUE TITLE
[Bug] .NET Core uses Assembly Name in place of Root Namespace for Resource Root

### ISSUE THREAD

**Issue by khionu** [toddams/RazorLight#171]
This behavior makes Embedded Resources unreachable if the Root Namespace != Assembly Name.

https://github.com/toddams/RazorLight/issues/107 is a viable fix, however, this should be resolved automatically as well.

**Comment by toddams** [comment]
So what is the point of this issue, anyway? :)

**Comment by khionu** [comment]
To point out the specific problem? As is, it only works under the assumption that the Namespace is the same as the Assembly name, which, while often true, is not always. In my context, I'm making a dotnet cli extension, which requires the assembly/output be in the format of `dotnet-[command]`, but I don't want hyphens in my namespace, to name one issue with that.

Regarding a fix, I noted 107 because it can fix it, but it should not be the sole way to fix this, as it leaves the framework-bound assumption.

**Comment by toddams** [comment]
Tracked in #107
