### ISSUE TITLE
new RawString(string.empty) crashes

### ISSUE THREAD

**Issue by ada3m0n666** [toddams/RazorLight#172]
new RawString(string.Empty) is crashing. It should not throw an argument null exception.

**Comment by csr-nick** [comment]
Seems like the check [here](https://github.com/toddams/RazorLight/blob/669cb741998b6248d7ccfa3f9da2d25acdeaa2f8/src/RazorLight/Text/RawString.cs#L27) could be ammended to check for null rather than `NullOrEmpty`.

**Comment by nloding** [comment]
I disagree, it should mimic the `Html.Raw` Razor directive, which handles empty/null content. If the value is empty or null it returns `HtmlString.Empty`. A similar approach should be taken here.

**Comment by mscrivo** [comment]
I agree with @nloding.  Coming from RazorEngine, a whole bunch of our tests around are templates are broken because we didn't specify a value for every single property.

**Comment by nloding** [comment]
@mscrivo you beat me to it - I was going to submit a PR this weekend :) Thanks for doing that, hopefully @toddams can get it pulled in!

**Comment by wakuflair** [comment]
Why is this issue closed? The latest package doesn't resolve this problem.

**Comment by pabloordonez** [comment]
Any news on this issue? Is a new version coming?

**Comment by wggley** [comment]
+1
Getting this issue also.
