### ISSUE TITLE
Rendering problems

### ISSUE THREAD

**Issue by mohsens22** [toddams/RazorLight#174]
Hello. I have this string in my model:
![image](https://user-images.githubusercontent.com/22152065/38589108-7d157498-3d3e-11e8-9125-7d52fcfd04b8.png)

But when I want to render it in the template I face this mess
![image](https://user-images.githubusercontent.com/22152065/38589137-9dd4dec6-3d3e-11e8-8281-ae01daf0b064.png)

What's wrong here?

**Comment by huanbd** [comment]
I think you should try 
`@Raw("Enter your text here")`

**Comment by mohsens22** [comment]
@Model.CSharpGoodPractice
This is what I have in the template. This is what it should be I think

**Comment by huanbd** [comment]
I mean `@Raw(Model.CSharpGoodPractice)`

**Comment by mohsens22** [comment]
![image](https://user-images.githubusercontent.com/22152065/38907203-e44517ae-42cf-11e8-83fe-657de90e3828.png)
Same as before

**Comment by toddams** [comment]
I tried @Raw() and it works for me. 
If issue is still there - please reopen and attach a sample project to reproduce
