### ISSUE TITLE
Intellisense errors

### ISSUE THREAD

**Issue by mscrivo** [toddams/RazorLight#181]
Anyone know how to solve the intellisense errors in VS?  I've got a .NET 4.7.2 class library project that uses RazorLight and the cshtml templates are giving me a bunch of intellisense errors that are rather annoying.  Here's a small Gif showing the issue I'm encountering:

![razorlight](https://user-images.githubusercontent.com/275524/39632421-0b711e62-4f83-11e8-9044-0e994f47e672.gif)

Here are the errors in the Error View:

![image](https://user-images.githubusercontent.com/275524/39632929-8092b132-4f84-11e8-8090-09a74961ea7d.png)

The template does appear to compile fine and works as desired, it's just the intellisense.

FWIW, This is on VS 2017 15.6.7 and the same templates had no Intellisense issues when I was using RazorEngine.  I'm moving away from RazorEngine out of necessity since it doesn't support net standard 2.0 and it has a reference to an old AspNetCore.Razor package which references System.Net.Http, that no longer builds with .NET 4.7.2 projects.

**Comment by toddams** [comment]
Something is with Visual studio.

**Comment by sybaris** [comment]
Hi,

I have the same problem with my VS2022 (17.6.2) on my project with Framework 4.6.2.
Notice that the same project with Framework 6.0, I do not have the problem.

Any idea to solve this (I would like to stay in 4.6.2) ?

Regards
Sybaris
