### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by ErcinDedeoglu** [toddams/RazorLight#183]
This example from wiki not up to date.
Could you advice for latest version for how can i use layouts?

var engine = EngineFactory.CreatePhysical(@"C:/path/to/views/root/folder");
var model = new MyTestViewModel()
{
    Name = "John Doe"
};

string result = engine.Parse("Test.cshtml", model);
//or
string result = engine.Parse("folder1/Test.cshtml", model)

**Comment by toddams** [comment]
The piece of code you provided shows the initialization of razorlight. 
You can find up to date info about initialization in readme

@layout stuff stays the same
