### ISSUE TITLE
Razor UI in class libraries?

### ISSUE THREAD

**Issue by mattwoberts** [toddams/RazorLight#184]
Just spotted this: https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries/

I've not fully got my head round this but does it have any implications for this project at all - it sounds like it aids in running razor OUTSIDE of asp.net MVC, so could be be an integral part of razorlight, or even replace bits of it?

**Comment by onionhammer** [comment]
Yeah razorlight itself can probably 90% be thrown out, honestly, and the rest of it rewritten.

**Comment by toddams** [comment]
The changes allows you to have razor templates in class library, but still you need ASP.NET MVC to discover them. So nothing changes, but the limitation of not having views in class libraries has been resolved.
