### ISSUE TITLE
I can't use @Html helper in my .NET 4.6 class library project

### ISSUE THREAD

**Issue by Syltty** [toddams/RazorLight#185]
Hi,

I'm using `<package id="RazorLight" version="1.1.0" targetFramework="net46" />`

It works fine until I try to add `@Html.AntiForgeryToken()` inside my form.

I get "Cannot find Html symbol" in the editor and pretty much the same error when running and parsing the page using 

```
return new HttpResponseInfo(HttpStatusCode.OK)
{
    Content = this.Razor.Parse("MyHtmlPage", model, viewBag),
    HeaderContentType = MediaTypeNames.Text.Html
};
```
I ran `install-package Microsoft.AspNet.Mvc`, tried to write `@using System.Web.Mvc`. It gets rid of the error in the editor but I still get an error running that stuff.

Should I use either one or the other? (Microsoft or Razorlight)

Any idea?

Thank you

**Comment by toddams** [comment]
Html helpers are not yet implemented
