### ISSUE TITLE
IncludeAsync

### ISSUE THREAD

**Issue by Mr-Nicolai** [toddams/RazorLight#187]
Hi there,

when i try to use IncludeAsync in my .csthml file i got the error "IncludeAsync does not exist in the current context". Do i have to add a @using directive?
![unbenannt5](https://user-images.githubusercontent.com/38925535/40470308-a4479892-5f22-11e8-8e9c-8b751b035d1b.PNG)

**Comment by toddams** [comment]
https://github.com/toddams/RazorLight#enable-intellisense-support
