### ISSUE TITLE
Incomplete compiled result when using IncludeAsync

### ISSUE THREAD

**Issue by jskuby** [toddams/RazorLight#189]
I'm running some tests with RazorLight 2.0.0-beta1 and have an issue with a test case.  I have the following 3 files:

TestEmail.cshtml
```
@{
    Layout = "Layout";
    await IncludeAsync("Partial", Model);
}
```

Layout.cshtml
```
[@RenderBody()]
```

Partial.cshtml
```
@using RazorLight
@inherits TemplatePage<Email.Tests.TestEmail>
Hello @Model.FirstName @Model.LastName!
```

When I render the output, I expect to see `[Hello FirstName LastName!]`, but instead I just get `]`.  When the content from Partial.cshtml is directly in TestEmail.cshtml, everything works as expected.  I only see this issue when introducing `IncludeAsync` into the test email.

**Comment by toddams** [comment]
There are indeed issues with rendering Includes. Issue is tracked in #134

**Comment by jskuby** [comment]
I thought that might be the case, but wasn't sure.  Thanks for checking on this @toddams.
