### ISSUE TITLE
Allow unrendered sections? + Provide better error message in TemplatePage.cs

### ISSUE THREAD

**Issue by thundercraker** [toddams/RazorLight#192]
I am mainly concerned with the message in  TemplatePage.cs that is thrown on line 259 when a section is defined in a page but is subsequently unrendered in the layout/parent etc

> Also: Is it really nessessary to do this check? .NET MVC will not complain if you define a section and dont use it in the Layout. You can definitely put in sections into conditional rendering blocks, which this check disallows.

--------------------------------------------------------

Its seems that the proper message for the exception was forgotten.

`var sectionNames = string.Join(", ", sectionsNotIgnored);
throw new InvalidOperationException();`

**Comment by thundercraker** [comment]
Opened a PR for it [#193](https://github.com/toddams/RazorLight/pull/193)

**Comment by toddams** [comment]
Thank you!
Merged :)
