### ISSUE TITLE
@page makes the compiler fail

### ISSUE THREAD

**Issue by petterek** [toddams/RazorLight#195]
Running .net core 2.1 and adding the @page instruction to the top of the page makes the compiler fail. 

The name 'page' does not exist in the current context

When I do not have @page directive, the model inside the template is not recognized, but works fine when rendering.
 
Appart from that, works very nice. 

I use cshtml file, that is set to "embeded resource"
```
   engine = new RazorLightEngineBuilder()
              .UseEmbeddedResourcesProject(typeof(ListSupportedInterfaces))
              .UseMemoryCachingProvider()
              .Build();
   input = engine.CompileTemplateAsync("Templates.CreateInput").Result; <-- fails here 
```

```
@page <-- Compilation fails. 
@using ServiceHost.NetCore.Templates

@model CreateInputModel

<html>
<head>
</head>

<body>
    <h3>@Model.ParamType.FullName</h3>

    <code>
        {
        @foreach (var m in Model.Fields)
        {
            @($"{m.Name} : {m.Type.Name}")
        }

        }
    </code>
    <hr />
    <code cols="60" rows="30">
        @Model.ParamInstanceSerialized
    </code>
</body>
</html>
```

**Comment by petterek** [comment]
and I'm running the 2.0 beta1 version

**Comment by toddams** [comment]
@page is a RazorPages feature of ASP.NET MVC, and not a part of RazorLight

**Comment by petterek** [comment]
Any other directive that can be put in the top of the page to recognize the model?

**Comment by toddams** [comment]
@model ?

**Comment by bluebaroncanada** [comment]
I'm having the same problem with `@model`.  The name 'model' does not exist in the current context
