### ISSUE TITLE
New NuGet package

### ISSUE THREAD

**Issue by Rizzen** [toddams/RazorLight#199]
There is a nice fix commit - https://github.com/toddams/RazorLight/commit/915ec6dc8d83865d2af074efd64dce3d53897c69 so when will it come to NuGet package?

**Comment by dominikfoldi** [comment]
Bump on this!

**Comment by AndyCJ** [comment]
Here's another [critical bug](https://github.com/toddams/RazorLight/pull/159) fix awaiting publish.

**Comment by tjrobinson** [comment]
@toddams Just wondering why this is closed? `2.0.0-beta1` came out prior to the fixes mentioned above. Happy to help if I can?

**Comment by rossdargan** [comment]
I could really do with this fix too.
