### ISSUE TITLE
RazorLight.MVC not compatible with .NetFramework 4.6.2

### ISSUE THREAD

**Issue by acopapic** [toddams/RazorLight#20]
It seems that RazorLight.MVC 1.0.1 is not compatible with .NetFramework 4.6.2. I'm getting 'Package RazorLight.MVC 1.0.1 is not compatible with net462 (.NETFramework,Version=v4.6.2).'

**Comment by toddams** [comment]
That's true I totallt forgot about MVC package, will roll update aoon

**Comment by toddams** [comment]
Fixed in [RazorLight.MVC 1.0.2](https://www.nuget.org/packages/RazorLight.MVC/1.0.2)
