### ISSUE TITLE
Properties set in templates don't set

### ISSUE THREAD

**Issue by recklessforce** [toddams/RazorLight#204]
**Describe the bug**

`CompileTemplateAsync` ignores properties that are set.

**To Reproduce**

```csharp
var razorLightEngine = new RazorLightEngineBuilder()
                .UseFilesystemProject(Directory.GetCurrentDirectory())
                .Build();

var template = await razorLightEngine.CompileTemplateAsync("Test.cshtml");
Console.WriteLine(template.DisableEncoding); // --> false
```

**Test.cshtml:**

```csharp
@inherits RazorLight.TemplatePage<object>
@{
    DisableEncoding = true;
}
test123
```

**Expected behavior**

`Console.WriteLine(template.DisableEncoding); ` should output `true`.

**Information:**
 - OS: Windows 10.0.17134.137
 - Platform: .NET Core 2.1
 - RazorLight version 2.0-beta1

**Comment by toddams** [comment]
Issue is not following the issue template

**Comment by recklessforce** [comment]
@toddams I've updated it. Could you please re-open?
