### ISSUE TITLE
[Question] Does RazorLight work with .NET Core Globalization/Localization?

### ISSUE THREAD

**Issue by MarcoNicolodi** [toddams/RazorLight#205]
Hello.

Ive implemented the email feature in my application using RazorLight in a netcoreapp2.1 library project. The library is used by multiple ASP.NET Core 2.1 different APIs. It worked pretty well. 

Now im gonna have to translate the templates. The documentation of ASP.NET Core Globalization/Internationalization is very complete, but also kind of complex, [as you can see here](https://docs.microsoft.com/pt-br/aspnet/core/fundamentals/localization?view=aspnetcore-2.1).

Before investing the time for implementing this feature in my project, i would like to know if the RazorLightEngine support the default ASP.NET Core Globalization features, such as `@inject IViewLocalizer Localizer`, `Localizer["String to translate"]`, etc.

Thank you.

**Comment by myrddraall** [comment]
Related to #166 
Its supposed to but it currently isn't working

**Comment by toddams** [comment]
Tracking this issue in #166
