### ISSUE TITLE
Register Template and then Partial(Body)

### ISSUE THREAD

**Issue by joetherod** [toddams/RazorLight#212]
In the >Net Framework version, you were able to register the template and then Execute the content on that template. There was a hit on registering templates, so I did it once and then did the Execute for different model objects. What is the similar way to do it in the Core version? Register the layout template once, then execute different body content with different model values?

**Comment by toddams** [comment]
> Net Framework version

What version are you reffering to?

**Comment by joetherod** [comment]
I am using Core 2.1. I was able to use the memory cache option so I dont have to compile the same template over and over again. Thanks.
