### ISSUE TITLE
Unclear (incorrect) error message

### ISSUE THREAD

**Issue by ReinisV** [toddams/RazorLight#215]
**Describe the bug**
[This](https://github.com/toddams/RazorLight/blob/744f545227083f17c63bcdef989bd5c2017ef53b/src/RazorLight/Generation/RazorSourceGenerator.cs#L50) error message contains a formatting marker ('{0}'), but the message is never formatted (the key is never inserted)

**To Reproduce**
Cause the error to be thrown

**Expected behavior**
The key should be inserted in the error message (the message should be formatted)

**Information (please complete the following information):**
 - OS: [ e.g Ubuntu 16.04, Windows Server 2016, etc ]
 - Platform [.NET Framework 4.x / .NET Core 2.x , etc]
 - RazorLight version [ e.g 2.0-beta1 ]

**Additional context**

**Comment by toddams** [comment]
Great issue for the first Pull Request :)
