### ISSUE TITLE
Release timeline?

### ISSUE THREAD

**Issue by WaltDaniels** [toddams/RazorLight#218]
Are there any plans to move this from Beta to Released?  I would like to use this on a project, but we aren't permitted to use anything marked "Beta" in our production environment.

**Comment by kishorehere82** [comment]
We want to use this as well (but not allowed in beta) - Can you please let us know the plans for beta to release for 2.0.0

**Comment by toddams** [comment]
End of October

**Comment by molinch** [comment]
Thanks a lot for your amazing library, and I hope it's soon :-)

**Comment by WaltDaniels** [comment]
Hey toddams, any update on a non-beta release date?
Thanks!
