### ISSUE TITLE
StackOverflowException in RazorLightEngine.cs

### ISSUE THREAD

**Issue by charleslp84** [toddams/RazorLight#219]
In the file RazorLightEngine.cs in the line 100 there is the recursive call to the same method.

return RenderTemplateAsync(templatePage, model, viewBag);

It's generating the StackOverflowException. I asume the correct call is 

return **_handler.**RenderTemplateAsync(templatePage, model, viewBag);

**Comment by toddams** [comment]
This is fixed now in https://github.com/toddams/RazorLight/pull/242

**Comment by toddams** [comment]
By the way, if you notice something as small as this issue - feel free to send a Pull Request, I would greatly appreciate your help :)
