### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.1.2.0' on .net 4.7.2

### ISSUE THREAD

**Issue by luisluix** [toddams/RazorLight#220]
When running razorlight on .net 4.7.2 it says that it cant load a file or assembly

**To Reproduce**
create a new mvc 4.7.2 project in visual studio, add razorlight nuget package 2.0 beta1, try running the sample code it will break on this line:

  var engine = new RazorLightEngineBuilder()
              .UseMemoryCachingProvider()
              .Build();

 - windows 10
 - .net 4.7.2
 - RazorLight version 2.0-beta1 

the code works fine on core, but on .net 4.7.2 it seems to be missing a reference or something. Im creating a .net standard library, and it works fine on core, but .net 4.7.2 keeps crashing with missing files/assemblies.

removing the dependent assembly in the web config causes a new exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: operatingAssembly

**Comment by toddams** [comment]
Fixed and planned for the next release

**Comment by Almeonamy** [comment]
Is there any temporary solution?
