### ISSUE TITLE
Localization Globalization

### ISSUE THREAD

**Issue by harryC72** [toddams/RazorLight#224]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

**Comment by harryC72** [comment]
I am building an asp .net core 2.0 application with a lot of localization throughout the site (it supports 3 languages currently). I wonder if there are some tips on how to make the globalization/localization work with Razorlight. I have several e-mail templates which get htmlized by Razorlight.

**Comment by MarcoNicolodi** [comment]
Theres a issue with internacionalization tracked by #166
