### ISSUE TITLE
Can't clear the cache

### ISSUE THREAD

**Issue by shobman** [toddams/RazorLight#225]
**Describe the bug**
Using the in memory cache, I can't compile new template that have already been compiled before, it just serves me the cached rendering.

**To Reproduce**

```
var engine= new RazorLightEngineBuilder()
              .UseMemoryCachingProvider()
              .Build();

var key = "my-key";

var content = await engine.CompileRenderAsync(key, "<p>Template 1</p>", new {});
// content = "<p>Template 1</p>"

// whether or not the item is removed from cache before compiling again, makes no difference to the outcome
if (engine.TemplateCache.Contains(key))
    engine.TemplateCache.Remove(key);

content = await engine.CompileRenderAsync(key, "<p>Template 2</p>", new {});
// content = "<p>Template 1</p>" !!!!!!!!
```

**Expected behavior**
I would expect that if I compile a template that's already compiled, than it should overwrite the existing template in cache. And if i explicitly remove the template from cache, then I'd expect that the new compilation would seed the cache.

**Actual behavior**
After compiling a new template with the same key, the result reflects the initial compiled template, and not the updated one.  This is observed whether or not the item is first manually removed from cache.

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Core 2.1.402 
 - RazorLight version 2.0.0-beta1

**Additional context**
I understand I should use CompileTemplate when I have a new template, and use RenderTemplate when I want to retrieve from cache. My templates are stored in storage and get updated via another system.  I need to check for updates to the underlying template before deciding whether to compile or render.

**Comment by blendsdk** [comment]
I have the same problem.

**Comment by toddams** [comment]
Tracked in #177

**Comment by jjxtra** [comment]
Setting ExpirationToken of the project item should do it
