### ISSUE TITLE
why there is Control character appended ?

### ISSUE THREAD

**Issue by mittu28** [toddams/RazorLight#226]
I see control character in result using  CompileRenderAsync method.
I have xml in template.
Here is caller code 

```c#
private async Task<string> ProcessRazorAsync(WebhookRequest value)
        {
            _logger.Info("---------- Event data ---------------");
            _logger.Info(value.EventData.UserVariables.GetValueOrDefault("WFInstanceID",""));
            return await _engine.CompileRenderAsync(_templateName, value.EventData);
         }
```
Here is my template.
```xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body>
    <Params>
      <a:WFInstanceID>​@Model.UserVariables.GetValueOrDefault("WFInstanceID","")​</a:WFInstanceID>  
    </Params>
  </s:Body>
</s:Envelope>
```

See red hyphen in attached image . since you cannot see control character in notepad.
![image](https://user-images.githubusercontent.com/43819099/46418371-a6a83d00-c6f9-11e8-8273-cca67011dd35.png)

**Comment by jzabroski** [comment]
@mittu28  Any chance you can write an XUnit.net test and reproduce the issue for me?  There's a lot going on here, like ASP.NET Webhook Receivers.  How do you know it's not Webhook Receivers that is formatting the GUID in the WFInstanceID property?
