### ISSUE TITLE
The document type '' does not support the extension 'ITemplateTargetExtension'.

### ISSUE THREAD

**Issue by TooManyLeaves** [toddams/RazorLight#236]
**Describe the bug**
Attempting to use Templated Razor Delegates produces the following error message:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Failed to generate Razor template. See "Diagnostics" property for more details
- The document type '' does not support the extension 'ITemplateTargetExtension'.
```

**To Reproduce**

```c#
@{
  Func<dynamic, object> b = @<strong>@item</strong>;
}
<span>This sentence is @b("In Bold").</span>
```

**Expected behavior**
Not crashing.

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Core 2.1
 - RazorLight version 2.0-beta1

**Comment by lars-nielsen** [comment]
@toddams 
If I fix this, would you be willing to merge and push a new nuget package?

**Comment by toddams** [comment]
Sure I'll find time for that :)

**Comment by lars-nielsen** [comment]
Great I'll create the pull request tomorrow, thanks in advance

ons. 31. jul. 2019 18.44 skrev Ivan Balan <notifications@github.com>:
