### ISSUE TITLE
  How to create external dynamic html tags

### ISSUE THREAD

**Issue by markleacompassphs** [toddams/RazorLight#245]
**Describe the bug**
Cannot find the correct syntax to allow for dynamic external link rendering.

**To Reproduce**

**Expected behavior**
This for example does not work - 
 <td style="background-color:#DCE1E3;text-align: center; border-right:2px solid #4b6e84; border-bottom: 2px solid #4b6e84;"><a href=@Model.Url target="blank">Go To Site</a></td>

**Information (please complete the following information):**
  OS: Windows 10 
 - Platform [.NET Framework 4.x / .NET Core 2.x 
 - RazorLight version [ e.g 2.0-beta1 ]
 - Visual Studio 2017

**Additional context**
Please provide some working examples on how we are supposed to do this, without being able to create dynamic external links we cannot move forward with using this product.  Thanks.

**Comment by boeserwolf91** [comment]
In case you write html templates (which is not clear to me), what about:

```<a href="@Model.Url">Go To Site</a>```

**Comment by markleacompassphs** [comment]
Yes that did work, however when I attempt to loop over the href tag it does not.  My other parts of the template that are just td tags do not have this issue when looping over the Model object.  

For dynamic href links we now know that this works, but we have to hard code the index.  

   <tr>
      <td style="background-color: #2E5674;text-align: right;padding-right: 10px; color:#dae4eb; border-right:2px solid #4b6e84; border-bottom: 2px solid #4b6e84; font-size: 9pt;">Reviews</td>
      <td style="background-color:#DCE1E3;text-align: center; border-right:2px solid #4b6e84; border-bottom: 2px solid #4b6e84;"><a href="@Model.Providers[0].Reviews[0].Link" target="blank">HealthGrades</a></td>
      <td style="background-color:#DCE1E3;text-align: center; border-right:2px solid #4b6e84; border-bottom: 2px solid #4b6e84;"><a href="@Model.Providers[1].Reviews[0].Link" target="blank">HealthGrades</a></td>
      <td style="background-color:#DCE1E3;text-align: center; border-right:2px solid #4b6e84; border-bottom: 2px solid #4b6e84;"><a href="@Model.Providers[2].Reviews[0].Link" target="blank">HealthGrades</a></td>
   </tr>

 
 But for some ridiculous reason this does not work, and I do not get any error message, the table just does not render at all. 
 
  <tr>
     <td style="background-color: #2E5674;text-align: right;padding-right: 10px; color:#dae4eb; border-right:2px solid #4b6e84; border-bottom: 2px solid #4b6e84; font-size: 9pt;">Reviews</td>
     @for (int i = 0; i < @Model.Providers.Count; i++)
      {
        <td style="background-color:#DCE1E3;text-align: center; border-right:2px solid #4b6e84; border-bottom: 2px solid #4b6e84;"><a href="@Model.Providers[i].Reviews[0].Link" target="blank">HealthGrades</a></td>
      }
  </tr>

**Comment by crowz4k** [comment]
try to do it like this @(Model.Providers[i].Reviews[0].Link)
