### ISSUE TITLE
Example on main page does not work

### ISSUE THREAD

**Issue by RedX2501** [toddams/RazorLight#249]
**Describe the bug**
The example on the main page does not work.

With that the exception:
```
System.ArgumentNullException : Der Wert darf nicht NULL sein.
Parametername: razorLightProject
```
is thrown

**To Reproduce**
Create any project with *master* or *2.0.0-beta.1*

**Expected behavior**
The example should create a rendered template.

**Information (please complete the following information):**
 - OS: Irrelevant (but win10)
 - Platform Irrelevant (but .NET Framework 4.6.1)
 - RazorLight version: master and  e.g 2.0.0-beta1
 - Visual Studio version: 15.6.2

The documentation of what exactly is a **Project** is missing...

**Comment by MNF** [comment]
Are you talking about https://github.com/toddams/RazorLight/blob/master/README.md?
It has a few examples.
Could you specify which snippet  cause a problem and which line?
Which method requires the parameter razorLightProject?

**Comment by RedX2501** [comment]
I believe i tried them all. 

At the end i believe it is caused by mit3 using a cachingprovider.

The examples are missing one.

**Comment by andrewduffy77** [comment]
Not working for me either... the most basic quickstart example. I'm using as part of an Azure function.

@RedX2501 what does mit3 stand for?

**Comment by RedX2501** [comment]
@andrewduffy77 I can't seem to figure it out anymore. It is for sure a typo.

**Comment by michael-freidgeim-webjet** [comment]
I've added an example with embedded resource that works for me into wiki https://github.com/toddams/RazorLight/wiki/Examples-of-Generating-from-templates

**Comment by jzabroski** [comment]
Fixed in beta3
