### ISSUE TITLE
Ability to cancel template generation

### ISSUE THREAD

**Issue by shai-glat** [toddams/RazorLight#253]
**Is your feature request related to a problem? Please describe.**
I use Razorlight in an ASP.Net Core application. As requests can be cancelled, i'd like to be able to cancel Razorlight mid-render if needed.

**Describe the solution you'd like**
Simply add a CancellationToken optional parameter to RazorLightEngine methods such as CompileRenderAsync() and check it during execution.

**Comment by jzabroski** [comment]
Do you think all public async methods should allow cancellation, or just rendering?  My point being, for nested templates, it is not clear to me what the behavior would be if you cancel the template.  What kind of code would you write where an inner template cancels and the outer succeeds?

**Comment by toddams** [comment]
Most of the time is taken by Reflection.Emit, which is compiles your template, and I don't think it has async option, thus a support of the CancellationToken

**Comment by jzabroski** [comment]
I think he was thinking of the inner template content such as IncludeAsync. But will wait to see his reply.
