### ISSUE TITLE
PreserveCompilationContext Error

### ISSUE THREAD

**Issue by mkeuschn** [toddams/RazorLight#254]
I have tried to build a class library with templates and used it then in a unit test but i getting this error:

`Can't load metadata reference from the entry assembly. Make sure PreserveCompilationContext is set to true in *.csproj file`

I have created a solution with this behaviour:
https://github.com/mkeuschn/RenderingService.git

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .NET Standard
 - RazorLight version 2.0-beta1
 - Visual Studio 15.7.5

** Solutions from other tickets I have tried **

I have added Mvc as mentioned in this ticket
https://github.com/toddams/RazorLight/issues/182

I have configured PreserveCompilationContext in its own Group and rebuilded the solution as mentioned here 
https://github.com/toddams/RazorLight/issues/127

**Comment by AnCampbell-AU** [comment]
Hi @mkeuschn, have you tried adding ` <PreserveCompilationContext>true</PreserveCompilationContext>` to your test project's csproj at this line?https://github.com/mkeuschn/RenderingService/blob/7ca633303bc06404e0a5c6f18f1dae83729a52b1/test/RenderingService.Test.csproj#L5

**Comment by mkeuschn** [comment]
Hi @AnCampbell-AU,

with the preserve compilation flag in the test project it works. Do I have to add this flag to each project where I use my own dll?

Regards

**Comment by campbellja** [comment]
@mkeuschn Yes that's correct

**Comment by AnCampbell-AU** [comment]
Hi @mkeuschn Yes that's right.
