### ISSUE TITLE
readme refers to  .UseDefaultCachingProvider(), that doesn't exist

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [toddams/RazorLight#255]
https://github.com/toddams/RazorLight/blob/744f545227083f17c63bcdef989bd5c2017ef53b/README.md has reference
var engine = new RazorLightEngineBuilder()
                .UseEmbeddedResourcesProject(typeof(Program))
                **.UseDefaultCachingProvider()**
                .Build();
but the method UseDefaultCachingProvider not found in the repository

**Comment by Bogatinovski** [comment]
I am also curious why that method UseDefaultCachingProvider() doesn't exist even though it is written in the documentation in the readme.md file. Why is this ? Is there caching out of the box or is there some way to enable the caching ?

**Comment by Bogatinovski** [comment]
I was also curious myself why is this. Upon inspection I found that `UseDefaultCachingProvider `indeed is missing from the `RazorLightEngineBuilder `object but there is another method called `UseMemoryCachingProvider`. That serves the purpose of "default caching provider".
Further more there is another method called `UseCachingProvider` and my guess is we can use that one to pass our own custom implementation of a cache provider, perhaps by inheriting the `ICachingProvider` interface.
