### ISSUE TITLE
RazorLight.Sandbox.csproj refers to non-existing files

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [toddams/RazorLight#256]
RazorLight.Sandbox.csproj has references to embedded resources:
    <EmbeddedResource Include="Views\Subfolder\A.cshtml" />
    <EmbeddedResource Include="Views\Subfolder\B.cshtml" />
    <EmbeddedResource Include="Views\Subfolder\C.cshtml" />
but https://github.com/toddams/RazorLight/tree/master/sandbox/RazorLight.Sandbox
doesn't have such files

**Comment by jzabroski** [comment]
I think this is because it's a Sandbox built by Ivan for testing out some things. It's not actually meant to be buildable by others.  It's literally a playground for experimenting with features.

**Comment by MNF** [comment]
It’s good to have sandbox, because others also may want to experiment, and it could be a good start point. I just suggested that the project should be completed. 

Thanks for taking care about this library.

**Comment by jzabroski** [comment]
Should be fixed now.  Please check.

![image](https://user-images.githubusercontent.com/447485/71094279-b71acb00-2178-11ea-97d0-710d74c193f9.png)
