### ISSUE TITLE
How can I use LINQ?

### ISSUE THREAD

**Issue by pbrianmackey** [toddams/RazorLight#257]
I have:

```
        [HttpPost("templatingpocsimple")]
        public async Task<JsonResult> TemplatingPocSimple()
        {
            string result;
            var engine = new RazorLightEngineBuilder()
              .UseMemoryCachingProvider()
              .Build();

            string template = "@using System.Linq \n @using System.Xml.Linq \n"
                              + "<p> @Model.SomeList.Where(x => x > 1) </p>";

            var model = new Person()
            {
                SomeList = Enumerable.Range(0, 25)
            };

            result = await engine.CompileRenderAsync("templateKeyMadeup", template, model);

            return Json(result);
        }
```

ERROR

> {"message":"Failed to compile generated Razor template:- (2:27) Cannot use a lambda expression as an argument to a dynamically dispatched operation without first casting it to a delegate or expression tree type.See CompilationErrors for detailed information"}

**Comment by martonx** [comment]
Actually I have issue with use .Any()

string template = "@using System.Linq \n"
                              + "<p> @if (myStringList.Any()) ... </p>";

"'System.Collections.Generic.List<string>' does not contain a definition for 'Any'"

**Comment by Wingjam** [comment]
To use Linq, you need to either cast or save your list to a statically typed variable.

In your case:
```c#
var template = @"
@using System.Linq;
@{
    List<SomeListType> someList = @Model.SomeList;
}
<p>@someList.Where(x => x > 1)</p>
";
```

**Comment by jzabroski** [comment]
Also, Razor Templates don't support open generic templates.  Your Model object has to be a closed data type.

If you feel you really need the ability to have open generic templates, you probably want to use a different library or different programming language entirely.  F# and WebSharper I believe support such use cases.
