### ISSUE TITLE
Leftover Artifacts

### ISSUE THREAD

**Issue by sbosell** [toddams/RazorLight#26]
We have been using RazorEngine in a few projects and it seems to create a bunch of compiled artifacts on the file system that require cleanup.  Out of curiosity, does RazorLight leave anything in the filesystem that requires cleanup?

**Comment by sbosell** [comment]
The artifacts that are left was referring to a competing library (RazorEngine).  https://github.com/Antaris/RazorEngine/issues/244  I was asking if your library leaves anything in the filesystem.

**Comment by toddams** [comment]
Oh, sorry, totally misread the question.
Nope, RazorlLight does not create temp files that must be cleaned. Or at least nobody noticed it so far :)
