### ISSUE TITLE
Failed to compile generated Razor template. The name 'Render' does not exist in the current context

### ISSUE THREAD

**Issue by gmarokov** [toddams/RazorLight#262]
**Description**
Hi. I try to use view with layout but I get the following error: 
`Failed to compile generated Razor template:
      - (73:17) The name 'Render' does not exist in the current context`

**To Reproduce**
1. My RazorLight setup: 

```
private static string TEMPLATES_PATH = $@"{Directory.GetCurrentDirectory()}/Templates/Email";
public static async Task<string> RunCompile(string templateName, object model)
{
      var engine = new RazorLightEngineBuilder()
          .UseFilesystemProject(TEMPLATES_PATH)
          .UseMemoryCachingProvider()
          .Build();
       string result = await engine.CompileRenderAsync(templateName, model);           
       return result;
 }

```
2. The rest is like the Wiki page for Layout pages: I did step 1 the model creation and step 2 layout/children page. Haven't performed the last step as it seems deprecated.

**Information:**
 - OS: Fedora 30
 - Platform .NET Core 2.1
 - RazorLight version 2.0.0-beta1

The Wiki page probably needs update too, as when tried the code there, It was marked as obsolete.

**Comment by jzabroski** [comment]
@gmarokov Thanks, but without knowing the model or the template content, it is hard to debug why you ran into this issue.  Can you please either attach a zip file with the repro or push a regression test to the repository as a PR.

**Comment by gmarokov** [comment]
@jzabroski I no longer able to reproduce it and unfortunately can't remember how it was fixed. 
Rethinking to switch to the MVC version anyway. Thank you, I will close it.

**Comment by jzabroski** [comment]
What MVC version are you referring to? Thanks

**Comment by gmarokov** [comment]
To inject the engine instead of creating it :) Regards

**Comment by jzabroski** [comment]
Cool. Happy if i helped. One thing is that I an deprecated RazorLight.Mvc
in 2.0.0 and moved AddRazorLight into the main package.
