### ISSUE TITLE
.NET Core 3 support

### ISSUE THREAD

**Issue by jsheetzati** [toddams/RazorLight#267]
**Is your feature request related to a problem? Please describe.**
Add full ASP.NET Core 3 support.

**Describe the solution you'd like**
Most of the used Microsoft.AspNetCore.* nuget packages are encompassed into the FrameworkReference and no longer available as Nuget packages. https://github.com/aspnet/AspNetCore/issues/3756. The project also needs to target netcoreapp3.0 in order to use the FrameworkReference.

**Comment by jsheetzati** [comment]
I should be able to open a PR once .NET Core 3 comes out of preview. Updated the project to support netstandard2.0 as well as netcoreapp3.0

**Comment by zhangsquall** [comment]
Had the same issue for antiforgery after upgrading to asp.net 3.0 rc.  Can anyone help?
Thanks.

**Comment by springy76** [comment]
@zhangsquall for me adding `<PreserveCompilationReferences>true</PreserveCompilationReferences>` to the project file solved the problem. Please don't ask me which side-effects this may introduce.

**Comment by zhangsquall** [comment]
> @zhangsquall for me adding `<PreserveCompilationReferences>true</PreserveCompilationReferences>` to the project file solved the problem. Please don't ask me which side-effects this may introduce.

It worked!

**Comment by joetherod** [comment]
Eta for new release that works with ,NET Core 3.0? Namespace missing in 3.0:
Microsoft.AspNetCore.Mvc.Razor.Extensions.NamespaceDirective

**Comment by joetherod** [comment]
> I should be able to open a PR once .NET Core 3 comes out of preview. Updated the project to support netstandard2.0 as well as netcoreapp3.0

@jsheetzati 3.0 is RTM. Eta for PR approval?

**Comment by jsheetzati** [comment]
Changes are in this branch with latest upgrades .NET Core 3 packages. I have not had an opportunity to verify the RTM packages yet.

https://github.com/altriadeveloper/RazorLight/tree/spike-netcore3squashed

**Comment by joetherod** [comment]
I pulled master and got it to compile with 3.0, but a lot of tests failed. I didnt try this PR.
I went with https://github.com/aspnet/Entropy/blob/master/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs

I extended it to support what I needed. Cleaner and works with Core 3.0.

**Comment by kYann** [comment]
I've created a RazorLight version for .NetCore 3.0 https://www.nuget.org/packages/RazorLight.NetCore3/ from https://github.com/whyseco/RazorLight

**Comment by toddams** [comment]
I'd appreciate if someone sends a PR for 3.0, don't have time at all for this project for now

**Comment by alextof** [comment]
Someone is able to make RazorViewToStringRenderer.cs work with .NET Core 3.0 getting the views from a Razor UI Class Library? Was working on 2.0, 2.1 and 2.2, now not anymore, IRazorViewEngine does not find the view.

**Comment by jonny64bit** [comment]
Just to confirm i've been using `<PreserveCompilationReferences>true</PreserveCompilationReferences>` 
for a while pre .net core 3 being released and never expiranced any issues with it.

**Comment by maxence51** [comment]
I also have this missing namespace `Microsoft.AspNetCore.Mvc.Razor.Extensions.NamespaceDirective`
even with `<PreserveCompilationReferences>true</PreserveCompilationReferences>`

**Comment by maxence51** [comment]
I finally used @whyseco version.  https://www.nuget.org/packages/RazorLight.NetCore3/

**Comment by HamiltonManalo** [comment]
@maxence51 giving this a test run. Thank you for sharing

**Comment by maxence51** [comment]
Thanks @jsheetzati, I think this project deserves to be maintained.

**Comment by jzabroski** [comment]
Yeah, my vision is that RazorLight will support FluentMigrator 4.0.0 release as well as possibly help Dave Gleick's [Wyam](https://github.com/Wyamio/Wyam) and [Statiq](https://github.com/statiqdev/Statiq.Framework) projects to replace the antiquated DocFX maintained by Microsoft, in addition to the core use case of @bjcull Ben Cull's FluentEmail project.

**Comment by HamiltonManalo** [comment]
@jzabroski 
I'd be happy to offer any assistance I could in maintaining the project.

**Comment by bjcull** [comment]
Ah some movement, I'll try to keep an eye on things and update FluentEmail as we go. Thanks for taking on the work!

**Comment by jzabroski** [comment]
🐢

**Comment by jzabroski** [comment]
Upgraded in my local.  Not yet tested, but it compiles.  Huzzah!

#### Failing Tests (8 of 135)
Checkbox checked indicates resolved on my machine.
- [ ] PropertyInjectorTest `Ensure_Registered_Properties_Are_Injected` fails with
    > `System.ArgumentException` : An item with the same key has already been added. Key: namespace
- [ ] RaceConditionTests `Multiple_Simuntaneous_Compilations_RaceCondition_Test` fails with
    > `System.ArgumentException` : An item with the same key has already been added. Key: namespace
- [ ] RazorLightEngineTest `Ensure_Option_DisablEncoding_Renders_Models_Raw` fails with
    > `System.ArgumentException` : An item with the same key has already been added. Key: namespace
- [ ] ...

#### My notes:
- Main issue appears to be the InstrumentationPass helper is now gone.



#### My questions:
- I didn't try to get this to work side-by-side between 2.x and 3.y. e.g. I think RazorLight for ASP.NET Core 3.z should ship as RazorLight 3.y
- For all intents and purposes, I think most people don't expect a ton of active development in 2.x packages and expect this project to be maintained in GitFlow-style.   However, the next week or so is time for people to **Speak Now Or Forever Hold Your Peace**.
- I'm confused by https://github.com/toddams/RazorLight/issues/273 which says NamespaceDirective is removed, but the code compiles fine after I upgraded.  Is

**Comment by HamiltonManalo** [comment]
I would be okay with a package being versioned for 2x and 3.y as I don't expect to revert back to 2.0 anytime though.

**Comment by gjunge** [comment]
@jzabroski this issue can now be closed.

**Comment by jzabroski** [comment]
@gjunge  Thanks for all your help!  Let me know if you encounter and issues.  At some point we should probably drop the beta tag.

**Comment by gjunge** [comment]
> @gjunge Thanks for all your help! Let me know if you encounter and issues. At some point we should probably drop the beta tag.

Happy to help. The truth to be told is that I currently not use the project and haven’t used it yet. We’re moving our projects from full framework to .NET Core, and in one of those projects we use some other Razor library which is not .NET Standard compatible, and that is why I came here and wanted to help with that .NET Core 3 support.

**Comment by gjunge** [comment]
And regarding the beta tag, I somewhere read a reason for it, but can’t remember where/why. 
And yes it is time to drop it soon.  

However I also thought of nice Microsoft DI support, would that be something that fits in the vision of the project?

**Comment by DanielToft** [comment]
Is this released? On version 2.0.0-beta2, i'm still getting "Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll'" when using  "UseFileSystemProject". When i use "UseEmbeddedResourcesProject" it cannot find my templates.

**Comment by jzabroski** [comment]
@DanielToft Please open a new issue and file a bug report.  Yes, .NET Core 3 support is released - you can see that from nuget.org dependencies accordian.

**Comment by billbrinck** [comment]
> Is this released? On version 2.0.0-beta2, i'm still getting "Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll'" when using "UseFileSystemProject". When i use "UseEmbeddedResourcesProject" it cannot find my templates.

Same for me. It can't find my templates. Did you resolve this somehow?

**Comment by jzabroski** [comment]
@billbrinck Please open a new issue and file a bug report with repro steps.  Alternatively, look at the example in the source and look at what could be different between your project and this one.

**Comment by jzabroski** [comment]
I see that you did create a discussion here: #452
