### ISSUE TITLE
How do we specifiy "preserveCompilationContext": true in the new CSproj tooling?

### ISSUE THREAD

**Issue by danwalmsley** [toddams/RazorLight#27]
In .net core rc4 I am unable to enable this option.

**Comment by danwalmsley** [comment]
Ok I found out how to do it:

Please update documentation with the following information:
1) This is to be set on the main executable project.
2) can be added like this
```
    <OutputType>exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <OutputTypeEx>exe</OutputTypeEx>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <PreserveCompilationContext>true</PreserveCompilationContext>
```
3) Visual studio 2017 seems to require a restart and a clean build before picking up the new setting.

**Comment by danwalmsley** [comment]
Great work by the way.

**Comment by toddams** [comment]
Oh, that's nice from you, thank you!)
I will update the docs
