### ISSUE TITLE
Error due to NamespaceDirective use on .NET Core 3.0

### ISSUE THREAD

**Issue by Hubert-Rybak** [toddams/RazorLight#273]
**Describe the bug**
Got error on .NET Core 3.0:

Could not load type 'Microsoft.AspNetCore.Mvc.Razor.Extensions.NamespaceDirective' from assembly 'Microsoft.AspNetCore.Mvc.Razor.Extensions, Version=3.0.0.0,

**To Reproduce**
Try using RazorLight on .NET Core 3.0 project

**Information (please complete the following information):**
 - OS: Windows
 - Platform .NET Core 3.0 ()
 - RazorLight version 2.0-beta1

It looks like NameSpace directive has been removed in 3.x (https://github.com/aspnet/AspNetCore/issues/7146) but RazorLight uses it here:

https://github.com/toddams/RazorLight/blob/ff6f6f7e32e30f9b0af0475a66d28db4da6eb7ae/src/RazorLight/DefaultRazorEngine.cs#L20

**Comment by joetherod** [comment]
Is this project active? The beta version has been in beta for a long time.
Need this addressed to continue with our upgrade to .NET Core 3.0
eta?

**Comment by kYann** [comment]
I've created a RazorLight version for .NetCore 3.0 https://www.nuget.org/packages/RazorLight.NetCore3/ from https://github.com/whyseco/RazorLight

**Comment by matthewblott** [comment]
Just come across this issue on macOS.

**Comment by jzabroski** [comment]
@Hubert-Rybak Are you sure NamespaceDirective is removed?  https://github.com/aspnet/AspNetCore-Tooling/pull/299 says otherwise.

**Comment by Hubert-Rybak** [comment]
You're right, it looks like they didn't remove it. I will close it in favor of https://github.com/toddams/RazorLight/issues/267

**Comment by jzabroski** [comment]
Thanks for your expedient reply
