### ISSUE TITLE
How can I escape out of parsing

### ISSUE THREAD

**Issue by danwalmsley** [toddams/RazorLight#28]
I am trying to do this:

#include "@{Model.ClassName}.h"

to produce
#include "classname.h"

but I get string does not contain a definition for h!

How do I escape out of parsing before the .

**Comment by toddams** [comment]
You can declare a variable somewhere at the top and then use it, for example

@{
    string s = string.Format("{0}.h", Model.ClassName);
}

**Comment by danwalmsley** [comment]
Thanks for quick reply.

Any chance of add support for something like this:
http://haacked.com/archive/2011/01/06/razor-syntax-quick-reference.aspx/

Mixing code and plain text (alternate)
@if (foo) {
  @:Plain Text is @bar
}

so @: switches back to plain text.

**Comment by danwalmsley** [comment]
your workaround gives me the same issue:

```
@{
	string headerName = $"{Model.ClassName}"
}
#include "@headerName.h"
```

**Comment by toddams** [comment]
I think @: should work as well, as RazorLight uses Microsoft's Razor engine under the hoods. 
Give it a try and let me know if it works (can't test it myself at the moment)

**Comment by danwalmsley** [comment]
```
#include "@Model.ClassName@:.h"
```

didn't work

**Comment by danwalmsley** [comment]
Will use your workaround for now, but would be nice to have @: working, its probably something I'm doing wrong.

**Comment by bar** [comment]
@danwalmsley hey man, please don't use my handle to document your code, danke

**Comment by danwalmsley** [comment]
@bar hehe interesting what happened there!
