### ISSUE TITLE
Discussion point; Git tags

### ISSUE THREAD

**Issue by x10an14** [toddams/RazorLight#283]
Hi!

I found [this post](https://github.com/toddams/RazorLight/issues/281#issuecomment-557673876) by @jzabroski, where he states;
> I don't think tags are a good idea. Next step would be to adopt either GitVersion, GitInfo, or Nerdbank.GitVersioning for predictable, consistent build version numbers. (...)

I've got no argument with a .NET-friendly versioning tool being the "go-to".
Or even that it ends up being utilized for that matter.

And even in conjunction with such a tool, I'm unsure why `Git tags` would be a bad idea?

## My thoughts on the matter
There's _absolutely **no**_ technical limitations<sup>1</sup> as to what a tag might consist of (the string of it that is).
So you may very well have multiple tags pointing at the same commit, like;
 - `x.y.z-alpha`
 - `x.y.z-beta`
 - `x.y.z-rc1`
 - `x.y.z-rc2`
 - `x.y.z`

The idea however, that you (the authors) say<sup>2</sup>; 
```
We validate **this** specific version (read: commit),
as the one representing the source code,
at a point we'd recommend/want others to use.
```

is one that _I for one_ would value. This is independent of the versioning scheme (and semantics) that you guys could want/decide upon.  

1: In the semantic sense - I guess one could _always_ find some security-hole á la SQL Injection.
2: Through Git's own tooling - read: tags.

### Post-thought addendums
PS: And at no point would I imagine my reasoning/suggestions here to conflict with any preferences of an automated versioning/deploy/integration -tool (as long as you - the users of that tool - are in control of it),  _and_ it doesn't lock down/limit your _semantic_ use of tags.

PPS: For what it's worth, the above described semantic usage of git tags are also what one of the original, biggest (in open source), and maybe even _canonical_ source code projects - the Linux kernel - _itself_  uses.

**Comment by jzabroski** [comment]
There is a lot to unpack here, but you're quoting me out of context.

The long and short of it is this project currently doesn't have automatic package promotion workflow builtin to the CI/CD server. If you want to do the work to set it up, then I agree, Linux kernel is a great example where the person who does the work gets the loudest/final opinion (usually).

The other side of it is, I think you're not quite getting the simplicity of Nerdbank.GitVersioning or GitVersion: every commit in the Repo will have a unique build number. It's ok, I didn't fully get it the first time, either. See my post on Reddit where I started to learn about it: https://www.reddit.com/r/csharp/comments/bn4388/why_would_i_use_gitversion/

The real risk/Downside to this "magic" is a new release to Gitversion or whatever tool could break the release process.

In the case of Gitversion, you still use tags, just not excessively. In the case of Nerdbank, you just use commits. I like the Nerdbank approach better but I'm more familiar with Gitversion and there are only so many hours to perfect things or ship it.

**Comment by x10an14** [comment]
### Immediate response
> (...) but you're quoting me out of context.
Apologies, we may be talking past each other, but I was interested in any reasoning that would lead to such a comment, independent on context =).

(You kinda answer it in the above post though - thanks!)

### Continuing thoughts ref. topic/discussion
**_Disclaimer_**: I am unfamiliar with .NET and its technical limitations ref. versioning CI/CD. 
I've just barely started dabbling in .NET core from within my linux development environments.

I take it you either conflate (or purposefully want to bundle - which is okay and relevant too) the below four aspects:
 1. versioning of this library/framework
 2. automation tools to aid in such
 3. what semantic meaning the future versioning scheme follows/prescribes (which could be any of):
    - incrementing counter - uniqueness per check-in/git push/git commit
    - the ability to tell users which version to choose between (ref. the semver standard<sup>1</sup>)
    - and more...
 4. and what technical limitations exist that will limit/construe the final implementation (like the DLL thingy in your reddit post - that was news to me).

1: https://semver.org/
### Suggestion on how to proceed

> and there are only so many hours to perfect things or ship it.

Seeing as you may not be too keen on spending more time on this (ref. above quote) I'll leave the discussion at rest with a more tidy summary of what I'd like if I could vote .

Feel free to reply/continue if you feel like this could be a useful expenditure of time:
  - That the version numbers follow the semver standard, so those who only browse nuget.org can easily choose between new features or breaking changes (or even bug fixes).
  - That there's a git tag available (matching the semver version) one could use - when one needs to e.g. debug whether or not failure lies with client or library (this repo).
     - This git tag could then be used in conjunction with `git bisect` to automatically find the commit that introduces any bug that one might want to find.

**Comment by jzabroski** [comment]
I'm always interested in becoming a better developer and one of the ways I think developers better themselves is by really understanding their whole ecosystem.

.NET Core has pretty robust CI/CD versioning, and it integrates directly into `dotnet pack` for publishing packages.  Its an epic to explain all the knobs you can turn, so you'll have to learn that yourself.

**Comment by jzabroski** [comment]
I started adding git tags since they're defacto created/maintained when doing GitHub releases.

**Comment by jzabroski** [comment]
> ### Suggestion on how to proceed
> > and there are only so many hours to perfect things or ship it.
> 
> Seeing as you may not be too keen on spending more time on this (ref. above quote) I'll leave the discussion at rest with a more tidy summary of what I'd like if I could vote .
> 
> Feel free to reply/continue if you feel like this could be a useful expenditure of time:
> 
> * That the version numbers follow the semver standard, so those who only browse nuget.org can easily choose between new features or breaking changes (or even bug fixes).
> * That there's a git tag available (matching the semver version) one could use - when one needs to e.g. debug whether or not failure lies with client or library (this repo).
>   
>   * This git tag could then be used in conjunction with `git bisect` to automatically find the commit that introduces any bug that one might want to find.

This was a really good process you suggested, @x10an14 .  Thank you.  I will likely try it out at work and if it indeed proves useful, will try it in FLOSS projects.

**Comment by x10an14** [comment]
Glad to hear I could help/have a potentially positive influence =)
