### ISSUE TITLE
operatingAssembly is null when using GetEntryAssembly for TestHost

### ISSUE THREAD

**Issue by maldworth** [toddams/RazorLight#289]
When using the TestHost for asp.net core ([WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#basic-tests-with-the-default-webapplicationfactory))

[This line](https://github.com/toddams/RazorLight/blob/60fdee0b937233d201f8c57410e6ee5a02b2dffc/src/RazorLight/RazorLightEngineBuilder.cs#L257) in the RazorLightEngineBuilder gives null.

I had to Set the operating assembly to use Assembly.GetExecutingAssembly(). GetEntryAssembly() works the rest of the time (running the api normally, not using the TestHost).

**Comment by jzabroski** [comment]
Do you think RazorLight should utilize ASP.NET Integration Testing?  If so, why?

**Comment by toddams** [comment]
@maldworth So what you propose to be a default behavior?

**Comment by maldworth** [comment]
2 options:

1. Leave it as is. Close this issue and then at least anybody who encounters can search and find the reason/workaround.
2. change the line to: `var assembly = operatingAssembly ?? Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly();`, then hopefully nobody encounters this again.

I'll let the package maintainers/contributors decide what you prefer.

**Comment by jzabroski** [comment]
But can't you just call SetOperatingAssembly?  I'm not trying to be critical of using ASP.NET Integration Testing framework, but for my tastes its a lot of machinery to test RazorLight.  If you do find value in it, I am curious what it is so I can learn.

If you CAN call SetOperatingAssembly, AND there is value to ASP.NET Integration Testing being used, then IMHO the right approach is to update the README with guidance on doing so.  Does that make sensE?

**Comment by maldworth** [comment]
Yes, I did call SetOperatingAssembly, works as expected. Correct, one doesn't need TestHost to test RazorLight specifically. Sounds like option 1 is the best choice here. Thanks for the quick responses!
