### ISSUE TITLE
Project status and roadmap

### ISSUE THREAD

**Issue by toddams** [toddams/RazorLight#29]
Hello there,

I'd like to inform you, that project is NOT  abandoned. At first, I wanted to collect the issues and then roll a stable version, but since RC-1 is released - not so many issues were reported. 
So here is a roadmap for the nearest future:

RC-2

- As everybody is moving to MSBuild - I will ensure that RazorLight is completely compatiable with it

1.1
- HTML Helpers

1.2
- TagHelpers (maybe)
- async/await support

Thank you all for supporting and contributing, you are awesome

**Comment by KolyaNET** [comment]
Will continue to support project.json?

**Comment by toddams** [comment]
Development will be done only on a new MSBuild structure. But for you, as a user who uses a library - it does not matter what to use, as it's just a nuget package
