### ISSUE TITLE
cacheResult renderTemplate code from quickstart does not compile in beta-2

### ISSUE THREAD

**Issue by ADNewsom09** [toddams/RazorLight#290]
**Describe the bug**
beta-1, the readme code to render a template worked

    var cacheResult = engine.TemplateCache.RetrieveTemplate("templateKey");
    if(cacheResult.Success)
    {
        string result = await engine.RenderTemplateAsync(cacheResult.Template.TemplatePageFactory(), model);
    }

in beta-2, this code no longer works as `engine` doesn't contain a property TemplateCache

**To Reproduce**
try to build this code using beta-2

**Expected behavior**
Code should build

**Information (please complete the following information):**
 - OS: Windows 10x64
 - Platform: .NET Core 2.2
 - RazorLight version: 2.0-beta2
 - Visual Studio version: Visual Studio Community 16.3.10 

**Additional context**
I was able to adjust the quickstart code to compile and run by changing the broken line to:

    var cacheResult = engine.Options.CachingProvider.RetrieveTemplate("templateKey");

But not sure if that still achieves the same goal of template re-use.

**Comment by ADNewsom09** [comment]
looks like the code was changed here: https://github.com/toddams/RazorLight/commit/153fc12dd2c0e1e23816e6b643dea6ff0e06a971#diff-ae7833522987db9dfee40c72bb95b173
Any guidance on the correct code with this new design? Need to update the readme

**Comment by jzabroski** [comment]
Does `engine.Handler.Cache.RetrieveTemplate("templateKey")` work?  Sorry, just responding quickly while my code compiles.

**Comment by ADNewsom09** [comment]
> Does `engine.Handler.Cache.RetrieveTemplate("templateKey")` work? Sorry, just responding quickly while my code compiles.

`IRazorLightEngine` doesn't have a property called `Handler` which is what I'm using in my code, `RazorLightEngine` does though.

**Comment by jzabroski** [comment]
I think that's a mistake.  @toddams  Do you agree that IRazorLightEngine should expose `IEngineHandler Handler {get; }`?  RazorLightEngine exposes this as a public property, so I think the interface should be symmetric with the concrete class.

**Comment by toddams** [comment]
Yup, I agree

**Comment by jzabroski** [comment]
I'll push beta3 this week with this fix, update some documentation, and include the s.nupkg for symbols so people can more easily debug.

**Comment by ADNewsom09** [comment]
So what is the 'right' way, `engine.Handler.Cache` or `engine.Options.CachingProvider` since they return the same object?

**Comment by toddams** [comment]
Well, I'd not count on options, as this is for the "initialization purpose". Dealing with Handler feels more right to me

**Comment by jzabroski** [comment]
Right.  Unless there is support for re-loading options, the right way to re-load options is through your DI container and requesting a brand new engine.  The main issue with supporting re-loading options is it has to be thread-safe re-entrant.  Also, as options may include value types, there could be potential in the future for struct tearing and other issues that would increase the maintenance cost of the code.  Ergo, don't use Options for state detection or behavior.

**Comment by jzabroski** [comment]
@ADNewsom09 Pushing beta3 now.

**Comment by ADNewsom09** [comment]
looks good. trying in our testing environment. We use razorlight in a significant azure production deployment. Working well for us. Thanks guys!

**Comment by jzabroski** [comment]
@ADNewsom09 Are you using Azure Functions?  If so, would you mind updating README to explain how you got it working?

**Comment by ADNewsom09** [comment]
Not Azure Functions, App Service.
