### ISSUE TITLE
示例代码无法运行

### ISSUE THREAD

**Issue by FreeTimeWorker** [toddams/RazorLight#291]
如题

**Comment by toddams** [comment]
It is not stated in readme, but the official language for this repo - is English. Feel free to reopen it with a proper translation

**Comment by FreeTimeWorker** [comment]
sorry ,I  has found it,  maybe readme.md need to be modfiy

**Comment by jzabroski** [comment]
It appears to be Chinese and just says "Sample code fails to run."

@FreeTimeWorker - This is not an acceptable bug report.  Even with language barrier, you need to be specific.  Post code to reproduce the problem.  Code is a universal language.
