### ISSUE TITLE
Reference to type 'IEngineConfiguration' claims it is defined in 'RazorLight', but it could not be found.

### ISSUE THREAD

**Issue by Torshe** [toddams/RazorLight#301]
I am trying to follow this tutorial as i want to inject in my layout file. https://github.com/toddams/RazorLight/wiki/ASP.NET-MVC-Core-integration, but when i try to add razorLight in my startup file i get this error
"Reference to type 'IEngineConfiguration' claims it is defined in 'RazorLight', but it could not be found."

I have an layout file (this is the file i want to inject) that looks like this:
`<head><style>some style</style><head>`
`<body>`
`   <div id="content">@RenderBody()</div>`
`</body>`

My template is like this:
`@{ Layout = layoutfile}`
`<table>`
`   content for table`
`</table>`

I have downloaded razorlight.MVC and using it in Startup file like this, but then i get the error.
![image](https://user-images.githubusercontent.com/26963478/71069980-23e29500-217a-11ea-9cdc-43fc3a6bc971.png)

**Comment by jzabroski** [comment]
@toddams I don't know where the RazorLight.Mvc package is defined, so I'm not sure how to troubleshoot this other than decompile the nuget package with dotPeek.  Thoughts?

**Comment by jzabroski** [comment]
@Torshe RazorLight.Mvc was an old incarnation of things and everything was moved into RazorLight package as part of 2.0.0 refactoring.  CC @toddams
