### ISSUE TITLE
Next stable release

### ISSUE THREAD

**Issue by mchirva** [toddams/RazorLight#314]
Hi Team,

Thanks for an excellent library! Do you have any plans on releasing a stable version in the near future?

**Comment by jzabroski** [comment]
I've been helping @toddams and I don't really know the library as well as he does as the original author.  As such, I'm hesitant to mark it as stable, but will try to continue pushing betas.  There's a semi-controversial PR submitted that changes the public interface.  

In terms of stability, though, I don't think there are any killer bugs and the current version is likely way less buggy than the last stable version.
