### ISSUE TITLE
Failed to compile generated razor view. See CompilationErrors for detailed information

### ISSUE THREAD

**Issue by williamwmd** [toddams/RazorLight#32]
Hello,
I'm trying to use a non-anonymous object and am getting the following error:

Failed to compile generated razor view. See CompilationErrors for detailed information

```
    public class TestModel
    {
        public string Name { get; set; }
    }
    var model = new TestModel()
    {
        Name = "John Doe"
    };
    var engine = EngineFactory.CreatePhysical(@"D:\");
    string result = engine.ParseString("Hello @Model.Name ", model, model.GetType());


```

**Comment by toddams** [comment]
Hi

Try to execute this code in debug mode and look on CompilationErrors of an exception. It must provide you with a detailed information

**Comment by williamwmd** [comment]
CompilationErrors:

The type or namespace name 'TestModel' could not be found (are you missing a using directive or an assembly reference?)

**Comment by toddams** [comment]
Same error happens when you do not specify a model type? I mean without model.GetType()?

Another question: model is declared at the same assembly where you use RazorLight?

**Comment by williamwmd** [comment]
Yes for their 2 questions.

**Comment by toddams** [comment]
Seem to be a bug, thank you for the report

**Comment by toddams** [comment]
Fixed
