### ISSUE TITLE
Documentation is for Beta version

### ISSUE THREAD

**Issue by joshnoe** [toddams/RazorLight#320]
The documentation is for the beta version which appears to still be very unstable judging from the many open issues (I've run into several of these already)? Maybe consider either documenting the release version or moving beta out of beta.

**Comment by jzabroski** [comment]
@joshnoe I started taking over the project end of last year.  As part of this, I realized that capturing all the use cases for RazorLight was very time consuming.  I don't think we're that far from stable release, but it's mostly down to me making time for it.  As such, I'm not going to document the 1.x releases.  I started helping Ivan with RazorLight years after those releases, and none of the code I'm using in production uses those 1.x releases.  For all intents and purposes, I don't even know the 1.x release exists.
