### ISSUE TITLE
@Model.myVar when it is followed by another char

### ISSUE THREAD

**Issue by zevero** [toddams/RazorLight#321]
**Describe the bug**
<div>@Model.lenghtInM</div> works
<div>@Model.lenghtInM m</div> works as well but
<div>@Model.lengthInMm</div> naturally does not.
This is a contrived example, but I need to have my var adjacent to other text.

**To Reproduce**
Look at the examples, look at the docs. There is no example given with syntax similar to
<div>@(Model.lengthInM)m</div> (does not work)
I also tried @Raw(Model.lenghtInM)m but got an error as well

**Expected behavior**
I expect to find an alternative syntax in docs, maybe with an example

**Information (please complete the following information):**
 - Windows 10 Enterprise 1909
 - .NET Core 2.1 , etc
 - RazorLight version [2.0.0-beta4 
 - OFFICIAL RazorLight package https://www.nuget.org/packages/razorlight
 - Visual Studio 2019

**Comment by jzabroski** [comment]
Is this a RazorLight bug, or a general Razor bug?

**Comment by jzabroski** [comment]
@zevero Need more details. What error are you getting?  Cannot reproduce.

```c#
namespace RazorLight.Tests.Models
{
	public class MetricLengthsTestViewModel
	{
		public long LengthInM { get; set; }
		public long LengthInMm { get; set; }
	}
}
```

```razor
@using RazorLight
@inherits TemplatePage<RazorLight.Tests.Models.MetricLengthsTestViewModel>

<p>@Model.LengthInMm</p>
<p>@Model.LengthInM</p>
```

I then commented out LengthInMm and then patched the first line to be:

```razor
@using RazorLight
@inherits TemplatePage<RazorLight.Tests.Models.MetricLengthsTestViewModel>

<p>@(Model.LengthInM)m</p>
<p>@Model.LengthInM</p>
```

And still have no errors.
