### ISSUE TITLE
Feature Nullable Reference Types not available

### ISSUE THREAD

**Issue by chris579** [toddams/RazorLight#324]
**Describe the bug**
When compiling a template I get the following errors
```
RazorLight.Compilation.TemplateCompilationException: Failed to compile generated Razor template:
- (11:1) Das Feature "Nullable-Verweistypen" ist in C# 7.3 nicht verfügbar. Verwenden Sie Sprachversion 8.0 oder höher.
- (17:1) Das Feature "Nullable-Verweistypen" ist in C# 7.3 nicht verfügbar. Verwenden Sie Sprachversion 8.0 oder höher.
- (24:1) Das Feature "Nullable-Verweistypen" ist in C# 7.3 nicht verfügbar. Verwenden Sie Sprachversion 8.0 oder höher.
- (30:1) Das Feature "Nullable-Verweistypen" ist in C# 7.3 nicht verfügbar. Verwenden Sie Sprachversion 8.0 oder höher.
- (32:1) Das Feature "Nullable-Verweistypen" ist in C# 7.3 nicht verfügbar. Verwenden Sie Sprachversion 8.0 oder höher.
- (38:1) Das Feature "Nullable-Verweistypen" ist in C# 7.3 nicht verfügbar. Verwenden Sie Sprachversion 8.0 oder höher.
```

Which translates to 
`The feature "Nullable reference type" is not available in C# 7.3. Use Version 8.0 or higher.`
I'm not using nullable reference types anywhere in my model or template. My template isn't even 38 lines long.

**To Reproduce**
- Create a classlib that targets `netcoreapp3.1`. 
- Create a ASP.NET Core App that targets `netcoreapp3.1`.
- Install `RazorLight` into the classlib and reference it from the main project.
- Add `IRazorLightEngine` to the DI via an extension method that is placed in the classlib
```csharp
serviceCollection.AddSingleton<IRazorLightEngine>(_ =>
                new RazorLightEngineBuilder()
                    .UseFileSystemProject(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "MailTemplates"))
                    .UseMemoryCachingProvider()
                    .Build()
            );
```
- Call this extension method in your `ConfigureServices`
- Try to compile a template

**Expected behavior**
The template compiles without errors.

**Information (please complete the following information):**
 - OS: Windows 10 1909
 - Platform .NET Core 3.1
 - RazorLight version 2.0.0-beta4
 - Visual Studio version Visual Studio Professional 2019

**Comment by hwinkelmann** [comment]
What helped in my case was to explicitly switch to C# 8 by adding `<LangVersion>8.0</LangVersion>` to some `PropertyGroup` in the `.csproj` files. Hope this helps!

**Comment by chris579** [comment]
I'm targeting `netcoreapp3.1` and have set `LangVersion` to `latest` so I have C# 8 available. Does it make a difference when I specify `8.0` explicitly?

**Comment by jzabroski** [comment]
@chris579 latest depends on your SDK, not your targeting pack.

**Comment by chris579** [comment]
In this case it would be worth mentioning this somewhere in the FAQ in the README. Seems to be a pitfall users might run into.

**Comment by jzabroski** [comment]
@chris579 Please submit a PR for what you have in mind and I'll review it.

**Comment by dariel312** [comment]
@jzabroski Thanks for this solution, I was also having this problem and spent like 3 hours trying to fix it and was literally about to submit an issue before GitHub referred me to this issue.
