### ISSUE TITLE
Philosophical question: can you consider this light?

### ISSUE THREAD

**Issue by Angele** [toddams/RazorLight#325]
![2020-03-04 12_06_12-LocalSwitchboard - Microsoft Visual Studio](https://user-images.githubusercontent.com/1502237/75873755-c2dd6b80-5e10-11ea-84d4-e2d9a0cb44f3.png)

**Comment by toddams** [comment]
Hi there
Are you bothered about the dependencies count?
If you take a look at our csproj file, you'll notice there are just a few. It's netstandard, and it will pull lots of tiny nuget packages if you use full .NET framework, or in some other circumstances.

**Comment by jzabroski** [comment]
Angele, those are just reference assemblies. RazorLight primarily refers to using Razor without ASP.NET Core MVC.

**Comment by Angele** [comment]
Yes, I was.
Thanks for clarification.
Seems like the long term solution is to change Project to .Net Framework 4.7.2, or above.
