### ISSUE TITLE
2.0.0 non-beta release

### ISSUE THREAD

**Issue by smcl** [toddams/RazorLight#327]
I've recently started using `2.0.0-beta4` in a project in work and I really like it, however the "beta" version suffix might make some organisations a little reluctant to use it. So I was wondering a few things:

- Do you have an idea of the scope for the full 2.0.0 release? Is there some functionality yet to be implemented, or some areas you'd like to test or some bugs you'd like to squash before the 2.0 non-beta can be considered "ready"
- Is there anything the community can do to assist with this? I'd be happy to pitch in with some PRs and I am sure there are others who would be willing to help too!

There have been >1m downloads of the library since the first beta, so the fact that there are only 52 "open" issues is really quite an encouraging sign! Anyway as I said, I like the library and I'd be happy to help if you have any need for it :-)

**Comment by toddams** [comment]
Hi smcl

Thank you for your interest in RazorLight project, we are very open to the new contributors :). At the moment @jzabroski is mainly supporting this library in his spare time. My vision is that we should really focus on making things stable on full 2.0. There are still a couple of annoying bugs which should be fixed. After stable we can concentrate on supporting Azure Functions, AWS Labmda and other environments, as it seems like people are actively using, but it has never been tested. 

Feel free to take any open "bug" issue, your any contribution would be appreciated a lot

**Comment by smcl** [comment]
Ah cool, so it's largely feature-complete and just needs to have outstanding bugs squashed and a bit more testing for confidence? That's good to hear. I'll take a peek at the issues next week to see if I can help 👍
