### ISSUE TITLE
Visual Studio 2019 intellisense errors

### ISSUE THREAD

**Issue by jez9999** [toddams/RazorLight#328]
Although my class library compiles and builds, I get a lot of annoying IntelliSense errors for my .cshtml template files I'm using for RazorLight, such as:

> The type or namespace name 'Rendering' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)

> The type or namespace name 'ViewFeatures' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)

> The type or namespace name 'IUrlHelper' does not exist in the namespace 'Microsoft.AspNetCore.Mvc' (are you missing an assembly reference?)

.. etc.  How can I get rid of these errors?  Is there a problem with RazorLight here?

**Comment by jez9999** [comment]
I managed to fix this by using `Project Sdk="Microsoft.NET.Sdk"` in my .csproj file, and switching target framework from `netstandard2.1` to `netcoreapp3.1` - looks like you have to use .NET Core rather than .NET Standard for it to work properly.

**Comment by jzabroski** [comment]
@jez9999 What version of VisualStudio2019 are you using?  Just wondering. Closing issue as you indicated its resolved.  Happy to look at a full repro and explain whats happening/learn from the situation myself.
