### ISSUE TITLE
Debugging capabilities

### ISSUE THREAD

**Issue by macsux** [toddams/RazorLight#338]
Is there a way to debug Razor template when using this library?

**Comment by jzabroski** [comment]
I don't debug them.  As explained in other places, I avoid business logic in the views and just test my viewmodels.  I don't use things like local functions.  If you want to write tests, look into SharpPuppeteer for fluent async/await browser automation and Verify/ApprovalTests.Net for approval testing.

You might be able to use dnSpy.  I looked at what Blazor does and they explicitly state they don't support source maps.

One piece of advice I can give is to segregate your javascrit dependencies from your RazorLight logic.  Here is an example: https://github.com/damienbod/AspNetCoreInjectConfigurationRazor - and use Premailer.net for inlining CSS into style attributes.
