### ISSUE TITLE
Example that works in LinqPad

### ISSUE THREAD

**Issue by Vaccano** [toddams/RazorLight#339]
**Is your feature request related to a problem? Please describe.**
When I tried to create the basic example using LinqPad I got the following error: 

> Can't load metadata reference from the entry assembly. Make sure PreserveCompilationContext is set to true in *.csproj file

**Describe the solution you'd like**
I would be nice if there was an easy to to get an example to run in LinqPad.  That way it is would be easy to test with.

**Additional context**
Here is the code I used to try to get this to run in LinqPad:

	async void Main()
	{
		var engine = new RazorLightEngineBuilder()
			.UseFileSystemProject("C:\\path\\to\\view\\Pages")
			.UseMemoryCachingProvider()
			.Build();
	
		string template = "Hello, @Model.Name. Welcome to RazorLight repository";
		ViewModel model = new ViewModel { Name = "John Doe" };
	
		string result = await engine.CompileRenderStringAsync("templateKey", template, model);
	}
	
	public class ViewModel
	{
		public string Name {get; set;}
	}

**Comment by Vaccano** [comment]
Nevermind.  The issue is with a setting in the project file.  I don't know if that would even be possible in LinpPad.

**Comment by jzabroski** [comment]
Please ask Linqpad for help
