### ISSUE TITLE
Razor 3.1.0 support?

### ISSUE THREAD

**Issue by Tiberriver256** [toddams/RazorLight#345]
Looks like maybe 3.1 isn't supported at the moment? I get the following runtime error:

```
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.AspNetCore.Razor.Language, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.'
```

Running on a .net core project with Microsoft.AspNetCore.Razor.Language 3.1.5 installed.

**Comment by Tiberriver256** [comment]
Sorry about this. Looks to have been a bug with the Azure Functions runtime.

**Comment by jzabroski** [comment]
@Tiberriver256 Please see the FAQ and suggest any improvements.  I wish the FAQ was not so complicated but its out of our hands.
