### ISSUE TITLE
support tag helper in string template 

### ISSUE THREAD

**Issue by mmokhtari** [toddams/RazorLight#357]
hi there

i was looking at isses your were going to add support of tag helpers to compile from string trmplate since 2017?
is there any lock we get this feature soon?

**Comment by jzabroski** [comment]
@mmokhtari I'm not sure what you're referring to in the issues backlog.  I started maintaining this project in 2019 to help Ivan (original author) out.  I personally don't have a wishlist of features but am happy to try to review pull requests.  I personally don't have much desire to add taghelpers at the moment.

**Comment by ryburn52** [comment]
@jzabroski tag helpers would be very useful for email templates, you would be able to use something like this https://github.com/XmlmXmlmX/InkyTagHelpers so you don't have to write html like it's the 90's

**Comment by jzabroski** [comment]
See #21 - I made this sticky.
