### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by Kailasl** [toddams/RazorLight#358]
is this supported in blazor? I am trying to create a simple blazor app which wiil return me html based on the template.

**Comment by jzabroski** [comment]
Create a web service to expose the html you want returned.  No direct support.  I know very little about Blazor other than watching videos.  No hands on experience, sorry.  If someone wants to add a sample of getting it working, that would be awesome.  (I dont even know if it makes sense to use this from Blazor).
