### ISSUE TITLE
Finding Views in an included class library

### ISSUE THREAD

**Issue by tpspencer** [toddams/RazorLight#362]
I am using RazorLight in a .net core 3.1 console app.
Everything is working great.
I decided to move my Views to a class library, but the "await IncludeAsync" method can not find the views.

Here is the solution structure
sln:RazorLightStandAlone
consoleApp: ConsoleNetCore\Views
classLib: BondPrint\Views

For views in ConsoleNetCore, this works great:

`				@{ await IncludeAsync("Views.RatingsBond.cshtml", Model); }
`

For views in the BondPrint class lib, these do not work:

`				@{ await IncludeAsync("ConsoleNetCore.BondPrint.Views.TopDetails2.cshtml", Model); }
`
`				@{ await IncludeAsync("BondPrint.Views.TopDetails2.cshtml", Model); }
`

How do I access views in a class library of the solution?

Thank you.

**Comment by tpspencer** [comment]
I have figured it out.  Usually happens after you post a message for help.

Thanks for the great project.

**Comment by jzabroski** [comment]
@tpspencer 
https://github.com/toddams/RazorLight#embeddedresource-source

**Comment by jzabroski** [comment]
Great.  Thank you for closing.  Happy jamming away to RazorLight.  All credit goes to @toddams for slaving over this project for years.
