### ISSUE TITLE
Invalid link in wiki.

### ISSUE THREAD

**Issue by RedlineTriad** [toddams/RazorLight#368]
**Describe the bug**
Link to MSDN at https://github.com/toddams/RazorLight/wiki does not point to a valid location.

**To Reproduce**
Open https://github.com/toddams/RazorLight/wiki and click on the linked MSDN example.

**Expected behavior**
An example on how to use the library.

**Comment by jzabroski** [comment]
I can't find that zip file online anywhere, and the Wayback Machine (archive.org) doesn't seem to have it, either.  That said, did you look at the sample project in the source code folder?

**Comment by jzabroski** [comment]
Updated wiki page.  @RedlineTriad Let me know if this addresses your issue.
