### ISSUE TITLE
Add SDK to global.json

### ISSUE THREAD

**Issue by dustinmoris** [toddams/RazorLight#37]
Another minor thing, when I pulled your code I had troubles to restore and build it initially because I have a much newer .NET SDK installed than the one used for the project.

I had to add

```
{
  "projects": [ ".", "src", "sandbox" ],
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}
```

to the global.json which basically hints to the dotnet CLI which version to use to guarantee a successful build. Only then my dotnet knew to load an older SDK and I was able to restore and build the project. Maybe if you have time you can add this, will make it easier when other people fork your project or even when you have multiple SDKs installed but not upgraded all your projects to the latest every time.

**Comment by toddams** [comment]
I have
````
<Project Sdk="Microsoft.NET.Sdk">
````
on every *.csproj file.

Running "dotnet --version" returns 1.0.0 
Do you know where project SDK version is set at new MSBuild structure?

**Comment by toddams** [comment]
Okay, looks like RazorLight.Tests reference to
````
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170217-05" />
````
caused that issue. I will updgrate all project referenes
