### ISSUE TITLE
Official sample doesn't work in .Net core 2.2 and Azure function SDK v2

### ISSUE THREAD

**Issue by rchaser** [toddams/RazorLight#374]
**Describe the bug**
This simple sample doesn't work

```
var engine = new RazorLightEngineBuilder()
	// required to have a default RazorLightProject type,
	// but not required to create a template from string.
	.UseEmbeddedResourcesProject(typeof(Program))
	.UseMemoryCachingProvider()
	.Build();

string template = "Hello, @Model.Name. Welcome to RazorLight repository";
ViewModel model = new ViewModel {Name = "John Doe"};

string result = await engine.CompileRenderStringAsync("templateKey", template, model);
```

System.Private.CoreLib: Exception while executing function: Function1. RazorLight: Can't load metadata reference from the entry assembly. Make sure PreserveCompilationContext is set to true in *.csproj file.

But it's set

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

```
**To Reproduce**
Repo with the simplest code
https://github.com/rchaser/RazorLightAndBlob

**Expected behavior**
The sample should work

**Information (please complete the following information):**
 - OS: Windows Server
 - Platform: .NET Core 2.2
 - RazorLight version: 2.0-beta4
 - Are you using the OFFICIAL RazorLight package? https://www.nuget.org/packages/razorlight - Yes
 - Visual Studio version: Visual Studio Community 2019 16.7.1

**Comment by jzabroski** [comment]
I think you should avoid v2 AzureFunctionsVersion.  It transitively uses .NET Core 2.2, which was end-of-life in December 2019.  See: https://dotnet.microsoft.com/platform/support/policy/dotnet-core and https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions

At any rate, I don't think I can support this older version.  I'm mainly just one person right now with a few people in the community pitching in.  Sorry, I'm sure this stinks as an answer, but it's simply a matter of priorities.
