### ISSUE TITLE
Layout value on EntityFrameworkRazorProject

### ISSUE THREAD

**Issue by ogazioglu** [toddams/RazorLight#375]
I couldn't find any documentation for using Layout with entityframework.

What should we set to Layout property of the template when in EntityFramework project?
Should we use a templateKey, for ex. a guid?

**Comment by HamiltonManalo** [comment]
Hi There, 

I haven't tested this personally, but in the sample project there is an example which shows how it is setup. According to the example you link layouts via PK so you seem to be on track.  https://github.com/toddams/RazorLight/blob/1e393ebf377417fc79120d5921273296f46efdd1/samples/RazorLight.Samples/Program.cs#L40

**Comment by ogazioglu** [comment]
Hi,

I have tested and seen that you needn't to do anything extra. Layout should stay as .cshtml link. Provider tries to find layout with page name as templateKey in database. So, the only thing you have to do is to store your layout page in the database with its name.

Thanks again.
