### ISSUE TITLE
Change Logs

### ISSUE THREAD

**Issue by HamiltonManalo** [toddams/RazorLight#379]
With the release of beta10 I had the realization that currently were not creating change logs with each release. One recent PR I created had a major breaking change in it that was released without any kind of notice. I realize this is quite a bit of work. But would the community, and @jzabroski consider attempting to maintain a change log and make submitting change log details part of the PR process for new PRs?

That would at least provide a trail of breadcrumbs for users to reference when the project breaks after an update.

**Comment by jzabroski** [comment]
I've been creating release notes. I didn't do it yet for beta10 since I was
heading on vacation.

**Comment by HamiltonManalo** [comment]
Ah, sounds good then.
