### ISSUE TITLE
Malicious code in a Razor template

### ISSUE THREAD

**Issue by rhegner** [toddams/RazorLight#38]
I'm using RazorLight in my web application where the user can provide mail templates in Razor syntax.

However this means that the user can do stuff like this

    @{
    var i = 0;
    while (true)
        {
        i += 1;
        <p>Line @i</p>
        }
    }

which causes my web application to crash at some point - or stuff like this

    @using System.IO
    @{ var f = File.ReadAllText(@"/etc/passwd"); }
    @f

which is also really bad.

What can I do to prevent such attacks? Is it possible to run the Razor engine in a sandbox?

**Comment by toddams** [comment]
For full .NET it is possible to run razor in isolated AppDomain, but I don't really know what can we do with .NET Core, as there is no AppDomain. I will investigate this question

**Comment by rhegner** [comment]
Yeah I know the missing AppDomain is a really severe restriction in .Net Core. And in fact I'm using .Net Core for my project...

Thanks for having a look at this!

**Comment by MissaouiChedy** [comment]
Small suggestion: Why not execute the untrusted code in a Docker container?

**Comment by hjalle** [comment]
I'm also interested in sanboxing capabilities using Dotnet core. I don't think running the untrusted code within containers is a great idea for various reasons, one of them being:

> One primary risk with running Docker containers is that the default set of capabilities and mounts given to a container may provide incomplete isolation, either independently, or when used in combination with kernel vulnerabilities.

From: https://docs.docker.com/engine/security/security/
through https://security.stackexchange.com/questions/107850/docker-as-a-sandbox-for-untrusted-code

**Comment by denismaster** [comment]
We can also sanitise input files for this construnctions. In my project i created a whitelist of constructions that users can use. No dangerous constructions = no problem)

**Comment by rhegner** [comment]
@denismaster could you go into a bit more detail about how you did that sanitization?
To do that properly your sanitizer would need a very deep understanding of Razor/C# syntax. Doesn't that mean you basically end up writing your own Razor interpreter (and still potentially leave many security loopholes open)??

**Comment by aviatrix** [comment]
@denismaster  i'm also interested in this, can you please share more details?

**Comment by denismaster** [comment]
I've enabled user to choose only one of predefined c# constructions, such as `@Model`, `@foreach` and `@if`. I'm using regex to find another language constructions things, and if there're any of them, the code will be stopped and request will be rejected. 
Yes, this solution isn't the best, it can contains(and i think it contains)  loopholes, but for me there is a good solution.

**Comment by toddams** [comment]
So far I could not find any options that would allow us to achieve exact code isolation as we could get running a separate AppDomain. Let this issue be opened till we find something decent to prevent running malicious code from non-trusted sources.

Thanks you @denismaster for sharing your ideas with us!

**Comment by dustinmoris** [comment]
Hi, I just wanted to chip in that for use cases like email templates and other user driven templates there is the [DotLiquid template engine](http://dotliquidmarkup.org/) which is exactly designed for doing this securely. This is why web frameworks like [Giraffe](https://github.com/dustinmoris/Giraffe) offer a Razor engine for normal web pages and DotLiquid for user customizable templates.

**Comment by rhegner** [comment]
@dustinmoris DotLiquid looks interesting. And even though it's not stated explicitly on their webpage, it seems to support .Net Core :)

**Comment by svarga91** [comment]
I used ExcludeAssemblies for this purpose
```
            var excludeAssembliesNames = new string[]
            {
                typeof(System.IO.File).Assembly.FullName
            };
            
            var engine = new RazorLightEngineBuilder()
                .UseProject(project)
                .SetOperatingAssembly(typeof(ViewModel).Assembly)
                .ExcludeAssemblies(excludeAssembliesNames) // To prevent @using System.IO @{{File.ReadAllText(@\"/etc/passwd\");}} in template
                .UseMemoryCachingProvider()
                .Build();
```

**Comment by reponemec** [comment]
@svarga91 : Using your snippet as is, my application throws the following FileNotFoundException: 

System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.\r\nFile name: 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'\r\n   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)\r\n   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)\r\n   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssemblies(Assembly a, ISet`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()\r\n   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssemblies(Assembly a, ISet`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()\r\n   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssembl
ies(Assembly a, ISet`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()\r\n   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)\r\n   at System.Linq.Enumerable.UnionIterator`1.FillSet()\r\n   at System.Linq.Enumerable.UnionIterator`1.ToArray()\r\n   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly, DependencyContext dependencyContext)\r\n   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)\r\n   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()\r\n   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()\r\n   at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)\r\n   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)\r\n   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)\r\n   at RazorLight.Compilation.RazorTemplateCompi
ler.CompileAndEmitAsync(RazorLightProjectItem projectItem)\r\n   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)\r\n   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)\r\n   at RazorLight.EngineHandler.CompileTemplateAsync(String key)\r\n   at RazorLight.EngineHandler.CompileRenderAsync[T](String key, T model, ExpandoObject viewBag)\r\n   at ASDSoft.ProGrant.Common.Infrastructure.Messages.TemplateValidator.ValidateTemplateAsync(TemplateToRender templateToRender) in D:\\ASD Projects\\ProGrant\\Backend\\Common\\Common\\Infrastructure\\Messages\\TemplateValidator.cs:line 47

Haven't you encountered this problem as well?
