### ISSUE TITLE
.NET 5.0 Support

### ISSUE THREAD

**Issue by nm-a** [toddams/RazorLight#386]
Hi,
Just would like to know the tentative timeline for .NET 5.0 Support. Do you have a plan in place currently?

Thank you

**Comment by jzabroski** [comment]
No plan to work on it at the moment.  Happy to accept PRs, as well as give guidance.  There is really one or two minor issues that need addressing, plus some testing that needs to happen.  Free Time is the bottleneck on my side right now.

**Comment by jzabroski** [comment]
I just merged one blocking issue, so I think there might be one other blocker.

**Comment by nm-a** [comment]
hi @jzabroski 
I have upgraded all the nuget packages to .NET 5.0 (added .net 5.0 new target framework and removed netcoreapp2.0). Returning below error when I try to create a pull request.


![image](https://user-images.githubusercontent.com/7089157/98938968-b87e8000-250e-11eb-8f2f-e42cb360d74c.png)


Thank you

**Comment by jzabroski** [comment]
@nm-a I just published to nuget.org.  Should show up in about an hour.  Thanks for your help.  If you'd like to contribute more I have some suggestions for a hackfest.
