### ISSUE TITLE
Performance of Parsing Strings

### ISSUE THREAD

**Issue by joetherod** [toddams/RazorLight#39]
My html for emails is stored in the db. I am using the ParseString. I have many emails to send that use different html strings. I ran a test to use the same html string with a new model with different properties. The parse time goes from 200 milliseconds and gradually increases about 25 milliseconds to parse. Why does the parse time increase at all? This can add up significantly when sending thousands of emails. Any way to support caching for parsing strings to reduce this gradual increase? I can see the first parse have the biggest time impact, but subsequent parsing of same string with different model properties should go down significantly and be fairly slower than the original parse. Right??

**Comment by toddams** [comment]
Hi @joetherod 

Right, most of the time is spent on compilation of the Razor Template. When you Parse files - you provide a unique key that, in case of file - it's filename. So when RazorLight compiles a template - it caches it and puts inside a MemoryCache, so next time when you Parse the same file - it takes it from cache. But strings are compiled everytime, thats why it takes so much time to execute

RazorLight has not so powerfull API at the moment to control how templates are cached, meaning you can only rely on an existing mechanism. While reading your issue I'm getting more and more confident that RazorLight should become more flexible and give user rights to decide how they want their templates to be cached no matter what source it is loaded from: string / file / resource/ etc.

I will put this into backlog as I find it aas a very significant improvement. 
So it could look like this in the future:
````CSharp
RazorLight.LoadTemplate("yourStringHere").WithKey("yourKey").Build();
//and then
string result = engine.Parse("yourKey");
````


For now what can I propose you - is to store your templates in files. I can imagine you have sort of management panel when you change your template. After you save it - rewrite the file, RazorLight knows about the changes made to the templates that are already cache and your template will be recompiled. Dirty, I know, but that's the only way you can do stuff at the moment
