### ISSUE TITLE
Implement string caching

### ISSUE THREAD

**Issue by toddams** [toddams/RazorLight#40]
This issue is caused by #39. 

That is a real world scenario, when a template source is loaded from database, and running "ParseString" causes performance issues on more-or-less loaded systems, as templates are not cached

**Comment by NickDarvey** [comment]
Hi @toddams,

Where was this on the roadmap? (And did you already know how you wanted to implement this?)
Is this something I could work on and open a PR for?

Nick

**Comment by toddams** [comment]
Hello Nick
I'm currently waiting for .NET 2.0 as Microsoft did major refactoring to Razor repo and a LOT of code has been changed. So in order to avoid double-work, it's currently on hold. 
The good part is that refactoring made by Microsoft would make it easier to implement all the missing features, as code became more clear and structured

**Comment by ryancyq** [comment]
Hi @toddams Will this be implemented soon? 
For reference, [AspNetCore.Razor 2.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Razor/2.0.0) is out

**Comment by toddams** [comment]
Yes, I'm aware about asp.net MVC 2.0
All the information regarding v2.0 is here -https://github.com/toddams/RazorLight/issues/63

**Comment by toddams** [comment]
Implemented in 2.0.0-alpha3

**Comment by huanbd** [comment]
Hi @toddams ,
Can you show me guide, how to manage string caching (Precompile template when template change)?

Thank you.

**Comment by jjxtra** [comment]
I'm also looking for guidance on how to invalidate a string in the cache, doesn't seem to be a way currently...

@toddams
