### ISSUE TITLE
MvcServiceCollectionExtensions exception

### ISSUE THREAD

**Issue by MarcAir** [toddams/RazorLight#41]
After latest version of vs2017 and sdk for .net core - getting 

>Message	"Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'."	string
$exception	{System.MissingMethodException: Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at RazorLight.MVC.MvcServiceCollectionExtensions.AddRazorLight(IServiceCollection services, String root, Action`1 config)
   at air.Startup.ConfigureServices(IServiceCollection services)}	System.MissingMethodException

Tried updating the package to for razorlight to rc3 and razorlight.mvc to 1.0.3 
last try updated Microsoft.Extensions.DependencyInjection to latest version 1.2.preview1-24163

still same exception. 
not sure if its a configuration issue I have or if it is something that is broken due to SDK updates.
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.10 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586
ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
.NET Core SDK 1.0.0

**Comment by toddams** [comment]
Try to clean your project and rebuild

**Comment by MarcAir** [comment]
Thanks @toddams, that was the first thing I tried - I do feel there is probably nothing amiss with your package, but rather with my library setup. 

**can I run it with netcoreapp 1.0.3 and framework 1.1.1?**
(to be honest, I don't know if the packages get up/downgraded by mixing the libraries, its just that this was the only way I could migrate my project before from json to msbuild.)

**Comment by MarcAir** [comment]
Update:
there was an issue with the websockets preview version that I reverted back to 1.0.1 -
here is the fix I found on [stack](http://stackoverflow.com/questions/42491515/typeloadexception-in-microsoft-aspnetcore-server-kestrel-on-startup-for-net-cor)

**Comment by Igoreso** [comment]
I'm having the same issue with 1.1.0 and ASP.NET Core 2.0 (I cannot use 2.0.0 alpha for different reason). 
Tried cleaning and rebuilding project (and adding `PreserveCompilationContext` beforehand) - no luck.
All nuget packages we use have "stable" versions.
