### ISSUE TITLE
Template content with "\r\n"

### ISSUE THREAD

**Issue by cksanjose** [toddams/RazorLight#416]
I'm using RazorLight to generate an automated email. The email is in text format.
The content contains a list of items and each item ends with "\r\n" so they are rendered in new line.

**To Reproduce**
The content is:

    "* OriginalFileName16755af9-c1ea-42f3-a0b8-e37f869a21f7\r\n"

It is rendered as:

    "* OriginalFileName16755af9-c1ea-42f3-a0b8-e37f869a21f7&#xD;&#xA;"

**Expected behavior**
_If you're getting an assembly not found error, you need to include a sample csproj, as there is no way to know why this occurs without seeing how you set-up your project._

**Information (please complete the following information):**
 - OS: Windows 10
 - Platform .Net Core 3.1
 - RazorLight version 3.0.2
 - Are you using the OFFICIAL RazorLight package? Yes
 - Visual Studio version 2019

**Additional context**

**Comment by jzabroski** [comment]
@cksanjose Can you try the DisableEncoding mentioned in the README
