### ISSUE TITLE
Experimental blazor editor disables Intellisense

### ISSUE THREAD

**Issue by ctrl-alt-d** [toddams/RazorLight#426]
In my environment, after enabling [Experimental blazor editor](https://devblogs.microsoft.com/aspnet/improvements-to-the-new-razor-editor-in-visual-studio/#get-started), Intellisense stops work.

**Comment by jzabroski** [comment]
This doesn't seem like a Razorlight issue. Can you please report a bug following the blog post you linked to. They explicitly ask for feedback. 

I can update the FAQ but ideally you submit a PR with a link to your bug report.

**Comment by dani-herrera-udg** [comment]
Hi @jzabroski , thanks about your fast reply, first of all, will be wonderful to know if more people has the same issue or just me.

If it is a generalized problem, then, I can try to code an agnostic, minimal and reproducible example about this behavior in order to open the issue. 🙌

**Comment by jzabroski** [comment]
@dani-herrera-udg I'm a little frustrated here - I just explained you need to report a bug to Microsoft, not me.  You're literally using a Visual Studio feature marked as Experimental, linking me to a blog post explaining its experimental and the Project Manager at Microsoft is encouraging people to file bug reports, but you're sending bug reports _**to me**_, not Microsoft.

Am I being unreasonable in being frustrated with you right now?  Please, do as I ask, and file this in the right place.
