### ISSUE TITLE
Documentation needed for the methods that you are supporting

### ISSUE THREAD

**Issue by jeevasusej** [toddams/RazorLight#435]
Please add document in details for the all the method and the properties that you are supporting. 

For example, how to use html helpers, tag helpers, encode element etc

**Comment by toddams** [comment]
Neither HTML Helpers, nor Tag Helpers are supported. 
If there is no built-in object inside a templatePageBase for the encoding, you can use your own. Razor template is very extensible. 

Btw, there is a issue template, do not neglect to fill it, it's there for a reason
