### ISSUE TITLE
I get RazorLightException when trying to call lib that contains razor templates from console application

### ISSUE THREAD

**Issue by ossaltu** [toddams/RazorLight#44]
Exception text:

`RazorLight.RazorLightException: 'Can't load metadata reference from the entry assembly. Make sure preserveCompilationContext is set to true in buildOptions section of project.json or in *.csproj file'`

Here is the solution with isolated case: 
[https://1drv.ms/u/s!AuXjDEud3Cas10ihf9jpraKC316w](https://1drv.ms/u/s!AuXjDEud3Cas10ihf9jpraKC316w)

**Comment by toddams** [comment]
I downloaded your project, did not change anything and it runs just fine

![](https://i.gyazo.com/c8a2381816d64d1eb9218f636fa1c9fd.png)

**Comment by ossaltu** [comment]
I've updated the example:
[https://1drv.ms/u/s!AuXjDEud3Cas11GysXD1m7XJR-Sv](https://1drv.ms/u/s!AuXjDEud3Cas11GysXD1m7XJR-Sv)

changing
`<TargetFramework>netcoreapp1.1</TargetFramework>`
to
`<TargetFramework>netstandard1.6</TargetFramework>`
in class lib was the key

**Comment by ForNeVeR** [comment]
@ossaltu, I suspect that you didn't clean the project before rebuilding and trying that again. It was an issue for myself. I've just created the PR to add this warning to README.

**Comment by mcintyre321** [comment]
Add `<PreserveCompilationContext>true</PreserveCompilationContext>` to the csproj, worked for me!

**Comment by ossaltu** [comment]
Yes, clean rebuild seems to be working

**Comment by alexsandro-xpt** [comment]
@ossaltu and @toddams I got a same problem.
As @ForNeVeR was mentioned, is really important.
If someone is using Visual Studio Code for development, delete `bin` and `obj` folder and then `dotnet restore` and `dotnet build` the solution and after `dotnet run`.
