### ISSUE TITLE
Header Template on each page

### ISSUE THREAD

**Issue by matthewwren** [toddams/RazorLight#449]
Is there a way to apply a header template to each page?

**Comment by jzabroski** [comment]
Why doesnt layouts work for you

**Comment by matthewwren** [comment]
Layouts don't apply to each page, they apply to the entire document as far as I have seen, unless I am missing something?  For example try to create a pdf a random amount of pages long and at the top of each page place in capital letters ACME LIMITED and an address.

**Comment by matthewwren** [comment]
Sorry this was not a question for RazorLight but a different library.  My mistake :(
