### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by williamwmd** [toddams/RazorLight#45]
Hello,
I'm trying to send data with accent and special characters, but it's returning me the data in an incorrect way.

See my example, the result should be:
`Olá - Olá`

But it is returning:
`Olá - Ol&#xE1;`

My code:
```
    public class TestModel
    {
        public string Name { get; set; }
    }
    public class Program
    {
        public static void Main(string[] args)
        {
            var model = new TestModel()
            {
                Name = "Olá"
            };

            var engine = EngineFactory.CreatePhysical(@"D:\");
            string result = engine.ParseString("Olá - @Model.Name", model, model.GetType());
            //=> "Olá? - Ol&#xE1;?"
        }
    }
```
Version: "RazorLight": "1.0.0"

**Comment by toddams** [comment]
Try to use @Raw() on your words that contain special characters (https://github.com/toddams/RazorLight/wiki/Encoding)
