### ISSUE TITLE
RazorLight 2.0.0-rc.3 release issue

### ISSUE THREAD

**Issue by ps-ahella** [toddams/RazorLight#459]
@jzabroski It looks like the rc3 release contains the same dlls as the rc2 release. I found this while I was searching for a solution for a TemplateNotFoundException in my project and trying to turn the new debug flag on (but the option was missing).

I've downloaded (from nuget.org) and compared the content of the rc3 and rc2 packages and they match. Can you please check and fix this. 

Thanks,
Albert

**Comment by jzabroski** [comment]
Hi Albert,

Whoa - thanks for catching this.  I confirmed.  I'm at work right now but I will deal with this tonight.

![image](https://user-images.githubusercontent.com/447485/140334655-b78753da-3f6b-4998-b06c-cb3a0e9e4af8.png)

**Comment by jzabroski** [comment]
@ps-ahella  I automated (most) of the release process to nuget.org last night as a GitHub Action, an an effort to get away from manual deploys from my machine.  Please check: https://www.nuget.org/packages/RazorLight/2.0.0-rc.4

I have not compared it myself yet - pressed for time today.

**Comment by jzabroski** [comment]
Verified fixed.

**Comment by ps-ahella** [comment]
Thanks @jzabroski. Sorry, did not have time to check it. Time is the most valuable thing we have (or not :-) ).
