### ISSUE TITLE
ExpandoObject as model type throws RuntimeBinderException

### ISSUE THREAD

**Issue by aristovg** [toddams/RazorLight#47]
Hi, 

This code throws RuntimeBinderException (Additional information: 'System.Dynamic.ExpandoObject' does not contain a definition for 'price')

```csharp
var engine = EngineFactory.CreatePhysical("D:\\views");

var obj = new ExpandoObject();
dynamic dynamicObj = obj;
dynamicObj.price = 30;

engine.Parse("test.cshtml", obj);
```

I believe problem occurs because of this line: 
https://github.com/toddams/RazorLight/blob/master/src/RazorLight/ModelTypeInfo.cs#L42

Seems that ToExpando()  doesn't handle ExpandoObject parameter correctly, as it returns new empty ExpandoObject as a result. 

Thanks!

**Comment by toddams** [comment]
That's right, ToExpando() method expects to receive anonymous object and convert it to ExpandoObject. 
I will add additional check, thanks
