### ISSUE TITLE
Update Embedded Resource Docs to be more explicit

### ISSUE THREAD

**Issue by mwasson74** [toddams/RazorLight#472]
**Is your feature request related to a problem? Please describe.**
Clearer documentation on how to implement Embedded Resources is desired

**Describe the solution you'd like**
Update the [Embedded Resources](https://github.com/toddams/RazorLight#embeddedresource-source) section of the README.md to include a combination of what @maxbanas mentions [here](https://github.com/toddams/RazorLight/issues/378#issuecomment-719610138) regarding the project structure and the related code and also [here](https://github.com/toddams/RazorLight/issues/385#issuecomment-728197671) regarding setting the root namespace. After trial and error and scouring the issues, I was able to put these 2 things together to make things work.

**Comment by jzabroski** [comment]
Hi @mwasson74  - PRs welcome.

**Comment by mwasson74** [comment]
I'll see what I can do!! 🤞
