### ISSUE TITLE
error while using  .UseEmbeddedResourcesProject(System.Reflection.Assembly.GetEntryAssembly())

### ISSUE THREAD

**Issue by passronny** [toddams/RazorLight#474]
hi I am using razorlight in .net core2.2 MVC  web project, i have registered the services of razorlight in the Startup.cs class as shown below

` var engine = new RazorLightEngineBuilder()
                .UseEmbeddedResourcesProject(System.Reflection.Assembly.GetEntryAssembly())
                //.UseFileSystemProject($"{RootPath}\\Views")
                .EnableDebugMode(true)
                .UseMemoryCachingProvider()
                .Build();

            services.AddSingleton<IRazorLightEngine>(engine); `

i have also created a generic class that converts my views to string , one of the methods is below

`  public async Task<string> GenerateNotificationContent(string messageBody,
            string pathToView)
        {
            var model = new CustomEmailMessageModel
            {
                MessageBody = messageBody               
            };

            return await razorLightEngine.CompileRenderAsync($"{pathToView}", model);
        } `

the views that i want are in the Views folder of the project, so when calling the above method i provide the path to the view that i want e.g  Views/Subfolder/View but im getting the below error

RazorLightProjectItem of type RazorLight.Razor.EmbeddedRazorProjectItem with key Views/Subfolder/view.cshtml could not be found by the RazorLightProject of type RazorLight.Razor.EmbeddedRazorProject and does not exist in dynamic templates. See the "KnownDynamicTemplateKeys" and "KnownProjectTemplateKeys" properties for known template keys.

what am i doing wrong

**Comment by jzabroski** [comment]
Did you read the error message?  It says:
 See the "KnownDynamicTemplateKeys" and "KnownProjectTemplateKeys" properties for known template keys.

Put a breakpoint and check that please.

**Comment by vijkumarsharma** [comment]
@passronny @jzabroski  is this issue resolved?
I am also facing the same issue

**Comment by jzabroski** [comment]
@vijkumarsharma I will repeat:

> Did you read the error message? It says:
> See the "KnownDynamicTemplateKeys" and "KnownProjectTemplateKeys" properties for known template keys.
> 
> Put a breakpoint and check that please.

Your last reply in [#250](https://github.com/toddams/RazorLight/issues/250#issuecomment-1252332133) was vague and non-constructive.  I don't know what you see, and you made no efforts to describe what you see when you put a breakpoint.  Describing something as "not fruitful" and "the same issue" is not descriptive.  At most, you can conclude you have the same error message, not the same issue.

**Comment by JMcConahie** [comment]
Can you verify that you set the "Build Action" to "Embedded resource" in the properties of the .cshtml files? I had a similar issue and realized I forgot this step.

**Comment by jzabroski** [comment]
Close this as it seems to be something people report when they don't read the FAQ or exception message

**Comment by ruffin--** [comment]
> Can you verify that you set the "Build Action" to "Embedded resource" in the properties of the .cshtml files? I had a similar issue and realized I forgot this step.

This was useful, but RazorLight was still missing my templates and showing nothing (both collections had counts of 0) when I tried...

```
catch (TemplateNotFoundException templateNotFoundException)
{
    var projectKeys = string.Join(" -- known project key\n", templateNotFoundException.KnownProjectTemplateKeys);
    var dynamicKeys = string.Join(" -- known dynamic key\n", templateNotFoundException.KnownDynamicTemplateKeys);

    Console.WriteLine($"{projectKeys}\n\n{dynamicKeys}");

    throw;
}
```

The code below, based on [this SO answer](https://stackoverflow.com/a/21638620/1028230) used in a standard console app with `Program.cs` as its main file, was helpful for getting a valid path to a template resource if all else fails:

```
public static void ListTemplateResources()
{
    var rootType = typeof(Program);
    var rootTypeAssembly = rootType.Assembly;

    var resourcePaths = rootTypeAssembly.GetManifestResourceNames();
    Console.WriteLine(string.Join(" -- ", resourcePaths));
}
```

That did output the path to the template I expected to see, and hard-coding the path(s) provided, in my case...

```
var engine = new RazorLightEngineBuilder()
    .UseEmbeddedResourcesProject(
        typeof(Program).Assembly // could've also used the class I'm in now in my case
        ,"ACME.Reports.Builder.Templates"
    )
    .UseMemoryCachingProvider()
    .EnableDebugMode(true) // TODO: remove when live
    .Build();

string reportHtml;
try
{
    reportHtml = await engine.CompileRenderAsync(
        "template.cshtml",
        viewModel
    );
}
// ...
```
.... (where `template.html` was in a folder named `Templates` in the project) worked fine. Even if it's PEBKAC, this is pretty failsafe.
