### ISSUE TITLE
Trying to test on netcore 2.0

### ISSUE THREAD

**Issue by danwalmsley** [toddams/RazorLight#48]
If I use from a .netcore 2.0 app I get:

when trying to parse (I think this is compile errors when compiling the template)

How does the compiler know which assemblies to use?

```
RazorLight.TemplateCompilationException: 'Failed to compile generated Razor template:

- The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)

- The type or namespace name 'Threading' does not exist in the namespace 'System' (are you missing an assembly reference?)

- Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?

- Predefined type 'System.Boolean' is not defined or imported

- The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

- The return type of an async method must be void, Task or Task<T>

- The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

- Predefined type 'System.Object' is not defined or imported

- The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)

- 'ArmLinkerScriptTemplate_template.ExecuteAsync()': return type must be 'Task' to match overridden member 'TemplatePage.ExecuteAsync()'

- The type 'Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

- Predefined type 'System.Void' is not defined or imported
```

**Comment by toddams** [comment]
RazorLight isn't tested with .netcore 2.0, so it's not a surprise for me :)

I will only support .netcore 2.0 after stable release, as Microsoft is making quite significant refactorings on Razor repository and API can change.

About dependencies: RazorLight loads dependencies from your entry assembly

**Comment by danwalmsley** [comment]
so it should be trying to find `System` and `System.Linq` from my main entry assembly?

**Comment by toddams** [comment]
Yep, but I think that problem is more global

**Comment by danwalmsley** [comment]
ok I think I can hand on for stable release :)

**Comment by kadamgreene** [comment]
With 2.0.0-alpha3, I am getting the same error (The type or namespace name 'Razor' does not exist in the namespace 'RazorLight') when placed in a .NET Core 2.0 console application:

```
static void Main(string[] args)
        {
            EngineFactory factory = new EngineFactory();
            var engine = factory.ForFileSystem(".");
            Console.WriteLine(engine.CompileRenderAsync<string>("Hello", null).Result);
        }

```
and Hello.cshtml is:

`Hello World`

I added reference to Microsoft.AspNetCore.Mvc.Razor (because visual studio was complaining about not having the reference), but that didn't fix it.

**Comment by sigpop** [comment]
Just confirming this is still the case with 2.0.0-beta1

var engine = new RazorLightEngineBuilder()
              .UseMemoryCachingProvider()
              .Build();
string result = await engine.CompileRenderAsync("templateKey", "Name escaped = @Uri.EscapeDataString(@Model.Name)", new { Name = "bob"} );

throws this error:

Response bodyDownloadSystem.AggregateException: One or more errors occurred. (Failed to compile generated Razor template: - (0:16) The name 'Uri' does not exist in the current context

Old version 1 code worked fine:

var eng = EngineFactory.CreatePhysical(@"/");
string result = eng.ParseString(templateText, model);

**Comment by csalee** [comment]
Workaround is to use namespace.  So, instead of "Exception", use "System.Exception"

**Comment by Sword-Smith** [comment]
> 
> 
> Just confirming this is still the case with 2.0.0-beta1
> 
> var engine = new RazorLightEngineBuilder()
> .UseMemoryCachingProvider()
> .Build();
> string result = await engine.CompileRenderAsync("templateKey", "Name escaped = @Uri.EscapeDataString(@Model.Name)", new { Name = "bob"} );
> 
> throws this error:
> 
> Response bodyDownloadSystem.AggregateException: One or more errors occurred. (Failed to compile generated Razor template: - (0:16) The name 'Uri' does not exist in the current context
> 
> Old version 1 code worked fine:
> 
> var eng = EngineFactory.CreatePhysical(@"/");
> string result = eng.ParseString(templateText, model);

Including the System namespace in the .cshtml file fixed this problem for me.
