### ISSUE TITLE
Performance Expectations

### ISSUE THREAD

**Issue by TheWrightDev** [toddams/RazorLight#482]
We were looking for something to easily crank out some template emails and initially this seemed like a good way to go. We made a project with our .cshtml files as embedded resources but that first run for each template is just so slow. Especially when developers are iterating on a layout are now waiting an additional 30+ seconds just to see how a change is rendered. 

For example, a relatively simple one page with template with no includes or anything extra:
![image](https://user-images.githubusercontent.com/6202690/169360106-7ee7dc3f-6f40-4721-8225-7f1c186e18f6.png)

Is this normal? Is there anything we can do ahead of time to cut down the initial load for these?

**Comment by jzabroski** [comment]
It would need to be precompiled.  There is code in the main branch to do just that, but nobody ever productionalized it.  PRs welcome.
