### ISSUE TITLE
Get the line number with an error in TemplateCompilationException

### ISSUE THREAD

**Issue by KolyaNET** [toddams/RazorLight#49]
I can get the line number of the error in `TemplateParsingException`.
How can I get the line number in a `TemplateCompilationException ` or `Exception`?

**Comment by toddams** [comment]
TemplateCompilationException has no error line number at the moment, but it can added, I think

**Comment by KolyaNET** [comment]
@toddams That would be good. I think my knowledge is not enough to help with the implementation.

**Comment by toddams** [comment]
Don't worry, I will add this ;)

**Comment by toddams** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6703574/25009118/51c638b0-206e-11e7-80c6-bc74fc6d4ada.png)

It looks like this now, is that acceptable for you, @KolyaNET ?

**Comment by KolyaNET** [comment]
@toddams It looks good. What does the number 7 signify?

**Comment by toddams** [comment]
Line number, and column number

**Comment by KolyaNET** [comment]
@toddams Excellent. Thank you. When will the new release?

**Comment by toddams** [comment]
Today
