### ISSUE TITLE
Missing space in exception message

### ISSUE THREAD

**Issue by BryceBarbara** [toddams/RazorLight#498]
https://github.com/toddams/RazorLight/blob/732fc8616cb57d572719e18348b1d9fdd3904866/src/RazorLight/TemplatePage.cs#L26

When compiled, it looks like:

```c#
throw new InvalidOperationException("IncludeFuncis not set");
```

It should be:

```c#
throw new InvalidOperationException(nameof(IncludeFunc) + " is not set"); 
```

**Comment by jzabroski** [comment]
ty. PR welcome

**Comment by jzabroski** [comment]
@BryceBarbara I already took care of this 5 days ago, see commit history.
