### ISSUE TITLE
Could not load type Microsoft.Extensions.Primitives.InplaceStringBuilder when using UseFileSystemProject

### ISSUE THREAD

**Issue by comparin19** [toddams/RazorLight#503]
When I create a RazorLIghtEngineBuilder using the UseFileSystemProject method, I cannot call CompileRenderAsync without getting this error:
Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**To Reproduce**

 var engine = new RazorLightEngineBuilder()
                    .UseFileSystemProject("myFilePath"))
                    .Build();

                string html = await engine.CompileRenderAsync("myFile.cshtml", model);

**Expected behavior**
The html is materialized using the given model. 

**Information (please complete the following information):**
 - OS: Windows11
 - Platform : .NET Core 3.1
 - RazorLight version 3.02
 - Are you using the OFFICIAL RazorLight package? YES
 - Visual Studio version :   Visual Studion Enterprise 2022

**Additional context**
We are using Microsoft.Extensions.Primitives version 6.0 elsewhere in our application so we cannot install an earlier version. 
Everything works fine when using the UseEmbeddedResourceProject option, so the .cshtml files and the model are correct.

**Comment by jzabroski** [comment]
> We are using Microsoft.Extensions.Primitives version 6.0 elsewhere in our application so we cannot install an earlier version.

Well, what do you suggest?

> RazorLight version 3.02

There is no RazorLight version 3.02

Basic servicing fix was done in https://github.com/toddams/RazorLight/issues/365

**Comment by comparin19** [comment]
Very sorry. I was using your RazorLight.NetCore3 package (thus the version 3.0.2).
When I switched to the RazorLight (version 2.3.0) package everything works fine.
