### ISSUE TITLE
DateTime arithmetic inside templates 

### ISSUE THREAD

**Issue by forik** [toddams/RazorLight#51]
Hi,
Inside a template I have an expression like "@((Model.ExpirationDate - System.DateTime.UtcNow).Days)".
Let's say that ExpirationDate = DateTime.UtcNow.AddDays(10);

In my unit test I have:

```
var expected = (ExpirationDate - DateTime.UtcNow).Days.ToString();
var actual = renderer.Render("@((Model.ExpirationDate - System.DateTime.UtcNow).Days)", new {ExpirationDate});
Assert.Equal(expected, actual);
```

And it throws as actual in this case is 10, but expected is 9. This test works fine when I use DateTime.Now.

**Comment by toddams** [comment]
what is Renderer?

**Comment by forik** [comment]
Ah, sorry. Renderer is just a wrapper around EnginceFactory.CreatePhysical(Path.GetTempPath());
renderer.Render is converted to: ParseString(template, model, model.GetType())

**Comment by toddams** [comment]
Have you tried to do the same on traditional ASP.NET MVC?

**Comment by forik** [comment]
Sorry, the original post was incorrect: expected is 10 and actual is 9!

Anyway, just tried returning a View from Action in ASP.NET Core Mvc
Result: 10, which is correct. And RazorLight renders 9, which is incorrect

**Comment by toddams** [comment]
That sounds really weird, but I'm still investigating what might cause this issue

**Comment by toddams** [comment]
I'm not sure if this is actual for 2.0 version. Feel free to open this issue again, if so
