### ISSUE TITLE
Project can not find template with key

### ISSUE THREAD

**Issue by MikeOtown** [toddams/RazorLight#516]
.Net 6.0

When I call engine.CompileRenderAsync() I'm getting

TemplateNotFoundException: Project can not find template with key XXX

However,

typeof(myclass).Assembly.GetManifestResourceNames().Where(kn => kn == "XXX").First()

returns the Resource Name

**Comment by jzabroski** [comment]
Are you using embedded resource project or filesystem project or something else?

**Comment by MikeOtown** [comment]
Hi - It's been a while since I worked on this, but I think it was a Class Library Project with embedded resources.  However, I'm no longer using RazorLight so can't really work on this issue at this time.

**Comment by jzabroski** [comment]
OK, I will close this issue. Thanks for your fast follow up.
