### ISSUE TITLE
The CompileRenderStringAsync still caching templates

### ISSUE THREAD

**Issue by alexey62soft** [toddams/RazorLight#518]
Hi everyone!

It seems in RazorLight I can't completely disable caching.

I try to use the following configuration:

```csharp
services.AddRazorLight(() => new RazorLightEngineBuilder().UseNoProject().Build());
```

and render approach (fetching template from datastore):

```csharp
var result = _razorEngine.CompileRenderStringAsync("type", "template", new());
```

After some investigation I found the `EngineHandler` that relies on `RazorTemplateCompiler` has an uncontrolled "L0" cache:
https://github.com/toddams/RazorLight/blob/master/src/RazorLight/Compilation/RazorTemplateCompiler.cs#L46

On another side, EngineHandler has an instance of RazorLightOptions with DynamicTemplates property which stores the actual version of the template. But, due to having an "L0" Compiler cache, it still returns an obsolete result.

**To Reproduce**

All steps and explanations - are above.

**Expected behavior**

I expect to receive the actual version of the template and don't have it cached in the compiler.

**Information (please complete the following information):**
 - Platform - .NET 6
 - RazorLight version - 2.3.1
 - Are you using the OFFICIAL RazorLight package? https://www.nuget.org/packages/razorlight - Yes

**Additional context**

**Comment by alexey62soft** [comment]
@jzabroski , can you comment on that, please?

**Comment by jzabroski** [comment]
It sounds like you want to use scoped services instead of registering things as a singleton.

The L0 Cache is not a bug, and designed that way on purpose.  It is possible you would want to update the template, but that is not a typical scenario.  Thus, the default registration methods provided in-box make the most sense.

**Comment by alexey62soft** [comment]
@jzabroski, yes, it seems I need to use a scoped approach, but, unfortunately, the library has no implemented IDisposable interface which causes OOM issues with the Scoped approach.

**Comment by jzabroski** [comment]
What would you propose?

**Comment by alexey62soft** [comment]
I would propose 2 variants:
1. Implement an IDisposable interface for IRazorViewEngine and all its custom dependencies to dispose the service properly via DI;
2. (Simpler) - add optional configuration for "L0" caching to allow configure retention policy. This will allow the usage of Singleton and refresh templates if necessary.

**Comment by alexey62soft** [comment]
Closing issue after deep investigation of the compilation process.

**Comment by ruffin--** [comment]
What did happen here? I'm designing a razor template and wanted to save cshtml, re-render, and see updates with inserted values to see the new changes. I'm not quickly seeing an example of how to invalidate the cache and run into this issue. 

I was initially hoping just removing `.UseMemoryCachingProvider()` would do it, but it appears from the above that you'll still get some default caching. ?? (That's certainly what I'm seeing.)

```
        var engine = new RazorLightEngineBuilder()
            .UseEmbeddedResourcesProject(Assembly.GetAssembly(typeof(ReportServices)))
            //.UseMemoryCachingProvider()
            .Build();

// ...

        var htmlEmail = await engine.CompileRenderAsync(uniquePathToTemplate, myModel, null);
```

(I'm running the above multiple times.)
