### ISSUE TITLE
Configuration - Adding Namespaces

### ISSUE THREAD

**Issue by joetherod** [toddams/RazorLight#53]
Engine Configuration has a collection property called Namespaces. Is this where I can add namespaces that are used in the html instead of putting the using namespaces in the html? If so, what is the format. I tried adding namespaces and it still didn't work. This will be very useful for a lot templates I have that use the namespaces defined in the web.config instead explicitly putting them in the razor. 

Thanks

**Comment by toddams** [comment]
Yep, that's a bug, namespaces are not applied. Fixing...
