### ISSUE TITLE
Make sure PreserveCompilationContext is set to true

### ISSUE THREAD

**Issue by JozefGula** [toddams/RazorLight#537]
Hello, can someone help me?

I have an ASP Net 7.0 project with RazorLight 2.3.1. I added "PreserveCompilationContext" to my *.csproj. However, I keep getting this error:

"Can't load metadata reference from the entry assembly. Make sure PreserveCompilationContext is set to true in *.csproj file"

I tried various combinations with PreserveCompilationContext but without success. Nothing in the FAQ solves my problem.

```
var engine = new RazorLightEngineBuilder()
	.UseEmbeddedResourcesProject(typeof(Program).Assembly, typeof(Program).Namespace)
	.UseMemoryCachingProvider()
	.SetOperatingAssembly(typeof(Program).Assembly)
	.EnableDebugMode(true)
	.Build();

return await engine.CompileRenderAsync("Views.EmailTemplates.Email", model);
```

Any ideas? Thank you very much

**Comment by michael-freidgeim-webjet** [comment]
The following section in .csproj works for me
 ```
 <PropertyGroup>
	<!--https://github.com/toddams/RazorLight/issues/203#issuecomment-403503671-->
	<!--https://github.com/toddams/RazorLight/blob/f72686e421a2894090c60a944471e10c1aa6a35d/README.md#im-getting-cannot-find-compilation-library-when-i-deploy-this-library-on-another-server-->
	<PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
```
