### ISSUE TITLE
Azure functions V4 issue

### ISSUE THREAD

**Issue by w1ckedmellow** [toddams/RazorLight#540]
While I was migrating to Azure Functions V4 I stambled upon an issue with a dependency.
I cannot find a way to solve this, and I'm reaching out for help.

![image](https://github.com/toddams/RazorLight/assets/147660500/cfaf5527-2801-43e9-ad11-95c9a6a16b88)

**To Reproduce**
I prepared a simple repo that recreates the issue, by running `RenderRazorLight` function.
https://github.com/w1ckedmellow/Azure-functions-v4-razor-light-issues.git

**Expected behavior**
Compilation a template from a path or Assembly embeded resource
`razorLightEngine.CompileRenderAsync( templatePath, templateModel )`

 - OS: Windows & Linux
 - Platform: .NET 6
 - RazorLight version: 2.3
 - Are you using the OFFICIAL RazorLight package? yes
 - Visual Studio version: Visual Studio Community 17.8.1

**Additional context**
Error
System. Private. CoreLib: Exception while executing function. RazorLight: Could not load file or assembly 'Microsoft. Extensions. DependencyModelJ Version=6.O.O.O

**Comment by jzabroski** [comment]
Thanks, the repro is helpful. I may take a look this weekend.

**Comment by rn1d** [comment]
I was having the same issue. I was updating my Azure Functions app from v3 runtime to v4 runtime running .NET 6.0 in-process model. While the app compiled and ran fine, I got the same exception when calling `razorLightEngine.CompileRenderAsync(templatePath, model)`.

I was able to work around it by [migrating my app to the isolated worker process model](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) running .NET 8.0. This approach might make more sense for some people, given the isolated worker model is the [recommended approach going forward](https://azure.microsoft.com/en-us/updates/ga-azure-functions-supports-net-8-in-the-isolated-worker-model/). 

I suspect RazorLight might also work in isolated mode with .NET 6.0, but in my case, going with .NET 8.0 was preferrable. 

Hope that helps!

**Comment by w1ckedmellow** [comment]
Thank you @rn1d for the tip and helpful links! :)
I migrated one of my functions to 'dotnet-isolated' and it worked smoothly.
Soon I will add a working branch of my test above. Hiope it will help otehrs.

@jzabroski  maybe it would be beneficial to add some info about this Azure functions limitations on the project readme.

**Comment by jzabroski** [comment]
Respectfully, did you read the part of the Readme where this exact topic is covered?

If you don't think it's clear enough, go submit a PR. - Don't message people saying something that's documented, isn't documented. 

![Screenshot_20240121_135725_GitHub.jpg](https://github.com/toddams/RazorLight/assets/447485/7ccf1c40-d0a1-4048-98c6-01b7f45a6dff)
