### ISSUE TITLE
Compile render string without model

### ISSUE THREAD

**Issue by vanillajonathan** [toddams/RazorLight#543]
**Is your feature request related to a problem? Please describe.**
I would just like to use a view bag without any model.

**Describe the solution you'd like**
I want the `model` parameter in the `CompileRenderStringAsync` method to be optional.
So I can do:
```csharp
var template = "Hello, @Model.Name. Welcome to RazorLight repository";
var viewBag = new ExpandoObject();
viewBag.TryAdd("Name", "John Doe");

string result = await engine.CompileRenderStringAsync("templateKey", template, null, viewBag);
```

**Comment by toddams** [comment]
Vision is to prefer model over ViewBag and other dynamic transport, we won't change API for it, sorry
