### ISSUE TITLE
Unnecessary config and container registrations when not using cshtml

### ISSUE THREAD

**Issue by grokky1** [toddams/RazorLight#57]
We store our views as strings in the database. We don't load from cshtml files.

The problem is with `services.AddRazorLight("/Views");`. The code does a bunch of stuff with the path, and [registers some objects with the DI container.](http://github.com/toddams/RazorLight/blob/master/src/RazorLight.MVC/MvcServiceCollectionExtensions.cs#L19).

That is not needed when only parsing views from strings.

It would be great to have an overload for `AddRazorLight` which doesn't need a path, and which doesn't register anything related to paths.

**Comment by toddams** [comment]
AddRazorLight registers itself inside service collection and enables you to receive dependencies from it that will be injected to your views, it's why it was added in first place. If you don't need any registrations - simply create engine using EngineFactory and call CreatePhysicall passing dummy path

**Comment by grokky1** [comment]
@toddams Yeah that's what I'm doing right now, and it works great!

However it still [adds overhead](https://github.com/toddams/RazorLight/blob/dc475fba5c4fc50b43cc637796869283b18db605/src/RazorLight/EngineFactory.cs#L22) and file system watching. If we only parse strings (never cshtml), then it's unnecessary and overkill.

**Comment by toddams** [comment]
Actually no overhead is added. When you call CreatePhysicall - you give a hint to an engine where and how it should find your views (only when using Parse method). It adds a watcher on a file I order to know if it was changed, so it can be invalidated from cache.

**Comment by grokky1** [comment]
@toddams Thanks, good to know.

**Comment by toddams** [comment]
It is only applied to a file at the moment you call Parse and it finds a file. If you use ParseString - no watchers are added

**Comment by grokky1** [comment]
@toddams Oooh ok, that makes sense now! Thanks. 😄

**Comment by Disciplemike** [comment]
Is there a way to change the scope of the injected dependencies here?
I'm having an issue with "@inject IAuthorization AuthorizationService" when the ctor of the IAuthorizationHandler is fired, it creates a new DbContext, but when the HandleRequirementAsync method is invoked, the passed IAuthorizationContext has whichever DbContext was first created.  I think it's using singleton for the injected dependencies, or at least it seems like it is.

Any ideas?
