### ISSUE TITLE
Feature request: layout for string parsing

### ISSUE THREAD

**Issue by grokky1** [toddams/RazorLight#58]
Currently we have:

    string result = engine.ParseString(content, model);

If we parse strings (not cshtml files) then we can't use a layout.

Would be great to have an overload like this:

    string result = engine.ParseString(layout, content, model);

**Comment by grokky1** [comment]
@toddams I'm gonna try come up with something myself, because I need this functionality.

Could you give me an idea where in the source code to start playing around? Am I correct in assuming that everything I need to do is in [`ParsingExtensions`](http://github.com/toddams/RazorLight/blob/master/src/RazorLight/Extensions/ParsingExtensions.cs#L29)?

**Comment by toddams** [comment]
@grokky1 do you use string parsing for templates stored in database?

**Comment by grokky1** [comment]
@toddams Yeah the templates come from the database.

**Comment by toddams** [comment]
So you need to follow this approach:
https://gist.github.com/toddams/8ebf21be9597ee48f47085b879b46ca7

This way your templates will be cached

**Comment by grokky1** [comment]
Actually, I've now looked at that code and I'm a little confused...

Is that code supporting a `cshtml` layout... that was what I wanted to know?

**Comment by toddams** [comment]
You set layout key as usual (might be an ID of your template in database) and it will resolve it from database using the class provided in sample

**Comment by grokky1** [comment]
Maybe I'm not understanding...

`GetContentFunc` and the rest of that code, seems to get the *template* from the database. But what about the *Razor layout*? That was not supported before, will it be supported now?

**Comment by toddams** [comment]
Layout - is yet another template and it's content is resolved by GetContentFunc. To set layout key you use same approach as MVC
@ {
    Layout = "templateKey"; // This is the key of layout which is resolved 
}
