### ISSUE TITLE
Resolving template names

### ISSUE THREAD

**Issue by FM666** [toddams/RazorLight#60]
I am using embeded engine.

Visual studio is checking syntax of *.cshtml files and marking a lot of problems, because it is not ASP project. (it build without problems of course).
It is annoing and one way how to get rid of that issue could be to rename the templates to something else (for example *.txt).

But I can't because RazorLight presumes the files are *.cshtml:
<pre><code>using (var stream = assembly.GetManifestResourceStream(this.RootType.Namespace + "." + key + ".cshtml"))</code></pre>

Why not use the Resource to resolve the names?

**Comment by toddams** [comment]
Yep, this must be changed, so it does not assume file is *.cshtml by the default

**Comment by toddams** [comment]
v2.0 [EmbeddedRazorProject](https://github.com/toddams/RazorLight/blob/dev-2.0/src/RazorLight/Razor/EmbeddedRazorProject.cs) has virtual "Extension" property. You can override it to set custom extension
