### ISSUE TITLE
Can not find compilation library location for package... netcoreapp1.1

### ISSUE THREAD

**Issue by danwalmsley** [toddams/RazorLight#61]
I have preservecompilation set on my csproj.
This is a project with quite a few nuget dependencies, and when I try to render a template I get:

```
System.InvalidOperationException: 'Can not find compilation library location for package 'system.data.common''
```

This can be solved by manually obtaining system.data.common.dll and putting it in the bin dir, but then I just keep getting hundreds of these.

Is it a mistake that the template engine is trying to load these dlls?

**Comment by toddams** [comment]
RazorLight loads dependencies from your entry assembly, so if it is referenced by your entry assembly - then it's an intentional behavior

**Comment by danwalmsley** [comment]
@toddams any idea why it is unable to find these assemblies?

**Comment by danwalmsley** [comment]
on .net core nugget packages are located in the nuget cache directory, until the project is published, should it be looking in there?

**Comment by toddams** [comment]
Shouldn't assemblies be put inside your bin dir after build?

**Comment by danwalmsley** [comment]
With .net core this has changed, only when you publish, normal builds for debugging etc they are located in userprofile/.nuget/packages

**Comment by toddams** [comment]
I have really no idea why does it fail. But I managed to find issues at MVC and CLI repos that may be very similar with what you are encountering, maybe this may help.

https://github.com/aspnet/Mvc/issues/5622
https://github.com/dotnet/cli/issues/3781

**Comment by dustinkingen** [comment]
I was having a similar this issue exception with `Remotion.Linq` in a project that is referencing Entity Framework Core.

I discovered using the verbose build output `dotnet build -v diag > build.log`  that some packages in my dependency tree are getting installed in `%USERPROFILE%\.dotnet\NuGetFallbackFolder` and are not getting resolved.

I solved it by:

- Rename `.dotnet\NuGetFallbackFolder` and creating a new `.dotnet\NuGetFallbackFolder` folder.
- Clear nuget cache with `dotnet nuget locals all --clear` command.
- Run `dotnet restore` on the project.

Previous to performing those steps I commented out the `fallbackPackageFolders` in the `%APPDATA%\NuGet\NuGet.config`. However, but I do not believe that matters.

```
<!--<fallbackPackageFolders>
    <add key="CliFallbackFolder" value="C:\Users\dusti\.dotnet\NuGetFallbackFolder" />
</fallbackPackageFolders>-->
```

**Comment by masterjs** [comment]
Helllo,
Not sure if it could help the investigation, but on our side, we also have the issue. If we turn to `False` the flag `MvcRazorCompileOnPublish`, then it all works properly. Related to the "refs" folder that is not there at publish time when using `MvcRazorCompileOnPublish`.

thank you,
JS

**Comment by toddams** [comment]
Not actual in .NET Core 2.0, I guess.

**Comment by sandord** [comment]
We're seeing this problem with .NET Core 2.1.0.
