### ISSUE TITLE
Disable Encoding

### ISSUE THREAD

**Issue by kidmar** [toddams/RazorLight#62]
I would like to know if there is (or will be) an option to completely disable encoding.
I'm using RazorLight to template source code and would like to have the HTML encoding completely disabled.
I know I can disable it with the @Raw, but it would be easier to have it off everytime.
Thanks

**Comment by toddams** [comment]
That sounds like a good idea. Definitely worth to be implemented

**Comment by toddams** [comment]
You can disable encoding per document like this:

````
@{
    DisableEncoding = true;
}
