### ISSUE TITLE
Nested calls of IncludeAsync doesn't work

### ISSUE THREAD

**Issue by BogdanovKirill** [toddams/RazorLight#65]
Hello ! 

Thank you for your great work! 
I love this project, and we use it heavily in production.
But I ran into a problem where nested IncludeAsync calls doesn't work correctly. 

For example I have Test1.chstml which includes Test2.chstml, and Test2.chstml also calls IncludeAsync for another 3rd template.

In this scenario I always receive RazorLight.RazorLightException: 'Can't locate a page as PageLookup is not set'. What can we do here ?

.Net core version: 1.1
RazorLight verison: 1.1.0

**Comment by toddams** [comment]
Fixed in 2.0-alpha2
