### ISSUE TITLE
Feature request: validate markup

### ISSUE THREAD

**Issue by grokky1** [toddams/RazorLight#67]
I'm generating markup, sending it to the server, storing it in a database, and rendering it later. This is a common use case.

However, before I store the Razor markup, I need to know it's valid - for example, there is no point in storing a template which includes this `@{ var thisThrows = 1/0; }`. So I create a dummy viewmodel, populate it, and try render the template, and see if it throws an exception or not.

It would be greate to have a method `public bool IsValid(string template);` which parses a template and returns whether it is valid. And it would ignore all viewmodel properties.

**Comment by toddams** [comment]
Checking if template is valid would require to generate a razor template and then compile it. So it means it should pass the whole cycle, just rendering would not occur. For me it's not very hard to implement, but every check would take about a second, is that acceptable in your case?

**Comment by grokky1** [comment]
@toddams What I do now before I save to the database, is I get the markup, I create a dummy viewmodel, then I run them through the RazorLight engine. If it doesn't throw, then I assume the template is valid.

Is that what you mean?
