### ISSUE TITLE
Method not found: 'Void Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_CompactOnMemoryPressure(Boolean)'.

### ISSUE THREAD

**Issue by 503503503** [toddams/RazorLight#69]
I have created a class to get the static page after use RazorLight.

The code is:

public class RazorLightHelper<T> : IRazorLightHelper<T> where T : class, new()
    {

        public string GetStaticPage(string templateUrl, string templateFileName, T t)
        {
            try
            {
                // Instance the Model
                var entity = new T();
                                                
                var engine = EngineFactory.CreatePhysical(@"F:\TFS Task\qin.job\src\Qin.JobManager\Template");
                
                string result = engine.Parse(templateFileName, entity);
                                
                return result;
            }
            catch (Exception e)
            {
                throw e;
            }
        }
    }

But there is a bug happened for CreatePhysical. And Error message is Method not found: 'Void Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_CompactOnMemoryPressure(Boolean)'.

I have no idea the reason and how to resolve it.

**Comment by toddams** [comment]
Tell me more about the environment you are running:
Platform,
OS,
Is it full .net or core,
What version of .net sdk and CLI tools (in case of core)

**Comment by toddams** [comment]
It's already reported that RazorLight does not work at .NET Core 2.0

We are waiting till stable release. Also UrlHelpers and HtmlHelpers are not yet implemented, but expected to be at 2.0

**Comment by darkengines** [comment]
According to https://github.com/aspnet/Caching/issues/320, `CompactOnMemoryPressure` is now back and marked as depreciated **on the nigthly version** of `Microsoft.Extensions.Caching.Memory` which may make RazorLight usable in appnetcore2.0.

If you are directly using the `CompactOnMemoryPressure` property, you should remove/replace any reference to it.

**Comment by dam3210** [comment]
Hi,
I have this error at .Net core 3.1. Does this mean .net core 3.1 is (now) not supported? 
Btw great library!

**Comment by jzabroski** [comment]
@dam3210 You can debug this yourself by opening RazorTemplateCompiler and in the file view in Visual Studio, selecting RazorLight (netcoreapp3.0) and on line 43, `new MemoryCacheOptions()`, right click on the text `MemoryCacheOptions` and go to View Definition.  You can see the class decompiled contains no references to CompactOnMemoryPressure.

So, I have no idea how you are claiming you have this error.  Please open a new ticket with your stack trace and details, like your csproj set-up.  Please don't assume a 2 year old issue is the same one you're having.  If you think it's the case, mention it at the bottom of the new issue.  We don't call CompactOnMemoryPressure anywhere in the solution, so if you want good service, please give better feedback on what's not working.

**Comment by dam3210** [comment]
@jzabroski thnx for your support. After a while, i noticed something weird with other libraries i downloaded. So start looking into that. Apparently something went wrong with Nuget Package Manger and had nothing to do with your library. Sorry to bother you, but thanks for you help :)

**Comment by jzabroski** [comment]
No worries.  Happy bug hunting.
