### ISSUE TITLE
How can I use Url.Content in the view?

### ISSUE THREAD

**Issue by DvirH** [toddams/RazorLight#70]
I got The type or namespace name 'Urlr' could not be found (are you missing a using directive or an assembly reference?)

**Comment by toddams** [comment]
UrlHelpers and HtmlHelpers are not yet implemented, but expected to be at 2.0

**Comment by Simonl9l** [comment]
@toddams - is this still in the pipeline? I'm using FluentEmail 2.8.0 and that seem to be referencing RazorLight 2.0.0-beta1 

Do you have any workarounds for @Url.Content such that I can set up a path to an image in an cshtml layout.

**Comment by jzabroski** [comment]
@Simonl9l Can you try using a tag helper that does the my-src="kittens.png".  Have not tried it myself but I believe it may work.

**Comment by Simonl9l** [comment]
Hi @jzabroski thanks - will have to investigate tag helpers. Not sure they work with FluentEmail...

**Comment by Simonl9l** [comment]
@jzabroski - all Im find in [this](https://github.com/toddams/RazorLight/wiki/Tag-Helpers) and that's not very helpful 

To be more specific, I have the StaticFiles Service enabled I have a file in my `wwwroot` and want to reference an image in my layout.cshtml.

I see in TemplatePageBase the Href method is commented out...
https://github.com/toddams/RazorLight/blob/badbd178564ba59934368161c7c140fa5906eee1/src/RazorLight/TemplatePageBase.cs#L305-L320

Any more detailed examples would be most helpful.
