### ISSUE TITLE
Target a lower version of .NET Standard

### ISSUE THREAD

**Issue by joaope** [toddams/RazorLight#76]
Hi,

Is there any reason for the library not to support a lower netstandard version?

A quick look at the references and I can see that pretty much all of them support netstandard1.3 as minimum version meaning lowering RazorLight to that would be really straight forward.

Happy to help with a PR.

Thanks for the great work!

**Comment by toddams** [comment]
Hello @joaope 
Here you can find a discussion we had before about NetStandard - #36 
I hope we can lower it at 2.0, but 1.1 will be NetStandard 1.6 only
