### ISSUE TITLE
Difference in lookup Physical/Embedded

### ISSUE THREAD

**Issue by codedevote** [toddams/RazorLight#77]
I discovered this while switching between physical and embedded template manager. When using the file based manager, references (like Layout) as well as the key parameter to the engine's Parse method require the file extensions ".cshtml" to be used. When using the embedded resource manager, the extension is appended in the template manager implementation. (See https://github.com/toddams/RazorLight/blob/master/src/RazorLight/Templating/Embedded/EmbeddedResourceTemplateManager.cs#L32). 
The consequence of all this is, that one cannot switch easily between those two different template managers.
I would suggest to accept both variants, with and without extension and make the template managers handle this accordingly (i.e. append extension only if required). 
I don't know, if other things need to be changed as well, but if you agree on the change, I can send a PR.

**Comment by toddams** [comment]
You are right, that behavior must be changed in 2.0. I will put this in a backlog

**Comment by toddams** [comment]
There is no difference anymore
