### ISSUE TITLE
"The helper directive is not supported."

### ISSUE THREAD

**Issue by btran021111** [toddams/RazorLight#78]
I have **@helper abc() {}** in my template.  When I parse my template with RazorLight, I got this message:

"The helper directive is not supported."

**Comment by toddams** [comment]
Yes, it's not supported and there is no plan to support it in the nearest future

**Comment by molinch** [comment]
@toddams Is there any way to work around that? I'm happy to help if a PR is needed

**Comment by avs099** [comment]
bumped into this today. I found this workaround:
```
@{
Func<int, int, IHtmlContent> PrintNumbers = (actual, assumed) =>
	new Func<object, IHtmlContent>(@<text>
			@((actual + assumed).EmptyIfZero())
			@if (assumed > 0)
			{
			<span class="--assumed">(@assumed found)</span>
			}
	</text>)(null);
}
```
	
and then use it as in good old times:

`<td>@PrintNumbers(12,4)</td>	`

**Comment by jzabroski** [comment]
@avs099 Thanks.  Perhaps we should add this the FAQ.
