### ISSUE TITLE
Expose compilation errors

### ISSUE THREAD

**Issue by aggieben** [toddams/RazorLight#8]
I'm trying out RazorLight in a F#/Suave.IO project I'm tinkering with, and so far it seems like a good fit because it's generally easy to use.  But one thing that has made things a bit more opaque is that compilation errors caused by the views themselves are not surfaced in the exception thrown by the host.  Could you expose these?

**Comment by toddams** [comment]
Can you please give an example of such an error, because it's not completely clear for me what errors do you mean, thank you

**Comment by aggieben** [comment]
Sure.  If I introduce a syntax error in one of my views, like this:

```cshtml
@{
        Something
}
```

Then the resulting error I get from RazorLight looks like this:

```
Starting in "/Users/ben/proj/tr/project1/src/TrinityRepublic.Publisher.Web"
[I] 2016-08-15T13:58:50.3833340Z: listener started in 93.503 ms with binding 127.0.0.1:8083 [Suave.Tcp.tcpIpServer]
[E] 2016-08-15T13:59:14.7292720Z: request failed [Suave.Web.defaultErrorHandler] exn:
RazorLight.TemplateCompilationException: Failed to compile generated razor view. See CompilationErrors for detailed information
   at RazorLight.Compilation.CompilationResult.EnsureSuccessful()
   at RazorLight.Caching.TrackingCompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.Caching.TrackingCompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at RazorLight.Templating.CachingPageFactory.CreateFactory(String key)
   at RazorLight.Templating.DefaultPageLookup.GetPage(String key)
   at RazorLight.RazorLightEngine.Parse(String key, Object model, Type modelType, ExpandoObject viewBag)
   at Program.render@17.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@850.Invoke(AsyncParams`1 args)
```

This exception tells me "you got an error", but not much more.  It doesn't tell me which view was the problem, and it doesn't tell me what kind of problem it was or where in the view it is.

**Comment by toddams** [comment]
Yes, but it gives you a hint to look at **CompilationErrors** property of your exception. It stores a list of strings with a compilation errors

**Comment by aggieben** [comment]
Ok, so the idea then is for me to log the errors myself?

**Comment by toddams** [comment]
````CSharp
try {
                System.Console.WriteLine(
                    engine.Parse(
                        "Template.cshtml",
                        new TemplateModel {
                            Source = "test",
                            Text = "text"
                        }
                    )
                );
            }
            catch (RazorLight.TemplateCompilationException e) {
                foreach (var item in e.CompilationErrors) {
                    System.Console.WriteLine(item); // Here is a compilation error message
                }
            }
        }

**Comment by toddams** [comment]
Please, let me know if sample above solves your problem

**Comment by aggieben** [comment]
That would do it for console logging purposes, but I'm not sure how I would emit those errors to the http output stream like Razor does in MVC (which would be a nice-to-have).

**Comment by toddams** [comment]
The thing is that compilation errors are already exposed, and you can reach them by iterating **CompilationErrors** property of the **TemplateCompilationException**.

The sample above demonstrates how can you show that errors in console environment. If you want to show that errors like ASP.NET MVC does - then it's up to you to build an error page and pass it to your http response.
