### ISSUE TITLE
Leaking Memory

### ISSUE THREAD

**Issue by kspearrin** [toddams/RazorLight#84]
I've been noticing that my web application is leaking memory somewhere. The leak is very slow, climbing about 1% every day on the server. In an effort try and find out what is causing these memory leaks I pulled dump files to compare about 4 days apart.

Comparing those two dump files shows the following:

![image](https://user-images.githubusercontent.com/1190944/30572506-092714b0-9cbc-11e7-8715-cd7769b71afd.png)

All of these `Microsoft.CodeAnalysis.CSharp.InternalSyntax.*` instances add up to about 185mb of memory increase over those 4 days.

Viewing the instances of them looks like it is coming from my Razor mail templates.

![image](https://user-images.githubusercontent.com/1190944/30572568-6f5cf588-9cbc-11e7-8e20-91f8b20c9067.png)

Any idea why this is happening?

Here is [my implementation of RazorLight](https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/RazorMailService.cs) for these templates: 

- [Initing `RazorLightEngine`](https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/RazorMailService.cs#L25-L30)
- [Custom embedded resource `ITemplateManager`](https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/RazorMailService.cs#L220-L245)
- [Engine parsing of mail templates](https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/RazorMailService.cs#L192-L202)

Is there something wrong with my implementation here or is there a bug somewhere in RazorLight? Thanks!

**Comment by kspearrin** [comment]
I created a simple load test to run 10,000 iterations of parsing embedded resource templates:

```c#
var engine = EngineFactory.CreateEmbedded(typeof(Program));

for(int i = 0; i < 10000; i++)
{
    var model = new BaseMailModel
    {
        WebVaultUrl = "http://google.com",
        SiteName = "Google"
    };

    var htmlContent = engine.Parse("Templates.Welcome", model);
    var textContent = engine.Parse("Templates.Welcome.text", model);
}
```

Sample project for this test: [RazorLightMemoryTests.zip](https://github.com/toddams/RazorLight/files/1312877/RazorLightMemoryTests.zip)

Diagnostic tools shows the same results as my productions dumps. There is definitely something leaking memory in here.

![image](https://user-images.githubusercontent.com/1190944/30573609-df702a60-9cc2-11e7-8321-3d0789b72db5.png)

**Comment by kspearrin** [comment]
The issue is not present in `2.0.0-alpha2`. In fact, with 2.0.0 the loop of 10,000 compilations only takes < 1 second vs the 1.x example above taking nearly 60 seconds to get through just 2,000 iterations. Why the huge difference?

```c#
public async static Task MainAsync(string[] args)
{
    var factory = new EngineFactory();
    var engine = factory.ForEmbeddedResources(typeof(Program));

    for(int i = 0; i < 10000; i++)
    {
        var model = new BaseMailModel
        {
            WebVaultUrl = "http://google.com",
            SiteName = "Google"
        };

        var htmlContent = await engine.CompileRenderAsync("Templates.Welcome", model);
        var textContent = await engine.CompileRenderAsync("Templates.Welcome.text", model);
    }
}
```

Here's memory for a 1 million iteration test which only took 60 seconds to complete:

![image](https://user-images.githubusercontent.com/1190944/30592728-f1b463fa-9d15-11e7-80d9-575f4122a503.png)

**Comment by toddams** [comment]
![7c31a1bd26ee70da803b5223ecf3d270ef8ba94711c8a9d74ef21e84571d317c](https://user-images.githubusercontent.com/6703574/30610709-bdf6eb06-9d87-11e7-81c6-245ddf02d055.jpg)

**Comment by alexsandro-xpt** [comment]
I have same problem @kspearrin with `RazorLight 1.1.0`, I'm run it in Docker Container and the container ever down in 5 minutes after get his container memory limitation.

@toddams Are you told me in the `2.0.0-alpha2` it's not happen? I will try it right now.

**Comment by toddams** [comment]
Please, let me know about the results @alexsandro-xpt .

**Comment by alexsandro-xpt** [comment]
Everything is fine right now `2.0.0-alpha2` there are no memory leak.
I'm rendering 14 template per second for email sending, apparently this is all right now.
Thank you!

**Comment by toddams** [comment]
Awesome :) I'm glad it works for you

**Comment by MFFoX** [comment]
Until .NET framework support is added back, us old timers are stuck with this memory leak. Do you have any rough ETA on the 2.0-beta2 release? Or is there something I can do to work around this?
