### ISSUE TITLE
RazorLight.MVC 2.0.0 release

### ISSUE THREAD

**Issue by shobman** [toddams/RazorLight#86]
Great to see the 2.0.0-alpha release!! 🍻
When can we expect the RazorLight.MVC 2.0.0 release?

**Comment by toddams** [comment]
I'm working on it

**Comment by jcphlux** [comment]
Any update on this even a very very alpha version. Just need very simple support.

**Comment by AlexLisong** [comment]
Hi, Thank you for creating this wonderful library, just wondering when we can get 2.0 release?

**Comment by toddams** [comment]
AddRazorLight is in main RazorLight package now
