### ISSUE TITLE
ParseString

### ISSUE THREAD

**Issue by rfrappier** [toddams/RazorLight#88]
Do you have an example on how to do the equivalent of ParseString<T>(string content, T model)
 with the new 2.0 version?

**Comment by toddams** [comment]
It is already there :)
Please, read release notes for alpha3 version - https://github.com/toddams/RazorLight/releases
___

````CSharp
string templateKey = "key";
string result = await engine.CompileRenderAsync(templateKey , "Hello @Model.Name", new { Name = "Johny" });

//Returns true, so next time you render template with this key - it will not be compiled, but taken from cache
engine.TemplateCache.Contains(templateKey); 
````
