### ISSUE TITLE
Missing StringTemplatemanager ? 

### ISSUE THREAD

**Issue by black-byte** [toddams/RazorLight#89]
Hello, i'm trying to use one of examples in .net 2.0 console app

string content = "Hello @Model.Name. Welcome to @Model.Title repository";

var model = new
{
  Name = "John Doe",
  Title = "RazorLight"
};

string result = engine.ParseString(content, model); //Output: Hello John Doe, Welcome to RazorLight repository

but there is missing how to initialize the engine.
I tried 
            var engine = new RazorLightEngine(new EngineCore(**new**... ), );

but intellisense shows only EmbededResourceTemplateManager and FilesystemTemplateManager.
Haven't found in code it also.

Is there any way to use this api to generate data from string view?

**Comment by toddams** [comment]
2.0 version is out and you can read how to render a string here https://github.com/toddams/RazorLight/releases

**Comment by black-byte** [comment]
I still cant create instance of the engine. Can you provide some code example with it ?
