### ISSUE TITLE
Not compatible with .NetFramework v4.6.2

### ISSUE THREAD

**Issue by acopapic** [toddams/RazorLight#9]
I'm trying to support netcoreapp1.0 and net462 in my project.json but it fails to restore with error message: 

> error: Package RazorLight 1.0.0-beta3 is not compatible with net462 (.NETFramework,Version=v4.6.2). Package RazorLight 1.0.0-beta3 supports: netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETFramework,Version=v4.6.2.

I found on the homepage that 

> it is also possible to use it on full .NET Framework (>= 4.6.2)

Is it?

**Comment by toddams** [comment]
I'm really sorry about that. Seems like there was a typo on Microsoft docs (which is fixed now), NetStandard 1.6 supports .NET 4.6.3 (that's a future release), not 4.6.2

I will add a support of .NET 4.6.2 asap

**Comment by toddams** [comment]
I'm really sorry about that. Seems like there was a typo on Microsoft docs (which is fixed now), NetStandard 1.6 supports .NET 4.6.3 (that's a future release), not 4.6.2

I will add a support of .NET 4.6.2 asap

**Comment by toddams** [comment]
Added .NET 4.5.1 (and higher) support
