### ISSUE TITLE
RazorLight 2.0.0 alpha3 renders '+' as '&#x2B;'

### ISSUE THREAD

**Issue by agilehobo** [toddams/RazorLight#90]
I'm using RazorLight 2.0.0 alpha3 in ASP.NET Core 2.0.0 project and found that it renders '+' as '&#x2B ;' (there is no space between B and ; but I need to add it otherwise GitHub will render as +)

Please fix it. Thanks.

**Comment by toddams** [comment]
This is not a bug, it's html encoding

**Comment by agilehobo** [comment]
@toddams,

How can I bypass it? Thanks.

**Comment by toddams** [comment]
https://github.com/toddams/RazorLight/releases/tag/2.0-alpha2

**Comment by agilehobo** [comment]
@toddams,

Work likes a charm. Thank you very much :-)
