### ISSUE TITLE
System.InvalidOperationException: 'Project can not find template with key '

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [toddams/RazorLight#91]
I have a netcoreapp2.0 console app. 

I tried to configure the engine like so:

`var engine = new EngineFactory().ForEmbeddedResources(typeof(Program));
 var s = engine.CompileRenderAsync("MyAssembly.Views.Rz.cshtml", new RzModel {Name = "shoes"}).GetAwaiter().GetResult();
`

I can see that the view is correctly embedded:
` var ass = typeof(Program).GetTypeInfo().Assembly;
            var res = ass.GetManifestResourceNames();
`

`res` returns a list of strings and one of them is `"MyAssembly.Views.Rz.cshtml"`.

What am i doing wrong?

**Update** what i was doing wrong was that for whatever reason the engine prefixes the key with the namespace of the root type (why???). So neither `MyAssembly.Views.Rz` nor `Rz` were a valid input, only `Views.Rz` was. This is definitely counter-intuitive.

**Comment by alexzaytsev-newsroomly** [comment]
@toddams is that something that is documented somewhere?

**Comment by toddams** [comment]
I a new readme file that isn't merged into master
