### ISSUE TITLE
Support for external files - partials or css

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [toddams/RazorLight#93]
It is unclear whether partials are supported.
When i tried `@Html.Partial("view")` inside a view i got 
```
Failed to compile generated Razor template:
- (10:6) The name 'Html' does not exist in the current context
```

I am trying to use this library as an engine for e-mails, so i want to define my styles once and then reference in each template file.

**Comment by toddams** [comment]
https://github.com/toddams/RazorLight/wiki/Include-(aka-Partial)

**Comment by alexzaytsev-newsroomly** [comment]
If anyone reads this - the keys in the `IncludeAsync` follow the same non-obvious naming convention as described here: https://github.com/toddams/RazorLight/issues/91
