### ISSUE TITLE
CompileRenderAsync assumes .cshtml extension on key when using FromFileSystem

### ISSUE THREAD

**Issue by danwalmsley** [toddams/RazorLight#94]
Hi,

   been trying out the new v2 branch, and so far so good. The one difference I came across is when I use a ForFileSystem, then what ever key I pass, it appends .cshtml to the key.

I can workaround this for now, but would be nice if my razor files could have a different extensions.

Good work :)

**Comment by toddams** [comment]
Hi @danwalmsley 

Please, take a look [here](https://github.com/toddams/RazorLight/blob/dev-2.0/src/RazorLight/Razor/FileSystemRazorProject.cs#L28). You can set whatever extension you want and then pass it to engineFactory.

And create an engine like this:
````Csharp
var project = new FileSystemRazorProject();
project.Extension = ".txt";

var engine = new EngineFactory().Create(project);
 ````
