### ISSUE TITLE
ViewBag - ExpandoObject does not contain a definition for 'Title'

### ISSUE THREAD

**Issue by kadamgreene** [toddams/RazorLight#97]
I have the following code:

```
var viewBag = new ExpandoObject();
((dynamic)viewBag).Title = template.Name;
var key = $"{template.Name}_{template.Content.GetHashCode()}";
StringBuilder content = GenerateContent(template, overlay);
var result = await engine.CompileRenderAsync(key, content.ToString(), model, viewBag);
```

and when I do:

`@ViewBag.Title
`

in the template.  I get:

RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition for 'Title'
CallSite.Target(Closure , CallSite , object )
System.Dynamic.UpdateDelegates.UpdateAndExecute1<T0, TRet>(CallSite site, T0 arg0)
RazorLight.CompiledTemplates.GeneratedTemplate+<ExecuteAsync>d__0.MoveNext() in _EmailLayout.cshtml
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
RazorLight.TemplateRenderer+<RenderPageCoreAsync>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
RazorLight.TemplateRenderer+<RenderPageAsync>d__8.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
RazorLight.TemplateRenderer+<RenderLayoutAsync>d__11.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
RazorLight.TemplateRenderer+<RenderAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
RazorLight.RazorLightEngine+<RenderTemplateAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
RazorLight.RazorLightEngine+<RenderTemplateAsync>d__11.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
RazorLight.RazorLightEngine+<CompileRenderAsync>d__9.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
DataToHtml.Implementations.TemplateCompiler+<Generate>d__4.MoveNext() in TemplateCompiler.cs
+
                var result = await engine.CompileRenderAsync(key, content.ToString(), model, viewBag);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
DataToHtml.Implementations.TemplateCompiler+<Generate>d__4.MoveNext() in TemplateCompiler.cs
+
                    await Generate(nested, model, builder, overlay);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
DataToHtml.Implementations.TemplateCompiler+<Process>d__3.MoveNext() in TemplateCompiler.cs
+
            await Generate(template, model, builder, overlay);
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
DataToHtml.Controllers.HomeController+<Index>d__2.MoveNext() in HomeController.cs
+
            var result = await templateCompiler.Process(new Template("parent") {
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by toddams** [comment]
````CSharp
var viewBag = new ExpandoObject();
````

You do not mark your ExpandoObject as dynamic
````CSharp
dynamic viewBag = new ExpandoObject();
````

**Comment by kadamgreene** [comment]
I found the issue.  I will make a PR with the necessary fix.

**Comment by kadamgreene** [comment]
I couldn't get a PR figured out.  The problem is in RazorLightEngine.cs, around line 85, what is in bold is missing from 2.0-alpha3 branch:

        public async Task<string> RenderTemplateAsync(ITemplatePage templatePage, object model, Type modelType, ExpandoObject viewBag = null)
        {
            using (var writer = new StringWriter())
            {
                await RenderTemplateAsync(templatePage, model, modelType, writer**, viewBag**);
                string result = writer.ToString();

                return result;
            }
        }

**Comment by SeriousM** [comment]
A workaround for now is to call `RenderTemplateAsync(ITemplatePage, object, Type, TextWriter, ExpandoObject)` yourself which is using the viewbag variable.

**Comment by kadamgreene** [comment]
Is there a new release yet for this?

**Comment by john-t-white** [comment]
When is there going to be a new release.  I am held up by this issues as well.

**Comment by szilardd** [comment]
@SeriousM what value do you set for TextWriter when calling ?

`RenderTemplateAsync(ITemplatePage, object, Type, TextWriter, ExpandoObject)`

**Comment by SeriousM** [comment]
> @SeriousM what value do you set for TextWriter when calling ?

Sorry but I can't help you with that anymore. It's too long ago.
