### ISSUE TITLE
Include/IncludeAsync not recognized by intellisense

### ISSUE THREAD

**Issue by rolandoldengarm** [toddams/RazorLight#98]
In my .CSHTML file, I'm successfully using IncludeAsync to include other templates.
It builds fine, however, VS2017 intellisense shows errors.

![image](https://user-images.githubusercontent.com/14539000/31521607-a7857298-b006-11e7-9f90-9580b3395976.png)

**Comment by toddams** [comment]
You can find half-complete updated documentation here:

https://github.com/toddams/RazorLight/tree/precompile#enable-intellisense-support
